### ISSUE TITLE
Greek Pop-over refinements

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1067]
- [x] Remove the `|` after the Greek entry
- [x] Remove Scroll Bar (and double check that all data shows)

**Comment by cdwhitfield73** [comment]
FYI, the "pipe" was displaying because at some point, there was additional information displayed after the text (part of speech link).  However, that code was no longer working, leaving a blank after the pipe.  For now, the pipe and the old link code has been removed, but at some point, I'm guessing we may want to "fix" that and have the link display again.
