### ISSUE TITLE
Duplicate check of the same word and verse

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1117]
Via @klappy: When I open the groupsData for adoption.json, there are two for the same check. 

Interestingly enough, while the key/value pairs are the same, they are in different orders. Each of which match the code in tW/FetchData/TranslationWords.js. The first on lines 202-219, the second on lines 447-465. 

The issue is that the filter is adding a duplicate of the same one. The contextId's are not found as a match because they have different key/value pair ordering. 

We need to address this issue in two ways:
- [ ] Fix the adding of duplicate contextIds to the same groupId in the filter.
- [ ] Fix the menu so that it can recognize that they are the same regardless of the contextId key/value pair order.

**Comment by mannycolon** [comment]
<img width="517" alt="screen shot 2017-04-18 at 9 19 51 pm" src="https://cloud.githubusercontent.com/assets/17072300/25159621/f4b7b38c-247e-11e7-8cce-42118965f895.png">

**Comment by mannycolon** [comment]
<img width="517" alt="screen shot 2017-04-18 at 9 19 58 pm" src="https://cloud.githubusercontent.com/assets/17072300/25159622/f9556380-247e-11e7-92d7-23bff5919cb6.png">

**Comment by klappy** [comment]
@mannycolon: Here's what I've got so far... Making it evident in the UI that we have a duplicate, and not a different occurrence.

<img width="663" alt="screen shot 2017-04-19 at 7 05 29 am" src="https://cloud.githubusercontent.com/assets/118073/25177138/d01c08e8-24ce-11e7-9f60-8c3a5612161c.png">

This way we can recognize in the UI that there is a duplicate. Behind the scenes, the menu doesn't use (contextId == ...contextId) which since it the sources were the same they should match. What I do now, is use lodash's object comparison, isEqual, that compares key/values regardless of order.

**Comment by klappy** [comment]
Looks like there was a "new" entry in the filter:

`New,Ephesians,1,6,adoption,adoption.txt, adoption ,Our adoption results in the praise of his glorious grace that he has freely given us in the One he loves.,`

I would like to propose that we don't simply remove this entry, because then we have to do that for every duplicate. I propose that we fix the code in the filter do check to see if it already exists before adding the new one.
