### ISSUE TITLE
Comment button remains outlined after deleting a comment

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1180]
I created a comment on a check and later went back and deleted the text in the comment. The comment icon was removed on the check, but the Comment button remains outlined in color.

**Comment by benjore** [comment]
See also #1183 and #1185 and #1192

**Comment by cdwhitfield73** [comment]
I think this issue is now obsolete with the changes I made to the button styling in another issue

**Comment by EllDoubleYew** [comment]
@cdwhitfield73 @cckozie should we close this issue then? What is the issue that addresses this chris?

**Comment by cckozie** [comment]
@EllDoubleYew @cdwhitfield73  No, please don't close it. It should get moved to the QA column along with Whitfield's changes that he thinks fixed it.

**Comment by benjore** [comment]
As a user, I want my eye to be drawn to where I'm supposed to be looking so that I have an enjoyable, easy time knowing what I'm supposed to be doing. 

- [ ] When a user clicks "Edit", the text edit box is highlighted and the cursor appears inside the box. (Instead of highlighting "Cancel" as it currently does). 
  - [ ] When in Edit Mode, when a user clicks "Cancel" or "Save Changes", there either should be no action highlighted or "Save & Continue" should be highlighted
- [ ] When a user clicks "Comment", the text edit box is highlighted and the cursor appears inside the box. 
  - [ ] When in Comment Mode, when a user clicks "Cancel" or "Save Changes", there either should be no action highlighted or "Save & Continue" should be highlighted
