### ISSUE TITLE
Progress scrolls right off the bottom of the menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1261]

**Comment by RoyalSix** [comment]
Is this still an issue? if so could it be explained a bit more? I don't quite understand it. @cckozie

**Comment by cckozie** [comment]
@RoyalSix Yes, it is still an issue. To replicate:
Open a project with tW
Click on a checking group and then scroll the menu so that the active check is near the bottom of the screen.
Select some text and click Save and Continue several times. The highlighted check moves down the checks menu as you complete the checks. Eventually the check being worked on is off the bottom of the screen.
Let me know if that isn't clear.

**Comment by cckozie** [comment]
Now the checks scroll off the top of the screen.
Perform the activities I described in the comment above. At some point the active check will reposition to the top of the screen. Continue performing checks or skips and at some point the active check will scroll off the top of the screen.
If it's not a lot more work it would be better to not move the checks from the bottom all the way to the top, but rather have the list just scroll up as needed.

**Comment by cckozie** [comment]
This is much improved and the checks no longer scroll of the bottom of the screen or jump around as much as before. I think we still need to do some work in this area, but I will write that up in another issue for the future.
