### ISSUE TITLE
Make sign in required to use tC 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1265]

**Comment by cckozie** [comment]
Need a new build that allows logging in before I can completely test this issue.

**Comment by cckozie** [comment]
1. If the user has a project open then signs out, all processes on the checking screen can still be performed.
2. If the user logs out he is still able to import projects from door43 using the URL.

**Comment by cckozie** [comment]
Still able to import from door43 using a URL when not logged in.

**Comment by cckozie** [comment]
Scenario 1: Fresh loading of tC with no persisted user
1. Do not log in
2. Navigate to the Import Online Projects screen
3, Enter the URL for a valid project and click Import & Select
Result: The user is bounced back to the User tab on the main modal with a snackbar message

Scenario 2: Door43 user logged out
1. Log in with a Door43 profile
2. Navigate to the Import Online Projects screen
3. Navigate back to the User tab on the main modal
4. Click the Sign Out button
5. Navigate to the Import Online Projects screen
6, Enter the URL for a valid project and click Import & Select
Result: The project is imported and the user is taken to the tool selection screen. Upon selecting a tool the user is presented the alert telling him to login before selecting a tool and is bounced back to the login screen.

Scenario 3: User logs in and starts working on a project, then logs out
1. Log in, open a project, and do some checks
2. Click on User on the menu bar
3. Sign out
4. Click Close on the main modal
5. Highlight some text
Result: The user is presented the alert telling him to login before making a selection and is bounced back to the login screen.

The user also does not receive any error message when attempting to upload until he clicks that button.
The user is allowed to export to csv without any error message.
**Expected behavior: The user should be confined to the login screen until he has successfully logged in.**

**Comment by benjore** [comment]
I agree with @cckozie 's final assessment - Upon opening tC, a user should see the welcome screen with the "Get Started" button. When clicked, the Main Modal is opened to the user tab. The user should not be able to open a different tab until there is a valid login - either local user or Door43 user. 

To prevent circumventing this problem, we will also need to implement #1495 as well.

**Comment by ihoegen** [comment]
@benjore @cckozie I'll make it so users are forced to stay at the login page when they logout then.

**Comment by cckozie** [comment]
When on the Welcome screen, clicking either Project or Tool on the menu bar causes the You must be logged in... alert to momentarily display and then disappear. The alert should not disappear until the user dismisses it.
