### ISSUE TITLE
tHelps external link bringing up wrong dialog

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1335]
- When clicking "Biblical Imager - Common..." at the bottom right of the screen, this warning dialog came up. Obviously I'm still in online mode, so that is not the right message to be bringing up. 

![screenshot 2017-04-28 09 34 50](https://cloud.githubusercontent.com/assets/13352518/25533351/fd0de2bc-2bf5-11e7-84ff-88a9db765d9b.png)

**Comment by klappy** [comment]
There is another related issue that may need another fix. 

I can recreate it on a check that shouldn't be there, but that is a separate issue (Names shouldn't be included in keywords, I'm wondering if there is something not filtering like it use to.) Open a Titus project, and tW. The first check, Apollos, in the helps article, there is a link to a translationAcademy article that goes to the Wiki, and that's not where it should go. It renders the missing content page on the wiki, when it should go to tA somehow: You are here: home » door43 » en-ta-translate-vol1 » src » master » content » translate_names.md

**Comment by klappy** [comment]
Also, tN tool doesn't appear to render links for me, it just gives me the unconverted markdown: [[en:ta:vol1:translate:figs_intro|Figures of Speech]]
[[en:ta:vol2:translate:bita_part1]]

**Comment by cckozie** [comment]
The "Biblical Imager - Common..." link is now linking to this page. Is that correct?
![image](https://cloud.githubusercontent.com/assets/8171759/25728730/87990da8-30f6-11e7-9f32-f8cfee4b0d80.png)

Is this a problem with the source or our code?

At the bottom of the tHelps article on apostle, some of the links go to a Door43 page, several bring up a blank form, some appear to be missing spaces in the link's text, clicking on jamessonofzebedee does bring up a tHelps article, but clicking on the How to Translate Names link in that article also link to Door43.

**Comment by EllDoubleYew** [comment]
No it is not an issue with the sources. Here is the article it is supposed to go to https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bita_part2.md

No idea why it is doing this. I'll figure it out.

**Comment by cckozie** [comment]
The issue described in the first comment is now fixed assuming that https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bita_part2.md is the correct link.
There continues to be several other problems, some noted in my earlier comment with the screenshot:
1. Clicking on tHelps links opens empty windows. See links in tHelps for "gift"
![image](https://cloud.githubusercontent.com/assets/8171759/26119565/3fc7b722-3a33-11e7-8505-e7fb58f94d6e.png)
2. Each time I click on one of the links in 1. above, it opens a new window rather than reusing the existing one. All of those windows are hidden except when hovering on the tC icon in the Windows taskbar. See #1456 
3. Picture icons that should be links aren't. See #1552 
4. Forward slashes still missing in some links. See #1553

**Comment by cckozie** [comment]
Saw some different problems in 0.6.26.5
Links are not rendered as links
![image](https://cloud.githubusercontent.com/assets/8171759/26277468/a8d677cc-3d4d-11e7-8787-b8ec539a5b2d.png)

**Comment by cckozie** [comment]
0.6.26.6
This is still a problem:
![image](https://cloud.githubusercontent.com/assets/8171759/26422063/67f3a12a-4096-11e7-9c1f-cf9bfd0b0bbf.png)
![image](https://cloud.githubusercontent.com/assets/8171759/26426895/86fe909a-40a8-11e7-93d8-f903ebe0d1b1.png)

**Comment by cckozie** [comment]
It would be great to also fix the issues in #1665 and #1678 at the same time.

**Comment by cdwhitfield73** [comment]
Fixed a bunch of issues with links.  May not have fixed every possible scenario.  Suggest writing up new issues for anything found.  This issue is getting very long and I won't be fixing any Fails.
