### ISSUE TITLE
Problems with message displayed when opening a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1369]
These issues occur both on Windows and OSX.
Sometimes the message window is a fairly large square, sometimes it is that same width but only high enough to display the progress bar.
Sometimes the window is completely blank, sometimes, it has the tC logo, sometimes it has the progress bar.
Even when the progress bar is displayed, it never shows the actual progress.
In 0.6.21 sometimes the message window does not appear for several seconds, then finally appears fractions of a second before the load is complete.

**Comment by benjore** [comment]
Related to: #1307

**Comment by EllDoubleYew** [comment]
This has actually been an issue since 0.0.1 some of the original progress bars (pre-refactor) even did this. 

My gut tells me it has something to do with render priority being taken away from the loading modal. Hooray JavaScript. @RoyalSix I don't know how this was remedied because it IS better than it used to be. What changed?

**Comment by klappy** [comment]
There are a few issues around the percentage and progress circle that I wonder if it is worth hiding it until we can get them resolved. Behind the scenes we are using 100% of our CPU to do the work, and the updating of the progress is queued up after the work is done. We would have to do a lot of work to make this and it could take days potentially a week to address it.

We have spent a few days already on this issue in previous versions of the progress.

Should we hide it and fix it later or invest a few days to address it now?

**Comment by klappy** [comment]
@mannycolon: Your gut feeling of doing this in the middle of componentWillMount may be a solution that addresses this. In other words, instead of fixing the issue by spawning an electron web worker we could try to not run this in the same "stack" by calling it strategically and not when it mounts. That way it isn't trying to re-render so much. It's worth a shot.

**Comment by cckozie** [comment]
I believe this will be fixed by #1499

**Comment by cckozie** [comment]
0.6.26.4
I have not seen this particular issue now for several builds.
