### ISSUE TITLE
tN check does not show highlighted text in source

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1377]
And the text in the Please select... box is not all contained in the verse.
![image](https://cloud.githubusercontent.com/assets/8171759/25594457/428c5dae-2e86-11e7-9eda-e40e824509da.png)

**Comment by klappy** [comment]
We don't currently do anything for "..." because of a few issues. One is a better understanding of every way they are used to make sure the way we handle them isn't creating more problems. 

Since this one not only uses "...", but it is spread across multiple verses, it creates another complication.

@benjore: Can we bring these up to the stakeholders to discuss how to move forward? These are some issues we've punted on for a while, but we need to start figuring out how to handle it :D

**Comment by cckozie** [comment]
I wasn't making a comment on the ellipses, but was only using them to abbreviate my text:)
I believe the real issues is that the text to be checked is not all in a single verse. It is my understanding that we are not going to address this in the current release, so I'm moving it back to the Issues Backlog.

**Comment by cckozie** [comment]
duplicate
