### ISSUE TITLE
App hangs when user tries to load a project from the door43 list and there is no Internet connection

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1386]
1. The project had previously been opened.
I went to the project list on door43 when the Internet connection was closed. I clicked the Load Project button for the project, then selected a tool (I shouldn't have been able to get this far), and the dialog with the spinning logo and progress bar came up. The app hung in that state.

2. If the go through the same process but on the door43 project screen choose a project that had not been opened before, I get this error message:
![image](https://cloud.githubusercontent.com/assets/8171759/25598520/1387e13a-2e9b-11e7-8c92-94497d592f42.png)

**Comment by cdwhitfield73** [comment]
This issue is not so much about the internet connection and basic error handling, as it is about trying to import a project that already exists locally.  First, we need a good user story of what you want to happen.  Do we offer options like merge or overwrite?  Then we need to write code that detects that the project already exists and gives the user the appropriate options.

**Comment by benjore** [comment]
#1498

**Comment by cdwhitfield73** [comment]
This issue has been resolved with #1498.  You can no longer import a project if it already exists locally.  A message is given to the user and the app is left in a workable state.
