### ISSUE TITLE
Create Local User

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1407]
- [x] Creating a Local User
  - [x] When clicking on "Terms and Conditions" in the main screen, the screen will change to show the Terms and Conditions (as per the mockup)
    - [x] Clicking "Go Back" will return the user to the main Create Local User page
    - [x] Clicking one of the hyperlinks will open a modal with that document
  - [x] The "Create" button is deactivated until the checkbox is selected and a username is entered
  - [x] When a user is created, that user stays "logged in" until they "log out"
  - [x] If a user logs out, they must create a new local user (there is no list of created usernames available in the app at this time) or log in with Door43
- [x] In "Import Online Projects" show ""Unable to connect to the online projects. Please log in to your Door43 account." for the top part, keep the URL import enabled.
- [x] In "My Projects" - when the user clicks "Upload" return a message saying "Please log in to Door43 to upload your projects"

**Comment by Thajny** [comment]
![local user - step 2](https://cloud.githubusercontent.com/assets/21183377/25721994/16df93c0-30d8-11e7-8b17-0e0f1ec4b404.png)
![local user step 3 1](https://cloud.githubusercontent.com/assets/21183377/25721993/16dea5a0-30d8-11e7-995c-36d5ee22a11d.png)
![local user step 3](https://cloud.githubusercontent.com/assets/21183377/25721992/16ddc374-30d8-11e7-8601-b162ed2e1639.png)

**Comment by mannycolon** [comment]
@benjore are these the *terms and conditions* we want to use for tC local user?
It seems like this `terms and conditions`are more for creating a door43 account. Do we want to use the same verbiage? or modify this version a little bit and make it fit a local user description?

**Comment by mannycolon** [comment]
@benjore where do i find those external links ??? for `statement of faith` and `Creative Commons Attribution-ShareAlike 4.0 International License.`

**Comment by benjore** [comment]
@mannycolon These all need to be available locally. Just make them into a little pop-up window, similar to what we have for the tHelps pop-up. 
Statement of Faith: https://unfoldingword.org/faith/
Creative Commons Attribution-ShareAlike 4.0 International License: https://creativecommons.org/licenses/by-sa/4.0/

As far as everything referring to Door43. Use that for now. We can go back and change it as needed.

**Comment by cckozie** [comment]
1. When a local user navigates to the Import Online Projects page, the project list area on that page momentarily displays a no projects found message which is quickly overwritten by a list of Door43 projects. I have no idea of what repo the list is from.
2. The hyperlinks on the Terms and Conditions screen do not work.
3. When a local user attempts to upload to Door43, the error message states "Error Uploading: Please log in to Door43 to upload your project." rather than what was specified in the list of requirements above.
4. When logging in to a Door43 account, as soon as any typing begins in the username field in the Door43 area, the terms and conditions checkbox gets enabled which is confusing since we don't require agreeing when logging in with a Door43 profile.
5. After navigating to the terms and conditions the username edit box is cleared.

**Comment by benjore** [comment]
Note: the user should not have to scroll to the bottom of the Statement of Faith (or any of those screens) before they can "go back". It should be available without needing to scrolling.

**Comment by mannycolon** [comment]
1. [x] When a local user navigates to the Import Online Projects page, the project list area on that page momentarily displays a no projects found a message which is quickly overwritten by a list of Door43 projects. I have no idea of what repo the list is from.
2. [x] The hyperlinks on the Terms and Conditions screen do not work.
3. [x] When a local user attempts to upload to Door43, the error message states "Error Uploading: Please log in to Door43 to upload your project." rather than what was specified in the list of requirements above.
4. [x] When logging into a Door43 account, as soon as any typing begins in the username field in the Door43 area, the terms and conditions checkbox gets enabled which is confusing since we don't require agreeing when logging in with a Door43 profile.
5. [x] After navigating to the terms and conditions the username edit box is cleared.

**Comment by cckozie** [comment]
@benjore - Are any of these things we want changed for the upcoming release?
1. On the license page in tS, the first sentence is "This is a human-readable summary of (and not a substitute for) the license" and the word "license" is a link to the CC-BY-SA 4.0 license site.
2. For Attribution we state "You must give appropriate credit, provide a link to the license,  and indicate if changes were made. " Shouldn't the link be to the source to which they are making attribution rather than to the license? In tS, a link is provided to door43.org
3. The text on the messages displayed when attempting to Import and Upload is slightly different than that specified in the first comment on this issue.
The current import message is "You must log in with a Door43 account to see projects here."
The current upload message is "Error Uploading: Please log into your Door43 account."

**Comment by benjore** [comment]
1. License page
  A. Add a title "Creative Commons Attribution-ShareAlike 4.0 License"
  B. "This is a human-readable summary of (and not a substitute for) the license" and the word "license" is a link to the CC-BY-SA 4.0 license site. https://creativecommons.org/licenses/by-sa/4.0/legalcode
2. "Attribution - You must attribute the work as follows: "Original work available at https://door43.org/." Attribution statements in derivative works should not in any way suggest that we endorse you or your use of this work." 
3. Change upload message to: "You must log in with a Door43 account to upload your project."

**Comment by cckozie** [comment]
The issue listed in the 2 comments above have been moved a new issue #1548
