### ISSUE TITLE
Main modal screen size

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1473]
0.6.20
Windows machine at max resolution (1366x768)

Main modal flows below bottom causing scroll bar on far right. Using that scroll bar scrolls the entire modal up and down. The entire modal should fit in this screen size.
![image](https://cloud.githubusercontent.com/assets/8171759/25761710/6b86fcfa-31a1-11e7-98ad-d19f00c0f3ad.png)

**Comment by cckozie** [comment]
@benjore The height issue has been fixed. Yesterday we discussed that the width should be expanded as well so as to not have the buttons stacking, but no verbiage was added to this issue for that. Should I create a new issue for that, or do we want to add it to this one?

**Comment by cdwhitfield73** [comment]
@cckozie @benjore My suggestion would be to create a new issue for the width.  I discussed this with Manny yesterday.  The real problem is not the overall width of the modal, but rather the "language" field in the project list.  We need to restrict it to a maximum width, and force the language to wrap if it is too long.  Right now, it is wrapping the whole table, including the buttons, to make room for long language names.  However, there are some languages that are so long, there is no way we can make the modal big enough to handle them, so just increasing the modal will just be a bandaid fix for some scenarios.  If you make this a separate issue, I would potentially have time to play with working on formatting the table better, rather than giving Manny a fail to deal with.

**Comment by cckozie** [comment]
I created issue #1549 to address the width problem.
