### ISSUE TITLE
Unable to select text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1509]
0.6.22
Performed all of the steps outlined in the first "paragraph" of #1508
Switched back to tN
Selected text for the first 3 checks in Active or Passive
Highlighted the text for the 4th check in that group, but the text does not stay selected
I can select individual words, but dragging to select does not work if it starts at the beginning of the verse and contains more than two words

**Comment by klappy** [comment]
@cckozie Are you able to consistently recreate this? I'm having difficulty.

**Comment by cckozie** [comment]
@klappy Yes, easily repeatable on both my Mac and Windows. I don't even need to follow all of the steps I had described. Just import https://git.door43.org/qa98/es-419_eph_text_ulb, open it in tN, and try to make this selection:
![select](https://cloud.githubusercontent.com/assets/8171759/25975488/255f4cc8-3674-11e7-83a7-a38c589bf086.png)

**Comment by klappy** [comment]
"cual  no" in the file, vs "cual no" rendered on the screen is the text causing the problem. 

@cckozie: Thanks for the specific example. As soon as I saw it I had a gut feeling it was whitespace. HTML treats multiple spaces as one, and since the selection is from the HTML, it only knows of single spaces. For comparison sake, not editing the source, we can treat multiple spaces as one. This way the source is kept as the user intends but we can still detect how many occurrences there are which is now finding 0, but will find the proper amount.
