### ISSUE TITLE
Problems in tS after uploading from tC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1581]
I don't know if this is something we need to fix in tS or tC, but we should figure it out before release.

I imported a project from Door43 into both tC and tS.
I did some tW checks in tC and uploaded the project to a different repo than the import.
I logged into tS as the user whose repo the project had gotten uploaded to.
I made a change in one chunk in tS.
I attempted to upload the project, got the changes have been made message as expected, and responded to the message with the Merge option.
Now when I attempt to open the project in tS I get this error message:
![image](https://cloud.githubusercontent.com/assets/8171759/26129904/ed3eee9c-3a57-11e7-8f78-8048a26e767d.png)
Will send feedback so we'll have the tS log file.

**Comment by cckozie** [comment]
The same problem exists if I just import a tS project that has been imported and uploaded from tC.

**Comment by cdwhitfield73** [comment]
@benjore @cckozie  Yes, this is definitely a problem in tS.  It can't handle the "apps" folder that tC creates in the project.  It doesn't even matter if any checks have been made, just importing a tS project into tC and then immediately uploading it back to Door43 now makes it unusable in tS anymore.  It's too bad we didn't think to try this before 11.1 was released, because it's a really simple fix, but now it will take another release of tS to handle it.

**Comment by cdwhitfield73** [comment]
There isn't anything we can do in tC to fix this problem (except stop creating an apps folder) so I am moving this to QA.  We probably need an issue created in the tS repository and marked as Urgent.
