### ISSUE TITLE
[0] Populate resources reducers 

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#1831]
## Overview
- Input data is from #1833 
- Reducers should provide same data that currently exists
- Reducers can be organized to new data structure from #1833 

## Notes
- Data comes in from FS in #1766 and copied to ~/translationCore/resources folder
- Data read from ~/translationCore/resources folder to reducers as needed.
- BCV: should handle all reference bibles this way.
- tW should only load current word article in reducer not all articles in memory/reducers.
- tA for tN should only load current article in reducer not all articles in memory/reducers.
- contextId gives which article should be read into current article whether tW or tA for tN.

**Comment by klappy** [comment]
@mannycolon @RoyalSix: Bibles should already be done. The ones left should be tW, tN, and tA. Lexicons are pending for future implementation.

Bibles are already brought in at chapter level, based on current contextId.

tN is already loaded in by groupId in the index for the menus from in the project.
tA can be loaded in by the groupId as well but from the user resources folder, it only needs to bring in a single .md article.

tW is kind of already loaded in by the groupId, except that the content is all loaded in memory. We need to only load in the .md article based on the current groupId like in tA's case.

The challenge will be to dynamically load something for the links inside both tA and tW. If we abstract a helper function that retrieves the link's article, then the links can be updated to follow those. We still need to keep the current article in the reducer so that they do not lose their scrolling location when they return from visiting the links.

If we work together we should be able to get this done today.
