### ISSUE TITLE
SPIKE: What would it take to handle #1991, #2109, and #718? 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2112]
Is our data structure robust enough to handle it? 
Can our data structure handle all the checks for tN & tW and the whole Bible, all at once?
Do we need to pivot to an internal database?

#1991, #2109, and #718 
1. What are the current limitations of our app?
2. What will it take to transcend those limitations?

**Comment by RoyalSix** [comment]
# Evaluating Functionalities #
  ## Ability to display all tools (tN, tW, other) in a verse-by-verse mode (#718) ##
  - We are rendering everything based off the groups index/data, in order to change the menus layout it will mostly deal with changing those.
  - Proposals:
    1. Leave the groups index and transverse through the groups data check by check (binary tree) appending all checks from the first reference to the last chronologically onto a new object and then sending that to the store as the new 'groupsObject'
        - Our menu setup still requires groups in the way its rendered and represented in the store, and so it would make sense to group by chapters. (Can happen during initial filtering) 
        - This process would take a lot of time to process on load for bigger  books and might make sense to pre process
    2. Generate a separate groups index for verse by verse mode on a tool basis
        - This makes the amount of tools concerns separate from the data being presented
  - Performance: There would be no hit in performance aside from the initial loading for processing. This can be done before they select the tool or on the first load. It might make sense to do this processing for our main content outside of tC because this will be a popular use case for looking at checks, probably just as popular as categorical checking.
    - If we processed all the checks for each tool individually in a chronological order then merging the checks when they select the tools they want would be a lot more efficient, with almost no performance hit.
 - Multiple tools & Verse by verse should be separate concerns

 
  ## Ability to set the range for multiple books (#1991) ##
  - Assumptions:
    - Will have USFM text in target language for wanted range
    - Way to represent multiple book range from source text in usfm/manifest
  - Proposals:
    1. Just load in the others books groups data.
        - The groups index should be the same
        - I also believe the contextID, book/chapter/verse loading can stay the same as long as we update the bookAbbr during the context Id change before any other actions.
          - the book abbreviation its contained in `projectDetailsReducer.params.bookAbbr` and in `projectDetailsReducer.bookName`, which we may want to look at consolidating for consistency.
   2. Alias the projects in a separate folder with list of projects as such:
```

    {
    "projects": [
        {
            "id": "1co",
            "name": "1 Corinthians",
            "repo": "https://git.door43.org/burje_duro/am_1co_text_ulb.git"
        },
        {
            "id": "2co",
            "name": "2 Corinthians",
            "repo": "https://git.door43.org/burje_duro/am_2co_text_ulb.git"
        }
    ]
}

```

## Ability to select and check with multiple tools at once (#2109) ##
 - This will only work for tools with the same view just different menu data, need to check for that somehow
 - Due to code like this 
`let Tool = currentToolViews[currentToolName];` 
`    if (contextId && contextId.tool !== currentToolName) {
      nextProps.actions.changeCurrentContextId(undefined);
    }` 
and the frequent use of `currentToolName` as a unique identifier. It limits our options to represent two uniquely identified tools in our data
 - Proposals:
    1. Make one tool as a wrapper for tN and tW which just consumes different data and renders it in the same way.
        - This would result in getting rid of the namespace problem because it would be all under one namespace such as <em>translationHelps</em>.
        - This method would require more initial setup, and less patching
    2. Leave the namespace as one of the tools because ultimately it doesn't matter if they have the same view and send in both the tN data and tW data for groups index/data.
        - This would have to result in removing checks for things like if the current tool is the one being loaded in the contextId from the code snippet above.
        - This method would require more bandages to patch

**Comment by RoyalSix** [comment]
## Conclusion ##
No internal database needed

**Comment by RoyalSix** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7216901-249627154_2-s1-v1.png?transparent=1&palette=1&width=246)
