### ISSUE TITLE
Skip / Close dialog is not dismissed when user clicks Skip

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2131]
beta.54
I opened an Eph project with tW, clicked on the God group, then clicked Save & Continue and Skip on each check as they came up. When I did that on the check for Eph 2:6, the Skip/Close dialog did not disappear and the checking screen remained dim after I clicked the Skip button. It now continues to do that on each check.
![image](https://user-images.githubusercontent.com/8171759/28072143-baa45526-6617-11e7-9066-bc5c9c9908e8.png)

**Comment by klappy** [comment]
@cckozie: I'm working on this issue now. It appears to be caused by bad data in our previous import of tW data. There is only one occurrence of God in the verse and there are two in the menu for this verse. Fundamentally, we are shifting to using predefined occurrences from the notes instead of us generating this list. So the fix to what caused the data issue is now irrelevant. However, the problem still exists and still needs to be addressed.

We can address this in two ways:
1. When this occurs, handle it more gracefully and skip to the next valid check that does exist.
2. Ensure this doesn't happen in future imports.

**Comment by cckozie** [comment]
PLEASE IGNORE THIS COMMENT AND GO TO THE NEXT
It's really the task in #2136 that failed, but since it's attached to this issue, I'm failing it too.

**Comment by cckozie** [comment]
After looking at this again, I think the user is going to be confused/frustrated by two behaviors:
1. The check got skipped with no indication of why
2. After it was skipped, the user is unable to go backwards from the following check. The Save & Previous button appears to be active but doesn't do anything.
I think we should add code to handle these issues as follows:
1. When before skipping the check issues an Alert stating "This check is invalid and will be skipped."
2. Have the skipping code executed both when moving forward and backward within the checks.

**Comment by cckozie** [comment]
Need to wait until I can load an Eph project

**Comment by cckozie** [comment]
Looks good in beta.53
