### ISSUE TITLE
ProjectValidation: Project Information

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2354]
## Front End
- ProjectValidation ProjectInformation Instructions
  - Move Attention data to instructions
  - Remove cancel import
- Create ProjectValidation ProjectInformation components
  - ProjectValidation/ProjectInformation Folder with index.js for the main component
  - Form for manifest details
  - Book drop down

## Back End
- ProjectInformationReducer
  - manifest, project save location and progress of tools
- Update prop references from params to ProjectDetailsReducer.manifest
  - Update book id\name to come from manifest.project.id\name
- ProjectInformationActions
  - Manifest save/load to fs in project folder
  - Action to edit the ProjectInformationReducer

**Comment by cckozie** [comment]
Most of this is not because something is broken, but rather to give us a more consistent look and feel.
1. All text should be the same font and size as the current word “Contributors” (and the same size as on the copyright page)
2. The labels should be bolded and in a fixed size and position above the entry field
3. There should not be any animation when focus is set to one of the entry field
4. Change the text from “Language ID” to “Language Code”
5. Focus should be set to the first empty field, if there is one. If all fields have data, set focus to the Language Code field.
6. Do not automatically add the user as a Checker (that currently happens when importing from USFM)
7. Checkers should not be a required field
8. Left to right is in the language direction list twice
![image](https://user-images.githubusercontent.com/8171759/29584334-038370d6-8749-11e7-9bc7-8cbceca86428.png)
9. Per #1711, the list of books is to contain both the book name and abbreviation

**Comment by mannycolon** [comment]
# QA Tasks
- [1] Make all labels bold, fixed size and fixed position above the entry field. 
- [1] Text should be the same font and size as the current word “Contributors”
- [1] Remove animation from text fields and remove "checkers" as required field.
- [1] Change the text from “Language ID” to “Language Code”
- [2] Remove Left to right is in the language direction list twice
- [2] Add book abbreviation to book names drop down list

**Comment by cckozie** [comment]
This looks good except for #6 above. The user is still being added as a checker.

**Comment by mannycolon** [comment]
@cckozie That is something related to `usfm` i can't handle that from the Project information check
