### ISSUE TITLE
SPIKE: Questions & Feedback on Storyboard Mockups

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#276]
As a developer, I want to ask questions so that I know I understand the intended workflow.

As a developer, I want to provide feedback, so that I know my perspective is taken into consideration.

https://invis.io/2T981SLSF

Spend Friday & Monday

 * [x] Manny
 * [x] Luke
 * [x] Ian 
 * [x] Jay

**Comment by EllDoubleYew** [comment]
- Okay the desktop folder names are hilarious I will give you that. "klappys" real name got me.
- I like how loading a project the first time feels like a part of the tutorial rather than living inside of the main app this time. I think it gives it a more intuitive aspect that it did not have before.
- What happens when you click "+ more" when you are choosing an app when you load a project? Does that just open the package manager or should it do something entirely different?
- In the storyboard, the extra menu options show when you mouse over the tC logo. I also noticed that there is another menu slider on the top right of the screen. I like both but I don't understand why there are two. Can we just decide on one or the other or is there a reason to have both?
- What exactly happens when you click on a box in the scripture pane? It just shows a black x for me right now. What options should the user need to have to load scripture references?
- LOVE the idea of the picture of the folder then the app for the chevrons on the left. Click the folder to change projects click the app to change apps. Perfect.
- I also really like that now we have an instruction to the right of the selection area rather than showing the buttons right away. This cleans things up a bit and makes it easier for the checker to see what exactly they should be doing with all the information that is being thrown at them.
- I notice that the arrow below the scripture pane is pointing away when it is expanded, but the arrow on the translationAcademy pane is pointing in when it is expanded. Is there more information to be shown in the scripture pane or should that arrow be facing the other direction in this storyboard?
- I would love to see your vision for what loading a new project looks like in terms of workflow. Are you fine with the current modal we have or do you see a better way to do it?
- If space is still available in the lower portion of the screen. What is the opposition to expanding the comments field by default rather than it being a dropdown? I just wonder if that exploration to click and use it will rival a default to expand it. 
- We need to come up with a clever way to let the user know that if they mark something as correct or flagged they can still go back and change it. Right now it sorta looks like it is "locked in" once you select one or the other rather than having the option to go back and change it if you want.

I think that sums it up from what I saw. Hope that covers the bases well enough to iterate through this UX design process. I like the direction its going but I just feel like a little more tweaking can be done before we dive head first.

**Comment by RoyalSix** [comment]
- When it comes to loading projects I have two questions 
  - Are the ones being displayed from local and from the current users online door43 projects? 
  - How would a user enter a project from online? 
- I think that the two menu bars that contain load, sync, settings etc. is redundant. I think that just having the one on the left is enough. 
- I like the new way words/phrases and the verses are displayed. How does that look for longer words that don’t fit in the phrases menu. Is that line next to the word an indication of its status? 
- Is there a reason for so much white space when the comment box is closed? 
- I like how we can pop the scriptures out, is that a modal that is in front of everything else on the same page? Or a different box/page that is moveable? 
- Theres a save button, what happens if I don’t save and want to switch projects, or just quit the app? Should we prompt the user to save? 
- Might be just me, but I feel like there should be a higher priority on the font of the text in the current book you are looking at (Gateway Language) vs. the text asking if it is correct in context etc. - I found the on hover for the mockup to be a little unintuitive. Maybe that is because of the fact that I am used to clicking it already? Haha 
- I really like how the two buttons you need to get things “done” are right next to eachother. Advanced users will also appreciate this! 
- Is the verse menu collapsible? I feel like you don’t always need to see all the verses, and we could have a next button near the save button. Could save us space and keep us from rendering information the user made not need. 
- The mockup states we are using the scripture pane for verses, is that correct? If so what do I do if I want to see the entire chapter?

Ill put my comments on the mockup page as well. This can be used as a reference.

**Comment by ihoegen** [comment]
It looks pretty good to me. My only real issue is with everything being collapsible, I see that being a performance issue with so much "hidden" data. Hopefully we'll be able to sort something out, because I really do like the proposed UI. I do see collapsible data being the new modal system, hopefully better though. 

Also, will users be overwhelmed by such a large amount of data being displayed on the screen? Should we default to collapsed data, or should we start with everything open.

**Comment by Thajny** [comment]
Feedback for Feedback:
**Luke** 
• The "+more" would open up the package manager.
• I have no idea whats going on with the menu. Theres no clear direction for it right now - some SO's liked having the top menu toggle while others liked the tC icon. I made the tC icon hoverable and not clickable because I think it's still too vague and the user may have a hard time finding it otherwise.
• Any time a box with a black x shows up, it means its a content box. Basically I was lazy/ran out of time, but It serves as a placeholder for whatever content would make sense.
• I dont know the proper way to put chevrons for drop downs, so ignore that
• The mockups aren't really to scale, so there might not ever be an awkward amount of space, but having margin space is always good (things butting up against an edge are harder to look at).
• I dunno what to do with the toggle, because that is a good point. Maybe it glows? Does something to show it still functions?

**Jay**
• I didn't factor in the different ways a user could load a project. But I think anytime the user is prompted to load a project, local files should probably take priority and then the other options are available somewhere.
• I dont know yet what longer words will do. Manny has been asking me that for a few weeks now haha. Open to suggestions on that.
• The way the Scripture pane is set up is kind of like a drawer. It will expand downwards. Ive heard suggestions of just making it a modal pop out - not sure which to do with that.
• I think the save button is just there for aesthetics. The program/app should be saving everything automatically, so even if they don't save, their progress isn't lost.
• I dont know what you mean about about text priority. From what I understand, you can hover/click on text in the scripture pane to get additional information (I dont know what that is). Other than that Im not sure I understand what you mean.
• Having the verse (sub) menu collapsible is an interesting idea. I know concerns have been made about all the moving parts in the UI. I'll leave that up to you guys as far as what to do with that - I like the idea (especially if you can navigate without using the menu)...but things might get real glitchy with nearly everything moving.
• Scripture pane is where everything but the target language goes. This is reference material and expanding the drawer will load the rest of the chapter (You scroll to view it all).

**Ian**
• I agree, everything being scrollable and resizeable could be problematic. There probably should be some fixed elements.
• I think we could probably emphasis in the tutorial walkthrough that you can minimize things but by default have everything showing. It might freak them out if everything is hiding by default (maybe they didn't pay attention to that part of the tutorial). But I can see how it might be intimidating too.
