### ISSUE TITLE
SPIKE: Research Rubric Tool

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#280]
Tool to answer questions in the rubric:

https://unfoldingword.org/quality/

Look for this heading: The Process for Determining Quality

## Groups/categories:
- Overview
- Naturalness
- Clarity
- Accuracy
- Church Approval

Some of these are binary, yes/no, and others are ternary, 0/1/2, disagree/somewhat agree/strongly agree.

**Comment by mannycolon** [comment]
## Workflow
- Chapters will be displayed on the left side of the content area.
- Checks / questions will be displayed on the right side of the content area
  - The user will go through the questions by clicking the chevrons.

**Comment by mannycolon** [comment]
## What does it take to develop the tQ tool
- Make tQ Generate it's own checkData file.
- Set up appropriate data-structure  to save questions response data (checkstatus).
- Implement a fetchdata.js
- Implement a View.js for tQ.
- Implement its own package.JSON file (where sub-tools dependencies will be specified).
- tPane integration.
- commentBox integration.

## Things to be determined:
- How would questions be stored. 
- Workflow.
- Report generation / report cards structure.

**Comment by mannycolon** [comment]
## tQ: Propose Layout

**Overview**
![overview](https://cloud.githubusercontent.com/assets/17072300/20084362/c7eb808c-a52f-11e6-88c4-4d7fed5be9a3.jpg)

**Naturalness** 
![naturalness](https://cloud.githubusercontent.com/assets/17072300/20084369/d9822d64-a52f-11e6-9853-03038160c886.jpg)

**Comment by mannycolon** [comment]
## Questions

## **Overview**
1. no | yes This translation is a **meaning-based translation** that attempts to communicate the meaning of the original text in ways that are natural, clear, and accurate in the target language.
2. no | yes Those involved in checking the translation are **first-language speakers** of the target language.
3. no | yes The translation of this chapter is in agreement with the **Statement of Faith**.
4. no | yes The translation of this chapter has been done in accordance with the **Translation 
   Guidelines.**

**Naturalness:** “this is my language”
1. 0 1 2 Those who speak this language and have heard this chapter agree that it is translated using the **correct form of the language.**
2. 0 1 2 Those who speak this language agree that the key words used in this chapter are **acceptable and correct for this culture.**
3. 0 1 2 The illustrations or stories in this chapter are **easy** for people who speak this language **to understand**.
4. 0 1 2 Those who speak this language agree that the sentence structure and order of the **text** in this chapter is **natural and flows correctly.**
5. 0 1 2 The review of the translation of this chapter for naturalness included **community members** who have not been directly involved in creating the translation of this chapter.
6. 0 1 2 The review of the translation of this chapter for naturalness included both **believers and non-believers,** or at least believers who are relatively unfamiliar with the Bible so that they do not know what the text is supposed to say before they hear it.
7. 0 1 2 The review of the translation of this chapter for naturalness included **speakers of the language from many different age groups**.
8. 0 1 2 The review of the translation of this chapter for naturalness included **both men and women.**

## **Clarity:**  “the meaning is clear” 
- 0 1 2 This chapter is translated using language that native speakers of the language agree is **easy to understand**.
- 0 1 2 Speakers of this language agree that the translations of **names, places, and verb tenses are all correct** in this chapter.
- 0 1 2 **Figures of speech** in this chapter make sense for people in this culture.
- 0 1 2 Speakers of this language agree that the way this chapter is s**tructured does not distract from the meaning.**
- 0 1 2 The review of the translation of this chapter for clarity included **community members** who have not been directly involved in creating the translation of this chapter.
- 0 1 2 The review of the translation of this chapter for clarity included **both believers and non-believers,** or at least believers who are relatively unfamiliar with the Bible so that they do not know what the text is supposed to say before they hear it.
- 0 1 2 The review of the translation of this chapter for clarity included **speakers of the language from many different age groups.**
- 0 1 2 The review of the translation of this chapter for clarity included **both men and women**.

**Accuracy**

## “the translation communicates what the original source text (or original language texts, in the case of Bible texts) communicated”

0 1 2 A complete list of all **important words** in the source text for this chapter has been **used** to help ensure all terms are present in the translation.

0 1 2 All important **words are translated correctly** in this chapter.

0 1 2 All important words are **translated consistently** in this chapter, as well as in other places where the important words appear.

0 1 2 **Exegetical resources have been used** for the entire chapter to identify and resolve potential translation challenges.

0 1 2 Historical details in the source text **(like names, places, and events) have been preserved i**n the translation.

0 1 2 The **meaning of each figure of speech** in the translated chapter has been compared and aligned to the intent of the original.

0 1 2 The translation has been tested with **native speakers who were not involved in creating the translation** and they agree that the translation accurately communicates the intended meaning of the source text.

0 1 2 The translation of this chapter has been **compared against at least two source texts**.

0 1 2 The translation of this chapter has been **compared against the original texts (Hebrew, Greek, Aramaic)** to check for correct lexical definitions and intent of the original texts.

 **Church approval**

## “the naturalness, clarity, and accuracy of the translation is approved by the Church that speaks that language”

no | yes Church leaders who have checked this translation are **native speakers of the target language,** and include someone who **understands well one of the languages in which the source text** is available.

no | yes People from at least two different church networks have **reviewed** the translation of this chapter and agree that it is **natural and clear**.\* (Note: this addresses the first part of the community check for Level 2.)*

no | yes Church leaders from at least two different church networks have **reviewed** the translation of this chapter and agree that it is **accurate**. (This addresses the final aspect of Level 2, the Church check).

no | yes The leadership or their delegates of at least two different church networks have **reviewed** the translation of this chapter and endorse it as a **faithful translation** of this chapter of the Bible in this language. (This addresses Level 3.)
