### ISSUE TITLE
SPIKE: Research Selector Bar

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#320]

**Comment by mannycolon** [comment]
researching the implementation for the **selector bar** brings up this question should we just find another design to represent the same but in a simpler and much easier way that we could implement. Is it worth it to spend so much time to implement it or should we just find another option.

**Comment by mannycolon** [comment]
what we could do is render the current group and current check in the same position. so that we illustrate the selector bar but this would mess up with the ability to scroll the other checks for the current group.

**Comment by mannycolon** [comment]
Another option could be dividing the submenu into two components. the component on top will have the checks that have been "completed" and the component at the bottom will have the current check highlighted in blue illustrating the selector bar and below it will render the others unchecked checks.

**Comment by mannycolon** [comment]
the same with the menu that holds the group names.

**Comment by mannycolon** [comment]
@EllDoubleYew I would like to have your input for this. i definitely feel a bit lost with this.

**Comment by mannycolon** [comment]
@ihoegen @RoyalSix we need your input here?

**Comment by EllDoubleYew** [comment]
My implementation plan was as follows: 

1. Create two extra big list items in BOTH the headers menu and the submenu. These extra items will sit at the top and the bottom of each list. Their height should = one half the height of the menu - half the height of a single menu item; This will allow both the first and the last element of each menu to be in the middle of the menu if you scroll all the way up or all the way down. Another important note is that since this will be dependent on the number of checks these spacers may change depending on how many checks there are in the submenu, so I would make it a child component of the menu; Or just implement an anonymous component in the menu thats size reacts to how many menu items there are. This is the first step and its not super easy to implement; as a matter of fact it may actually be the hardest. I was thinking of having some kind of spacer component that just filled the empty space with a set width and height but you might think of a better way so don't limit yourself to that.
2. Oh boy this is the fun one. Make each sub menu item line up with its header at all times. The way you want to do this is with ReactDOM Nodes. I don't want to type all this up but they aren't as hard to work with as they sound and I have used them somewhere in TC before.[ Here is a good introduction and some healthy googling should let you know the rest ](http://blog.vjeux.com/2013/javascript/scroll-position-with-react.html). What you want to do is always scroll to a position in the submenu so that the active check is in the middle. This is what those extra spacers above and below do so that we can always achieve this. Your scroll position in the submenu is always going to = the height of the spacer at the top + the sum of the heights of all the checks above the active check.
3. Theres a couple of ways to prevent the user from messing this alignment up once you do it. The most logical approach for now would be to just lock the scrolling of the submenu but I know that may be annoying in the long run. The long term approach will be to automatically load the check that lines up with the header item as the scroll. This runs into some performance issues due to the number of renders being called while you scroll so we will have to do some render muting to prevent that from becoming too big of an issue. This kind of automatic check loading is probably a story in its own so I dont know if I would try and implement this before review tomorrow but if you see a way to do it it would be a really nice touch.
4. Now for the little blue highlight around the header and the submenu item there are a billion ways to implement this. My original idea was to work with Thomas to get some high res image of this component from his mockups and then float it so that its right "empty space" always rests on the active menu header item; then as long as you completed step 1 and 2 correctly the second empty space inside of that selector image should fall right over the active check.  As for the up and down buttons just give them an onclick that calls the old school nextCheck and previousCheck functions that we were using in the old UI. I think I know a place you can dig those up if you cant find them anymore.

And walla you have completed the selector bar. Slack me if you have questions I will be avilable async all day.

**Comment by ihoegen** [comment]
I agree with @elldoubyew 's approach, but I think for this to work best, it will have to be separated and broken down into as many smaller components as possible. Also would it even be possible to finish today? There seems like a whole lot.

**Comment by RoyalSix** [comment]
First, getDOMNode is depreciated
So we will have to either find another method to get the nodes properties or my suggestion which would be alot easier is to hardcode a height for the menu to always start at (which is not all that bad).
After that all we have to do is create a blank space div with a changing height, that corresponds to the height of the menu item. This could live in the Menu container and pass a ref down to the submenu

**Comment by RoyalSix** [comment]
`class EmptySpace extends React.Component {
  constructor(){
    super();
    this.state = {
      height:253,
      top:0
    }
  }
  render(){
    return (<div style={this.state}> </div>);
  }
}`

**Comment by RoyalSix** [comment]
`class EmptySpace extends React.Component {
  constructor(){
    super();
    this.state = {
      height:20,
      top:0
    }
  }
  render(){
    return (<div style={this.state}> </div>);
  }
}
`

**Comment by EllDoubleYew** [comment]
@RoyalSix I did not realize that. So same implementation but with css positions instead of the scrollTop values? We might need to postpone this conversation depending on what all has been done thus far.

**Comment by RoyalSix** [comment]
Actually looks like they moved it to ReactDOM.findDOMNode()
this post has a good scroll implementation
http://stackoverflow.com/questions/30495062/how-can-i-scroll-a-div-to-be-visible-in-reactjs

**Comment by EllDoubleYew** [comment]
@RoyalSix can you find any other documentation on that? i tried to find the findDomNode() function with out any luck.

**Comment by mannycolon** [comment]
@EllDoubleYew @RoyalSix I already started working on this. i was able to either make it scroll to the top or bottom. have not been able to make it scroll to the middle yet.
