### ISSUE TITLE
SPIKE: Research Progress for the Groups

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#321]

**Comment by EllDoubleYew** [comment]
The biggest question mark for this spike was "is it possible to create visual progress bars without using a library?". I am always a big fan of not taking on dependencies whenever possible so I tried to see how I could do this the vanilla way. [I found this library that would make things a lot easier](https://github.com/kimmobrunfeldt/progressbar.js) and started to replicate Thomas' design in a JSfiddle before I realized that its not gonna like react.

Luckily React is more prominent than it used to be and I was able to find [this port of the library to react compoonents](https://github.com/kimmobrunfeldt/react-progressbar.js). This is the direction that I am going with the progress bars because they allow me a lot of flexibility with how they look and it is a relatively small library. This is the best direction to go for implementation.
