### ISSUE TITLE
SPIKE: Research Approach with new Scripture Pane

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#322]

**Comment by mannycolon** [comment]
- The scripture pane could have its own settings.JSON file where we save which scripture will be display. In other words, we save which scripture/s to display from the scriptures save in common.

- Should source language, gateway language, and target language be in the scripture pane by default ?

- Make the scripture sources removable and allow users to add with the limit of 4.

- Make the scripture tPane not scrollable.

- Hold the fours scripture sources in the scripture pane state or just save in a variable inside the constructor.

- Determined how many verses will be displayed in each scripture source pane.

- scripture pane should take in what sources the current tool wants to use as default or to start off.

**Comment by mannycolon** [comment]
@ihoegen @RoyalSix we will also need your input here?

**Comment by ihoegen** [comment]
Maybe we could have drop down menus, that allow the user to select what goes in which pane, and that could be saved in the local storage settings object, but also make it easy to switch. Also, while we're working on SPONGE, should we make it so the books are divided on a by chapter basis?

**Comment by mannycolon** [comment]
@RoyalSix ^^

**Comment by EllDoubleYew** [comment]
So I will break this down component by component in how I would implement, Ill start with the smallest of the components that we will need and work my way up to the container for it all: 

Word: We need to break down word components for when we want to use the lexicon to look up a words definition (I know this only applies to greek for right now, but we need a universal implementation so that we can apply it to Hebrew as well for OT). These word components will essentially just be a span with the text of the word inside, as well as some common parent onClick function we pass down to them as a prop that looks up their definition in the lexicon (via their language they pass up as a parameter) and will in turn display a popover with the defintion of the word. This should be the smallest component.

(Optional) Verse: I don't remember if we are using verse components in the tpane right now but it wouldnt hurt to have them. They would just have a verse number as a prop they get from their group container and should be responsible for rendering the little verse number at the beginning of the verse as well as all of the words inside of the verse. I noted this as optional because if we really wanted to we could implement without this component but I think it just cleans things up a little bit. Thats a decision the team needs to make as a whole before we jump into it. If we decide to implement the verse, the verse component should be able to use itself as a reference to get a string from the store of that verse, then it should break that string down into word components.

ReferenceContainer: This is going to be the area that is responsible for rendering all of the verse components that will be relevant to the current check. I don't remember if we said that we wanted to continue to render the entire book or just cut it down to 3 to 5 verses but either way this will be the box that holds an individual language reference. This box should be tied to the store to get information about the where the current current check is. It should use its own state to determine which language reference it is getting all of this from. Note: This is not the component that is responsible for adding and removing references from the pane, it is just the parent holder for one references verses.

ReferenceWrapper: Not a lot going on with this component other than holding a a reference container and rendering a close button the user can do to get rid of the resource. Each resource should be wrapped in a ReferenceWrapper. In the future if we wanted to add "Drag and Drop" functionality to this component it will make our lives a whole world of a lot easier if we have a component dedicated to making that happen (Which this component could hold the role of). Alternatively we could have this close functionality tied to the Reference container but again thats a team decision we need to make. I could make all kinds of arguments of why it might be nice in the long run to have another wrapper around all this stuff but we may decide not to.

NewReference: This is your "[+] Add a new resource" button we have talked about. Clicking could do a lot of different things depending on where thomas wants to go with the new resource workflow. This could display a modal, display the selection in the menu, or display the resource selection in itself (just depends on what thomas wants to do, cant remember if there is a mockup for this workflow or not). Regardless we are going to need a component that will handle selecting which resource you want. This component will essentially be a static component that will always float to the right side of the pane and can be clicked whenever to add another ReferenceWrapper with the props that we get from the user (Being language). This component could also just be a part of the parent container, from an architectural standpoint I think it lives better as its own component but we could put it as a static element of the ParentContainer too if we REALLY needed to.

ParentContainer: We can call this really anything we want but this is just the big container that will hold all of the stuff I have talked about so far. Klappy mentioned that for now if a user wants to reorder the references inside its safe to assume they would need to remove and re-add references in the order that they want. So this container wont really do much other than have its children ReferenceWrappers and the always-present NewReference component.

[Important side note about collapsibility: This will all need to be in the HorizontalCollapsible component that we have talked about making before, we will use a very similar component for tHelps except it will be vertical.]

LoadResource: For now this will probably have to live in a modal and will be displayed whenever the NewReference component is clicked. It will look in the store to see which resources are available to be loaded given what project you have already loaded and give the user a list to select from. When they load one it will pass the language down as a prop to a new ReferenceWrapper, which in turn will pass it down to the Reference container so it can use the language ID and the current check information to populate the correct verse and word components inside of that reference. *This component needs to be developed in a way that is as modular as it can possibly be* since we know that it may not always live in a modal lets write it so that we can eventually use it anywhere.


I think that covers all the bases for the Scripture Pane. This is just one implementation of the near infinite ways there are to do this, thats just how I would do it personally.

**Comment by RoyalSix** [comment]
The implementation ('data flow') will be very similar to the old TPane. The only difference is really when you are importing another "Pane".
We have to remember some things when implementing this:
    - Each Pane needs to be basically its own "TPane" containing only one "Pane"
        - What I mean by this is, every TPane has a certain amount of data storage for it traveling in and out of the checkstore.
        - Keeping this structure allows for easier data storage ('We will have to reference each one by its name maybe the same as the title')
    - We will have to create another wrapper component for all the "TPanes"
    - When a component gets closed it is no different than rendering null on a div and deleting the relevant checkstore data. 

The implementation of the UI:
    - I suggest using a library for the pop out animation
    - The only other tricky thing is the auto scroll
    - I'm not sure how we even want this but I'm guessing it will be the same as before; They all move on a reference selection:
        - This literally will have one small change, instead of searching just the TPane we will search each TPane in the checkstore (maybe a new field in common called "arrayOfPanes")
