### ISSUE TITLE
SPIKE: Research Testing Libraries to Use in tC

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#324]

**Comment by ihoegen** [comment]
Relevant Links:
https://www.npmjs.com/package/electron-mocha
https://mochajs.org/
https://github.com/electron/spectron
https://facebook.github.io/jest/docs/tutorial-react.html

I think for in terms of testing the API, [Electron Mocha](https://www.npmjs.com/package/electron-mocha) would be best. It would encourage a truly modular API, and tests can be run from the command line, instead of the browser like other testing suites. Another nice feature of Electron Mocha is that instead of using Phantom JS like mocha does, it uses Electron, which is considerably faster. Like it's parent, Mocha, it can also run with TravisCI. An issue we are going to run into no matter what test suite we use, ModuleAPI does do some visual things, but Electron Mocha allows access to the renderer process, and we can even access localStorage. Another nice feature of Electron Mocha is it, like Mocha, plays well with testing suites that are specifically designed for React and Electron, which will be talked about later. Also, if we continue building node modules for specific things, like the USFM-Parser, Mocha would be a great tool to test with, and to integrate into those modules. It also integrates with the Electron API, which allows us to do some cool things as well, such as opening windows, and copying/pasting text. 

For the testing of the application, [Spectron](https://github.com/electron/spectron), by Electron/Github seems like a good fit. It is compatible with Mocha, and thus Electron Mocha, can run on TravisCI, can handle promises and async programming, can get the console outputs, which alone is pretty awesome, and it does so much more. This would be good for making sure the app can at least startup, which is an extremely crucial part of builds, and if it doesn't startup, it can read the console and tell us why. The fact that Spectron can access the console is pretty great, and I see many future uses for that feature alone. It also looks like we could use it to interact with the CoreStore, CheckStore, and other parts of the application that are more architectural than interface-based. However, Spectron does not appear to have that great of a use case when it comes to the actual UI. But it could probably do just about everything else when it comes to code stability. Like Electron Mocha, it can also access the Electron Renderer, but unlike Electron Mocha, it can tell us what's happening under the hood. This data is valuable in that we could use it to create a more efficient application.

Finally, there's [Jest](https://facebook.github.io/jest/docs/tutorial-react.html). Now it does seem cool, and there is a ton of functionality included with Jest, it just looks extremely complicated. However, Jest allows us to do things that none of the others do. Jest can give us feedback on what our components look like, and how they're composed. The issue with Jest however, is it won't play well with any of the other testing libraries, and it doesn't look like it can work with TravisCI. I would definitely file this under "Maybe Later", but that does not take away from it's potential.

So in conclusion, there isn't a single testing library that will cover everything we need. We need one that can work well with node modules, so Electron Mocha, which can be used to test things such as the ModuleAPI, the USFM-Parser node module, and others. There's also the Spectron, which will be useful in making sure that the application is able to start up and there is no issues in doing so. It could also possibly be used to test the Stores, other parts of the Module API, and localStorage. It's also very compatible with Mocha, and therefore is compatible with Electron Mocha. Then there's Jest. It could be the best possible testing library for the UI, it is just complicated, and may not even be the right choice. But it is a good choice for testing Components, and could clue in to some weird bugs we've run into over the last couple of months.
