### ISSUE TITLE
Windows build reinstalls Git even though the same version was already on the PC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3269]
It doesn't cause problems but seems superfluous.

**Comment by da1nerd** [comment]
yes right now it's not checking to see if Git is already installed. If we added that then this would be avoided.

**Comment by cckozie** [comment]
@neutrinog Why can't we just check to see if Git is installed and then install it if it is not there rather than prompt the user who probably won't know how to answer the prompt?
The current installer is rather kludgy if the user choses not to install git and it is not already on the computer.

**Comment by da1nerd** [comment]
@cckozie because thus far I have not been able to reliably determine if Git is installed. From the documentation on the related tools I'm using it "should" be working, but it's not. Therefore I allowed the user to manually check/uncheck installing Git.

My original design was to check it automatically and disable it from being changed by the user. So I'm punting it with the current implementation so I can clear my head while working on other things. No use hitting my head against the wall while being unproductive.

We can keep this issue open and look at this again.

**Comment by cckozie** [comment]
@neutrinog Makes sense. I'll leave it open for now.

**Comment by da1nerd** [comment]
This is deprecated with the inclusion of #4960

**Comment by cckozie** [comment]
Now N/A
