### ISSUE TITLE
SPIKE: Decide Which Unit Tests have biggest ROI

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#329]

**Comment by ihoegen** [comment]
So this spike will need to be started off with the files that play major parts in the functionality of translationCore. It will then break into an assessment of what functions need to be tested, and the importance of each of these functions. The following list is sorted in order of importance

- Upload.js
    - **~~The functions need to be exported out of the modal, and access needs to be allowed from outside files~~** - **Done** 
    - sendFilePath - Arguably the most important function out of the file, maybe even the app.
    - saveManifest - Not as important, but is used enough times to warrant testing.
    - getParams - A lot of processes depend on correct params.
    - saveTargetLanguageInApi - A correctly loaded target language is crucial.
- ~~LoadOnline.js~~ **Done**
    - ~~openManifest - Handles most of the LoadOnline process. Should be expanded outward, so that testing can be done on the inner workings.~~
- AccessProject.js
    - loadFromFilePath - We need to be able to reopen projects, using only their file paths. 
    - loadCheckData - Important that it functions so work can continue.
- ~~ImportUSFM.js~~ **Done**
    -  ~~Hopefully in rewriting Upload.js, we can use some of those functions through the usfm import process.~~ 
    - ~~openUSFMProject - Needs to work in order for USFM files to work~~.
    - ~~saveTargetLangeInAPI - Need a properly working target language.~~
- ~~PackageManager.js~~ **Done**
    - ~~downloadPackage - Needed, along with compilePackage to test any of these.~~
    - ~~compilePackage - Needed to test the rest~~ **Covered in downloadPackage test.
    - ~~getPackageList - Need a list of packages available.~~
    - ~~getLocalList - Need list of packages installed.~~
- ~~USFM-Parser~~ **Done**
    - ~~This node module does enough to where tests should be written for it.~~
- CoreStore and Core Actions
    - Need to find a way to test these, shouldn't be difficult. 
Actions to take before tests can be written: 
- ~~Rewrite Upload.js, making it so that it's functions can be used elsewhere. Also rewrite anything that uses a copy of these functions, or a hidden ref.~~ **Done**

**Comment by ihoegen** [comment]
When we feel that this Spike is complete, it'll be best to go out and start writing these individual stories.

**Comment by ihoegen** [comment]
@RoyalSix We should work on dividing these amongst ourselves
