### ISSUE TITLE
Encode tW Links in UHB

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3365]
This is the Old Testament counter part to #3204.

**Comment by jag3773** [comment]
Blocked by #3414

**Comment by jag3773** [comment]
@neutrinog There is nothing blocking this task now.  Please go ahead and encode the tW links into the [UHB](https://git.door43.org/Door43/UHB) so that we can have people go through and verify them.

**Comment by da1nerd** [comment]
@jag3773 do you want me to limit this to the word occurrences or perform a global search?

**Comment by da1nerd** [comment]
@jag3773 also, I realized I forgot to convert the book ids inside of the usfm files to usfm format.
Please merge in this PR https://git.door43.org/Door43/UHB/pulls/329

**Comment by da1nerd** [comment]
@jag3773 how come in UGNT the strong numbers have 5 numbers e.g. `G39720` but in UHB they only have 4 e.g. `H0376`?
Is this discrepancy an oversight?

**Comment by da1nerd** [comment]
I've created a PR for the tW links. Please review the questions above first including merging in the update to the UHB usfm files first.

https://git.door43.org/Door43/UHB/pulls/330

**Comment by da1nerd** [comment]
And this is the error log to PR 330

[errors.log](https://github.com/unfoldingWord-dev/translationCore/files/1697262/errors.log)

**Comment by lrsallee** [comment]
Interesting that the Ruth sample has all possible tW tags pre-listed, so the task is to remove all the incorrect ones instead of mainly adding the correct ones as in the UGNT. I don't have an early opinion on whether that is faster or slower than the UGNT process. Will need to work on Ruth and see. I suspect it will depend on how wide I am able to stretch out the window on my monitor :)

**Comment by da1nerd** [comment]
It may be faster to verify the strong numbers in tW. Because if you fix one tW it will fix all instances of it in the text. Then I can re-run the script.

**Comment by lrsallee** [comment]
I see in Ruth 1:2 that we are going to need to add milestones to connect names such as Bethlehem. I assume there are many similar names throughout the OT.

\w מִ​בֵּ֥ית|lemma="בֵּית לֶחֶם" strong="m:H1035" x-morph="He,R:Np"  x-tw="rc://*/tw/dict/bible/names/bethlehem" \w*
\w לֶ֖חֶם|lemma="בֵּית לֶחֶם" strong="H1035" x-morph="He,Np"  x-tw="rc://*/tw/dict/bible/names/bethlehem" \w*

**Comment by lrsallee** [comment]
I went through several verses, and I don't see an easier process, since we are working from the Hebrew roots, and there are so many renderings for each. This way, the correct tW tag is probably in the list. Therefore, it is like the classic tale of Michelangelo creating the David statue by "chipping away any stone that wasn't David."

**Comment by jag3773** [comment]
@lrsallee So do you think that we can refine what is in the list by either modifying our script or by modifying the Strong's numbers that are listed on the tW pages?

Or are we stuck with a manual review for the rest of of the job?

**Comment by benjore** [comment]
@jag3773 What is still needed for this one?

**Comment by jag3773** [comment]
I don't think this is a tC developer issue anymore, it is on the content team's shoulders now.  I'll close.
