### ISSUE TITLE
Word Alignment opens to blank screen with console error

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3486]
0.8.1-alpha.13-46601e0
[43-LUK.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1580048/43-LUK.usfm.zip)
![image](https://user-images.githubusercontent.com/8171759/34267923-6e8f5d68-e644-11e7-91d4-81b3df5c73f1.png)

**Comment by PhotoNomad0** [comment]
@benjore @klappy @jag3773  - the crash here is because we only have greek alignment data for 80 verses in luke chaper 1. But the ULB's index.json file says there are 82 verses in Luke 1.  How should we proceed on this?  Since the ULB only has 80 verses in Luke 1 it looks like we should fix the index.json file as well as make sure we have a fail safe when the verse counts mismatch.

**Comment by PhotoNomad0** [comment]
### Tasks
- [ ] [2] Fix Word Alignment tool and translation core to handle missing alignment data.
- [ ] [2] Unit testing.
- [ ] [1] PR Review
- [ ] [1] PR Review 2

**Comment by cckozie** [comment]
0.8.1-rc.5-852f639
Works on Windows. Need to test on Mac.

**Comment by cckozie** [comment]
0.8.1-rc.6-4b73715
Works on Mac.
