### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3594]
From #2236

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Update npm package and find any broken legacy functionalities

**Comment by RoyalSix** [comment]
Looks like bootstrap Modals are not officially supported in React 16 https://github.com/react-bootstrap/react-bootstrap/issues/2812#issuecomment-335015479

**Comment by cckozie** [comment]
Import icons are disabled. Can only click on the box with the words.
![image](https://user-images.githubusercontent.com/8171759/35410435-0df1baa2-01db-11e8-83e0-2f185f39ecf0.png)

**Comment by cckozie** [comment]
### This moved to https://github.com/unfoldingWord-dev/translationCore/issues/3697

0.8.1-alpha.15-b862dfd
The issue above still exists, and now I see another one on the Mac.
The text on the menu bar sometimes disappears.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0f10582e-122b-4742-a008-19477ec3e35a)
The text reappears when hovering over the menu bar.
This happens randomly in alignment when dragging words back to the word list. Sometimes as you begin dragging the word, the text in the menu bar flashes one or more times. Then occasionally when the word is dropped in the word list, the menu bar text stays hidden.
I'm assuming this is a React 16 issue since I've never seen it before.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [4] Debug libraries to get modal to show again
- [ ] [1] PR
