### ISSUE TITLE
Update to zaln attribute

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3781]
* update `k-` to `zaln-` attribute, per https://forum.ccbt.bible/t/usfm3-alignment-data-encoding/34 -- in the USFM.js library
* update the English ULB that is already in there (find and replace)

Backwards compat with `k` NOT REQUIRED.

Note (maybe this needs a separate issue): We need to use milestone start/end markers correctly, I think our examples so far are missing the `\*` on the start markers.  We need to use `x-strong` in milestone attributes because `strong` is only a recognized attribute for word level attributes.
See the comment https://github.com/ubsicap/usfm/issues/59#issuecomment-365707495 .

**Comment by klappy** [comment]
Just sharing a few things... doing a brain dump on the issue. 

All alignment is currently using a milestone marker, `\k-s ... \k-e` that extends the key term marker `\k`. Because we are putting the Greek/primary language words from the alignment in the key term milestone marker's attributes, it wasn't ideal since they aren't key terms. After talking with the USFM3 team, they recommended making our own custom attribute via the `\x-custom-s ... \x-custom-e`. Since we are doing alignment, we will use `\zaln-s ... \zaln-e` which is the milestone adaptation of the custom marker `\zaln ... \zaln*`. The `-s` and `-e` designate the start and end of overlapping markers.

We preserve the above through the VerseObject representation of the USFM3. 
So the tag attribute would be `\zaln` and the type attribute would be `milestone` to signify that there needs to be a `-s` and `-e` added when parsing and generating USFM.

@PhotoNomad0 and @jag3773 what are your thoughts on the above? Does that match up with the way you see it?

**Comment by jag3773** [comment]
@PhotoNomad0 @klappy (cc @mannycolon @benjore ) I have updated our notes everywhere that I could find to reference `zaln` instead of the previous idea of x-aln.  This is due to feedback on the example we posted at https://github.com/ubsicap/usfm/issues/59#issuecomment-365707495 .

Please also note:

* We need to use `\*` to end the milestone start marker
* We need to use `x-strong` in milestone attributes because `strong` is only a recognized attribute for word level attributes.

See the updated USFM example at https://forum.ccbt.bible/t/usfm3-alignment-data-encoding/34.

If we need to create a new issue to handle these, let's do that.

**Comment by mannycolon** [comment]
@jag3773 

> We need to use x-strong in milestone attributes because strong is only a recognized attribute for word level attributes.

Thats additonal to what we spoke. In that case I feel we should make a new story for that. It seems like it would require a lot of changes.

**Comment by jag3773** [comment]
@mannycolon note that we could keep our internal data using `strong` but just make sure our import/export uses `x-strong` if the attribute is in a milestone.

It's worth noting that `strong` should still be used if it occurs in a word level attribute.

**Comment by klappy** [comment]
That should only be the concern of the usfm-js library as it does all of the conversion to and from usfm especially the adding and removing of ‘x-‘ of custom attributes. Also, I’m more concerned with this changing so frequently as we implement it. I almost feel that we need to leave it as is and change it once the spec hasn’t changed for 30 days.

**Comment by klappy** [comment]
After reading all of the background conversations, I better understand the context and the confidence for the changes made now.
