### ISSUE TITLE
Upgrade to Material UI Next

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4305]

**Comment by RoyalSix** [comment]
- [ ] [1] Upgrade to Material ui next
- [ ] [1] Find outdated implementations

**Comment by benjore** [comment]
@neutrinog Why should we do the upgrade? Can we leave the core as is and upgrade the tools to Material UI Next?

**Comment by da1nerd** [comment]
The biggest benefit is better tooling and components. e.g. testing certain material components will be easier, we won't have to custom write as many building blocks, also there is better support since the version we are using is no longer receiving active development.

Regarding using both libraries. Yes we can install both side by side. There is a `mui-legacy` npm package that points to the `0.2` version of Material UI.

Therefore in tc we'll simply run `npm i mui-legacy material-ui@next`. Then in tC core we'll need to change all import statements from `... from 'material-ui'` to `... from 'mui-legacy'`.
In this way tC core will continue to use the old components, however the tools may choose to use either depending our which import statement they use.
