### ISSUE TITLE
Allow importing of any Door43 projects except for projects with 0.7 checking data

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4333]
In a temporary "fix" for v0.9 we prevent importing of Door43 projects if we determine that they may be older than 0.8.0 so that we don't risk causing problems with the checking data. If there is no tW or tN checking data in the Door43 project, we need to allow Door43 projects to be imported into tC.

Problem: tC is blocking more projects than just projects with 0.7 checking data (including fresh tS projects in Door43). This problem was caused when a quick fix was made to prevent checking data made in tC 0.7 being overwritten in 0.8/0.9.

**Comment by PhotoNomad0** [comment]
#### Notes:

- Previous Issue was: https://github.com/unfoldingWord-dev/translationCore/issues/4278
  - PR was in https://github.com/unfoldingWord-dev/translationCore/pull/4300
- looks like old projects will have checking data here: `.apps/translationCore/checkData/selections` and very old projects will have checking data here: `checkdata/TranslationNotesChecker.tc` or `checkdata/TranslationWordsChecker.tc`

#### Test Projects:

| test project  | project type   | expected results   |
|---|---|---|
| https://git.door43.org/tc01/es-419_eph_text_ulb  | ts project  | should import  |
| https://git.door43.org/tc01/abu_tit_text_reg | ts project with complex merge conflict| fails due to merge conflict parse error and shows general import error |
| https://git.door43.org/photonomad0/sw_tit_text_ulb_L3  | 0.7.0 tc project w/checking | show error that it is not supported.  |
| https://git.door43.org/tc02/fr_eph_text_ulb  | 0.7.0 tc project w/checking  | show error that it is not supported.  |
| https://git.door43.org/photonomad0/ceb_jas_text_ulb_L-  | Pre-0.7.0 tc project w/checking  | show error that it is not supported.  |
| https://git.door43.org/tc01/ar_mat_text_ulb  | 0.7.0 tc project no checking  | should import  |
| https://git.door43.org/photonomad0/es-419_luk  | 0.8.0 tc project no checking  | should import  |
| https://git.door43.org/tc02/es-419_tit_ulb  | 0.8.0 tc project with checking  | should import  |
| https://git.door43.org/tc02/English_tit | 0.8.1 tc project with alignment, no checking  | should import  |
| https://git.door43.org/tc02/am_1co_ulb  | 0.9.0 tc project no checking  | should import  |
| https://git.door43.org/photonomad0/el_tit | 0.9.0 tc project with checking  | should import  |

**Comment by cckozie** [comment]
This is a 0.7 project:
https://git.door43.org/tc0.7/rmr-x-bsa_tit_text_ulb
I think any projects in the repos for https://git.door43.org/wendyc/ should be a good test for projects that have never been in tC.

**Comment by PhotoNomad0** [comment]
@cckozie - I have  updated the list above with some candidates for testing various version.  Please Take a look to see if it is correct.

**Comment by cckozie** [comment]
@PhotoNomad0 I think the list looks good. https://git.door43.org/tc02/es-419_tit_ulb is an interesting one since we did not support any checking in 0.8. I'm guessing that I must have used it for testing on the way to 0.9. That brings up an interesting point; that we should probably start updating the manifest to the coming release as soon as we start development on it. Does that make sense?

**Comment by cckozie** [comment]
This fix is not in 0.10.0-9f11991

**Comment by PhotoNomad0** [comment]
Looking at translationCore 0.10.0-a90d7b8 (Travis build #7934).  It's in there now.

**Comment by PhotoNomad0** [comment]
@cckozie - Looking at translationCore 0.10.0-a90d7b8 (Travis build #7934). It's in there now.
