### ISSUE TITLE
Alignment Data Reset Bug

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#4386]
If the user invalidates a verse by changing it after an alignment has been made
And goes back to the wA tool the alignments reset dialog will show but the alignments will not get reset.

**Comment by cckozie** [comment]
Blocked from testing by #4433

**Comment by cckozie** [comment]
I am assuming that this problem was caused by #4319, but I'm noting it here as well.
Reseting of alignments after verse edits no longer works properly. I loaded a project that was fully aligned in tW and made an edit to verse one. I was correctly informed that the alignments for the verse had been reset, but when I opened the project in Word Alignment, only two words of the verse had been moved back to the word list and the rest was still aligned as before the edit.
