### ISSUE TITLE
Forced Migration for existing projects

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4402]
Include:
- change project validation to make sure we have the project resource.id.  If missing go to new project details page.
- migrate older projects to find the resource id and nickname

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [4] Add validation checking for resource id and nickname
- [ ] [4] Unit tests
- [ ] [2] PR Review

**Comment by PhotoNomad0** [comment]
Think this can be handled by adding resource id and nickname to validation checking in stepper.

**Comment by PhotoNomad0** [comment]
Fixed in PR unfoldingWord-dev/translationCore#4535

**Comment by cckozie** [comment]
For tS projects, the resource id is automatically plugged into both the translation id and nickname fields. Thus the menu bar now displays it in the project field.
![image](https://user-images.githubusercontent.com/8171759/40922005-9ed19842-67d6-11e8-9438-d31390a095eb.png)

@benjore 
1. Should the user be forced through the details page when the tS projects are first opened to allow them to add a nickname and/or change the translation id?
2. Should the user now be able to have multiple projects for the same book/language as long as they have different nicknames? I now no longer get a message telling me that the project already exists, but the second project does not show up on the projects page and it is left in the imports folder on the file system.

**Comment by benjore** [comment]
1. Yes. 
2a. Multiple projects are allowed for a book/language as long as they have a unique identifier.
2b. Not importing needs to be figured out.

**Comment by PhotoNomad0** [comment]
Looks like will have to change how we implemented migrations

**Comment by PhotoNomad0** [comment]
fixed in https://github.com/unfoldingWord-dev/translationCore/pull/4567

**Comment by cckozie** [comment]
0.10.0 (a48d474)
After upgrading from 0.9.1 and selecting existing projects that came from tS, the user is not forced through the project details screen to allow changing of the resource id and nickname.
Local tstudio import [es-419_tit_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115875/es-419_tit_reg.zip)
Imported from Door43 [fr_eph_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115876/fr_eph_reg.zip)
THIS HAS BEEN FIXED IN 0.10.0 (3c6ba1c)

**Comment by PhotoNomad0** [comment]
@cckozie - good test cases - found issue with projects that have missing verses.

**Comment by cckozie** [comment]
Blank project name in alert and console errors when migrating this project. (The project is properly renamed and I am able to open it in wA) FIXED IN 0.10.0 (0ef3ec4) 
[en_ult_php_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2167057/en_ult_php_text.zip)
[es_ult_luk_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2167176/es_ult_luk_text.zip)

![image](https://user-images.githubusercontent.com/8171759/42330647-3613426c-8039-11e8-8844-4888f5f3248c.png)
