### ISSUE TITLE
Integrate scripture pane from tc-ui-toolkit into the word alignment tool

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4520]

**Comment by cckozie** [comment]
I have not yet done extensive testing so suspect there may be more than these 2 issues.
0.10.0 (906add5) 
(Do not see either of these issues in 0.10.0 (45ccd50))
1. ULT shows no no text for verses in php. (FIXED IN 0.10.0 (3c6ba1c))
![image](https://user-images.githubusercontent.com/8171759/41299388-ee30a9ac-6e28-11e8-8445-b5de7ba62b15.png)
[php.zip](https://github.com/unfoldingWord-dev/translationCore/files/2094622/php.zip)
[en_ult_php_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2094630/en_ult_php_text.zip)

2. ERROR displayed on blank screen in luk (FIXED IN 0.10.0 (3c6ba1c))
(I suspect this may be due to Luke 1:1 being a missing verse in this project)
[es_ult_luk_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2094633/es_ult_luk_text.zip)
![image](https://user-images.githubusercontent.com/8171759/41299460-1b81b068-6e29-11e8-835b-966b4ff131c4.png)
![image](https://user-images.githubusercontent.com/8171759/41299550-50c47dbe-6e29-11e8-8f83-ea4c5f8282bf.png)

**Comment by mannycolon** [comment]
@cckozie Number 3 seems to not be related to the scope of this story
@mannycolon You're right. Just before standup I moved it to another issue, but forgot to delete it from this one. Thanks.

**Comment by cckozie** [comment]
None of the elements in the expanded scripture pane are localized
This is still a problem in 0.10.0 (3c6ba1c)

**Comment by cckozie** [comment]
None of the elements in the expanded scripture pane are localized. This is still a problem in 0.10.0 (3c6ba1c)

**Comment by mannycolon** [comment]
@cckozie We have to wait for the crowdin translation to come in automatically after the strings are translated which I think they have not. 

@neutrinog Is there anything we can do to accelerate the process of the strings translation?

**Comment by cckozie** [comment]
@mannycolon The localization was working in wA in a build I tested before the ui toolkit integration into wA.

**Comment by mannycolon** [comment]
@cckozie All the tool localization got reset after the UI toolkit integration because all the strings were moved to the same file. Now we just have to wait for crowdin to do its magic.

**Comment by cckozie** [comment]
@mannycolon I did create the new issue for missing localizations. It does seem strange to me that if we're using the scripture pane from the ui toolkit in both tools, that the localizations are present in the scripture pane in tW but not in wA.

**Comment by da1nerd** [comment]
@cckozie the locale is managed by the tools not the ui toolkit.
In other words, the ui components are empty shells, and the tool injects the locale into them.

Therefore there is some duplication and each tool must be updated independently.
There is some controversy over this implementation, however providing localization in the ui toolkit is not trivial. This was the easiest path forward until we have time to evaluate other options.
