### ISSUE TITLE
(4) SPIKE: Verse Bridges - Data Structure

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4545]
- [ ] (4) Data Structure for wA Tool
  - [ ] how we save things
  - [ ] checking for changes
  - [ ] Impact on USFM.js

**Comment by klappy** [comment]
@neutrinog To be able to handle both verse crossing and verse bridges, here's what I'm thinking for overriding the reference of the current verse we're working on.

@benjore @jag3773 One of the questions arising is whether the Greek versification is what we use to base everything and we use overrides on the mismatching target verses. The other option is to organize verses by the target (that makes verse bridges visible in the menu) and use overriding references on the Greek word objects in the alignment. 

To me, the answer to the question is directly tied to what do we want on the menu. Do we want to see inconsistent bridges in the menu since it is tied to the target language, or do we build the menu off the consistent versification of the Greek? The current system is tied to the Target language and we encounter anomalies of imported partial books that only have one verse and we may or may not display all of those in the menu.

Long-term impacts of storing verses by the target versification can make it more difficult to analyze the data across multiple languages. Keeping them organized by the Greek can make it more consistent and easy to find what we need. I personally lean towards this and would need to come up with a way to render the menu with the target versification including verse bridges if that was desired.

Here's a sample of what the data structure might look like to handle verse crosses and verse bridges at the same time. In the Greek token object, it shows an override of the first verse if they were stored by the target language verse bridge of "1-2". In the Target token object, the verse bridge is in the overriding reference if they were stored by the Greek versification.

```json
      {
        "sourceNgram": [
          {
            "text": "Παῦλος",
            "lemma": "Παῦλος",
            "morph": "Gr,N,,,,,NMS,",
            "occurrence": 1,
            "occurrences": 1,
            "strong": "G39720",
            "reference": {
              "book": "tit",
              "chapter": 1,
              "verse": 2
          }
        ],
        "targetNgram": [
          {
            "text": "Paul",
            "occurrence": 1,
            "occurrences": 1,
            "reference": {
              "book": "tit",
              "chapter": 1,
              "verseBridge": "1-2"
          }
        ]
      }
```
