### ISSUE TITLE
Progress bar/tC logo animation doesn't always work

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#46]
Many times when opening an app for a project the popup for progress shows but stays blank.

**Comment by RoyalSix** [comment]
This issue comes from a combination of react and having a big view being set as the state. 
I was able to set timeouts between the loading process (before and after the setting of the state) that lets the spinner animation get a few frames in but there is still a considerable amount of pause when the state is actually being set. (this method also makes the user experience less smooth)
Ultimately the only way to fix this is to:
1. Use web workers to achieve concurrency
2. Set the state of the new module view in "pieces"
3. Not show an animation and load in the project more efficiently (I've already found a step towards this that reduced loading time by a few hundred ms.)

**Comment by RoyalSix** [comment]
I also found another solution that will optimize TC as a whole, this includes overriding the "shouldUpdateComponent" function in components with memory intensive states (or all the components we wish).

**Comment by RoyalSix** [comment]
Looks like that didn't improve the speed on load...
 because the components that were re rendering when they shouldn't weren't large enough to see a considerable difference in speed.
So now its back to an issue with the way we load the main module view

**Comment by RoyalSix** [comment]
Hi, so I'm not sure if anyone else is reading this, but I'm going to update my log in progress.
I was able to get web workers fully functional, they are quite amazing things. I even created a function in the api to pass a function and run it on a separate thread. The bad news is I quickly realized that there is no way currently to pass the type of information we are trying to pass to a web worker (a React component). The fact is that web workers can only handle computations in no respect to context, although they can send and receive information, there are restrictions to the type of data.

So I've moved on to loading the state in "chunks".
So far this has seemed to be an easier solution, and I am just about done with basic implementation.
There are two plans of attack that I found: 
1. Leave it to the developer
2. Leave it to the API

I've started on method two which I believe may be a bit harder but will provide a better solution in the long run.
