### ISSUE TITLE
Create JSON -> USFM3 Converter NPM Module

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4622]
This will inject the output from word MAP into a USFM 3 file.

> Note: we may need to convert USFM3 to json as well. Though we will add that at a later time.

**Comment by da1nerd** [comment]
Is this the realization for interoperability with https://github.com/translationCoreApps/word-map/issues/5?

**Comment by da1nerd** [comment]
we should build verse objects and then use an existing library to convert it to usfm.

**Comment by da1nerd** [comment]
Here's the related repo https://github.com/translationCoreApps/word-map-usfm

**Comment by RoyalSix** [comment]
@neutrinog Is there a PR for this?

**Comment by da1nerd** [comment]
@RoyalSix no just a new repo https://github.com/translationCoreApps/word-map-usfm.

**Comment by richmahn** [comment]
@neutrinog How should we review this?

**Comment by da1nerd** [comment]
The best person to review this would be @klappy.
This tool chain is still in flux so it would help to know some of the background.

**Comment by klappy** [comment]
@jag3773 and I spent some time with the external teams that will be using this and we came up with some changes. The goal for this story was to have a starting point, with the knowledge that there would be changes. I'll review this one and create a new story for our new changes as it would be out of scope for the original story.

**Comment by klappy** [comment]
Before I tested the conversion I needed to test one of our assumptions, the ability to import the file into tC prior after it is converted. So I stripped out the extra data that we will not have in the json alignment files out of the aligned USFM3 file in order to simulate what we will have.

I can confirm that we do not need to "slipstream" or inject in the extra metadata for the aligned Greek text before it will work in tC. The separation of concerns in tC appears to allow us to import just the UGNT word and its occurrence(s) in the milestone marker to allow us to import it and function in the wordAlignment tool. 

I imported this file to test: 
[57-TIT.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/2228089/57-TIT.usfm.txt)

**Comment by klappy** [comment]
I created a PR for `word-map-usfm` repo with the updated example and readme that documents it.

The readme should help explain what the expected input should be for generating the output USFM3.

Here’s the first pass at documenting the spec for the Alignment JSON data structure: 
https://github.com/translationCoreApps/word-map-usfm/blob/klappy-minimal-example/README.md#input

**Comment by klappy** [comment]
The current converter tests as expected based on discussions prior to the above mentioned modifications. We can pass this issue and create a new one for updating it to work as documented here:
https://github.com/translationCoreApps/word-map-usfm/blob/klappy-minimal-example/README.md#input
