### ISSUE TITLE
Importing a USFM2 project with an unknown \id tag shows all verses missing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4751]
## Story Explanation
Test project - [php_usfm_badId.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/2215675/php_usfm_badId.txt.zip)

If the data in the \id tag is not the standard text for a book in the Bible, the import 'succeeds' but indicates that all verses are missing.
This problem has been introduced since 0.9.1 where it worked correctly. I suspect that it is related to work done on #3559.

### Features / Specifications
When a project that has an unknown \id tag is imported, the app correctly requires the user to select the desired book, but apparently it does not attach that information to the project.

### Definition of Done
Importing such a file should correctly display the reference(s) of verses that are actually missing from the file on the missing verses page.
<!--

**Comment by cckozie** [comment]
0.10.0 (9b04f29)
Tested the same base good and complete usfm2 file but with these 4 different id tags:
1. '\id p' - Imports correctly
2. '\id'    - Alert warning that it is not a valid USFM project
3. '\id 1'  - Imports but shows all verses missing. Imported the same file a second time and it worked correctly. (I don't understand this but have seen it twice)
4. '\id *' - Imports but shows all verses missing.

**Comment by cckozie** [comment]
Moving this out of the current sprint. Not required for 0.10 release.

**Comment by benjore** [comment]
Related to #4738 ?? & #3608

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - on the QA fails: 
- on windows `translationCore 0.10.0 (6492329)`, I also see item 1 failing every other time.  Seems to be issue that settings from previous successful import are not being cleared from reducer before next import.  It looks like this would be a quick fix and should address items 1, 3 and 4.  

- Item 2 is because we are checking for `\id` followed by a space as a quick check that this is a valid USFM file.

**Comment by cckozie** [comment]
0.10.0 (c12e5e6) 
1. works
2. Alert warning that it is not a valid USFM project. Written up in #3608
3. works
4. works
