### ISSUE TITLE
tC locks up when using alignment tool

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4787]
0.10.0 (6492329)
[en_impt_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2242439/en_impt_tit_book.zip)

1. Open the project in wA
2. Go to verse 2:5
![aln1](https://user-images.githubusercontent.com/8171759/43416804-ed350632-93fe-11e8-9fdb-6f545b4f7a22.png)
3. Drag 'word' back to the word list
![aln2](https://user-images.githubusercontent.com/8171759/43416818-f7d1b66c-93fe-11e8-8967-500e14faca85.png)
4. Click refresh. Note that the two Greek words ὁ λόγος are now separated. (Green background is written up in #4784)
![aln3](https://user-images.githubusercontent.com/8171759/43416840-ffa0ec00-93fe-11e8-9bf0-bc44497cd388.png)
5. Drag 'husbands', 'so', 'that', 'not', and 's' back to the word list
Note that the word list is now hidden and the app is locked up
![aln4](https://user-images.githubusercontent.com/8171759/43416858-0b3e3f68-93ff-11e8-9847-9b062f0fba68.png)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/617a3602-7a60-4250-84a0-f688e331fb35)

**Comment by PhotoNomad0** [comment]
### Observations:
- the words God and s are out of order in this project.  (May not be significant)
- can reproduce this error in another project, so there is nothing specific to this example project.
- seems to be related to MAP - when I restart the app I see that map has made suggestions. If I drag s out and put back in, and then drag out again I see the hang again.  But if map hasn't been run, I can drag God and s back an forth all day long.
- error seems to be in life cycle for WA tool.

#### Crash is in:
- in debugging discover that the crash is happening in getTokenizedAlignment() with state undefined.  It is being called by getAlignments(), which has a sparse array (array length 16, but elements 13 and 14 missing) - it looks like elements  of the array have been deleted or filtered?  Added checking for missing array elements, but the UI still locked up.  How are the array elements being deleted?
- now looking at the action ALIGN_RENDERED_TARGET_TOKEN that has the null exception - unfortunately each reducer implements that action.  So need to narrow it down.
  - looks like an exception thrown in verse.js in call to compile() - fails before renders loop.  
  - looks like the cause is that in verse(), update new alignment set newAlignmentIndex to 15 (error in newRenderedAlignments[] which comes from indices generated in compile()?)  Indices[11] contains 8 entries of 10 - very strange.  also  Indices[10] contains 1 entry of 10.  Appears to be a bug in compile() related to suggestions.

- tried verse 2:1 since shorter - seems to be issue with joined source words that have no target

**Comment by PhotoNomad0** [comment]
@neutrinog - added a unit test in https://github.com/translationCoreApps/wordAlignment/pull/63 that I think exposes the error Kos is seeing.  I am still working on trying to fix compile(), but so far do not have a solution that doesn't break other tests.  I Will continue looking at it until I have a fix or you are ready to take this on.

**Comment by da1nerd** [comment]
@cckozie see my comment in #4784 regarding the empty green cards.

**Comment by PhotoNomad0** [comment]
@cckozie - test in release build "translationCore 0.10.0 (1fc250f)"
