### ISSUE TITLE
Map Accepted Suggestions Disappear

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#4800]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
The verse shows that it has suggested alignments, upon clicking the `Accept` button to apply those changes, a second later the changes are reverted and the popup `Changes have been detected in your project which have invalidated some of your alignments. These verses display an icon of a broken chain next to the reference in the side menu.` appears.
The map alignment suggestions are not persisted after reload aswell.

### Steps to Reproduce

1. Download the [project](https://github.com/unfoldingWord-dev/translationCore/files/2251009/hi_abc_tit_book.zip)
2. Open the project above and select the wA tool. You should already be on the verse `Titus 1:2`
3. Click the accept button, wait for popup mentioned above.
4. Click `OK` and Click the refresh button
5. Notice how the suggestions come back even though you just accepted

**Expected behavior:** 
Suggestions to persist, after accepting

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.10.0  |
| build #      | 6ea8367 |
| OS           |   OSX   |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
@RoyalSix Is this a project you have downloaded from DCS? There is a problem in the project as there is a duplicate word/sequence in that verse.
![image](https://user-images.githubusercontent.com/8171759/43552616-c974ee98-95b0-11e8-9bf3-58becbcf738f.png)

**Comment by RoyalSix** [comment]
https://git.door43.org/ult-pre-alignment/en_tit

**Comment by RoyalSix** [comment]
[alignedulb_hi.zip](https://github.com/unfoldingWord-dev/translationCore/files/2255183/alignedulb_hi.zip)
This is the project @cckozie 
Which I got from here https://git.door43.org/tCore-test-data/AlignedUlb_hi

So I'm guessing since this is originally a USFM project that it is a problem with the parser?

**Comment by cckozie** [comment]
[hi-TIT.3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2259545/hi-TIT.3.usfm.zip)
It looks to me like the usfm3 is OK. 'की' does appear in the file twice, each with its correct occurrence. 
I suspect this may be a problem with MAP since both the text and word list appear to be correct.

A similar problem exists in 3:14
Screen shot when verse is navigated to:
![image](https://user-images.githubusercontent.com/8171759/43677912-88b2b072-97cf-11e8-8757-c6613efab0c9.png)

Screen shot after clicking Accept:
![image](https://user-images.githubusercontent.com/8171759/43677904-677b4702-97cf-11e8-90ae-480bff4fe401.png)

**Comment by da1nerd** [comment]
This is a bug in suggestion rendering in wA.
