### ISSUE TITLE
Serious performance issues in larger books

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4842]
0.10.0 (a1f84d7)
Here are timing in mm:ss format for the book of Acts:
On my Mac:
From clicking Select on Project Screen until Project Details screen appears- 0:45
From clicking Continue button on Project Details screen until Tools screen appears- 0:05 (no processing indicator)
From clicking Load button on wA tool until project opens in alignment- 0:50
From project opening in alignment until menu scrolling is enabled- 0:07 (no processing indicator)
From clicking on a different chapter until it is displayed- 0:12 (no processing indicator)
From clicking on a verse until selected verse is displayed- varies to ~0:10 (no processing indicator)
From clicking on Refresh button until snackbar message is displayed- 0:18 (no processing indicator)

On Windows:
From clicking Select on Project Screen until Project Details screen appears- 1:35
From clicking Continue button on Project Details screen until Tools screen appears- 0:07 (no processing indicator)
From clicking Load button on wA tool until project opens in alignment- 4:20
From project opening in alignment until menu scrolling is enabled- 0:07 (no processing indicator)
From clicking on a different chapter until it is displayed- 0:46 (no processing indicator)
From clicking on a verse until selected verse is displayed- varies up to ~ 1:00 (no processing indicator)
From clicking on Refresh button until snackbar message is displayed- 1:50 (no processing indicator)

Besides these timing issues, the menu and word list scrolling also locks for several seconds when attempting to scroll.
After dragging a word to align it, the system doesn't respond to additional drag attempts from or to the word list for at least 10 seconds, often much longer, on my Mac.
Also, sometimes it takes a long time to exit to the Projects or Tools page when one of those icons are clicked on in the menu bar. It seems like something is hogging the processor behind the scenes. Once the tool is exited, the system is slow to respond to user actions for several seconds.

The slow response in changing verses/chapters appears to be related to MAP, as does the problems with scrolling and the icons in the menu bar not being functional when the tool first opens. These problems do not exist in 0.9.1.

**Comment by klappy** [comment]
Does this happen with a fresh unaligned Acts project or only an already aligned Acts project?

**Comment by klappy** [comment]
Here's an overview of my profiling session: While opening the wA tool, I’ve got about 50s of the 90s of the trace are verifyGroupDataMatchesWithFs. I’ve commented dispatches out and stepped up the tree and it still takes nearly as long until I comment out the full verifyGroupDataMatchesWithFs. Then it only takes less than 15s (10s w/o profiling). 

I've narrowed it down to two lines in that function, toggleGroupDataItems and dispatch(validateBookSelections). Loads in the same 10s with just those two lines commented out. This tells me that FS is not the bottleneck as the commented out functions already have data in reducers. Since we can iterate through all chapters and verses and load proper files from fs without much performance hit, we should be able to do what we need in about 20s for loading.

Async calls will not speed up the process as we heavily use dispatching which will then queue up nested actions via their dispatch.

To address this issue there are two natural things to explore:
- Batching updates that need to be made so that you can dispatch once for all updates to the reducer with optimized comparisons. This reduces number of dispatches and subsequent renders of the dom as there is one update and not for each of the types checked in each of the 1000 verses of Acts. 
- Additionally explore loading the tool and then updating the menu after the faster load and watching the menu iterate through the updates.

**Comment by klappy** [comment]
If I recall correctly, in the early days of tC the menu took way too long when loading a tool due to dynamically reading everything off of disk. It was then optimized to somewhat "cache" the information in an index. The challenge of having the data in two places is that it can become out of sync, which is why we then check to make sure everything matches what is on disk. Now we're even slower than before as we are reading from cache, then going and reading it from the definitive source again, undermining the cache to begin with.

Here is where I insert a famous quote, "There are only two hard things in Computer Science: cache invalidation and naming things." -- Phil Karlton

How appropriate :D

**Comment by klappy** [comment]
As for optimizing via batching, here are some articles and references:
https://medium.com/@reinelmp/batching-redux-actions-a68daaa2d492
https://redux.js.org/faq/performance#performance-update-events
https://github.com/tshelburne/redux-batched-actions

**Comment by cckozie** [comment]
1.0.0 (ca376d9) 
Fully aligned Acts on Mac:
Select project to missing verses page: 1:15
wA load to alignment screen: 0:12
Drag/drop ~ 0:01
Change verse/chpater 0:02+
