### ISSUE TITLE
Insert the Original Languages quote for the NT tN

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4943]
### User Story

As a Checker, I want to use tN to check my translation so that I can do a deeper check on my translation.

### Features / Specifications

- [x] Talk to Jesse
- [x] Figure out a way to easily demo it to the stakeholders so that they can verify that the OrigLang quote is correct.

**Comment by da1nerd** [comment]
@jag3773 where are all the files for this?

**Comment by jag3773** [comment]
@neutrinog The TSV tN files are at https://git.door43.org/unfoldingWord/en_tn , make sure to read through the README on that repo.

The aligned data may be found in the repos in https://git.door43.org/ult-pre-alignment .

Basic idea is to read the English in the GL Quote field of the TSV and find the corresponding phrase in Greek by reading the alignment data, then insert that into the TSV, too.

This should, of course, come in as a PR that someone on our content team can review for accuracy before merging.

**Comment by neutrinog** [comment]
@jag3773 we are missing alignment data for some books. E.g. there's no en_gen repo at  https://git.door43.org/ult-pre-alignment

**Comment by da1nerd** [comment]
@jag3773 I have an initial PR available at https://git.door43.org/unfoldingWord/en_tn/pulls/1071.
This only includes perfect matches e.g. the original language and gl language words were found in exactly the same order.

There were a number of complications described below:

1. alignments were incomplete (most fell in this category)
1. `jasper ... sapphire ... agate ... emerald` How do you want me to handle lists of items like this?
1. Word order did not match e.g. in Matt 1:23 we have the Gl quote `which means, "God with us."` but in the original language it appears literally as `which means with us God`

For the entire NT there were 10,590 failed quote lookups (out of 17,712 total).

**Comment by jag3773** [comment]
@neutrinog Let's try the following, in response to your items above:

1. Can you elaborate on this anymore?  Or maybe post some examples of this?  I see that [Titus 1:1 "He revealed his word"](https://git.door43.org/unfoldingWord/en_tn/src/branch/orig_quotes/en_tn_57-TIT.tsv#L8) was not captured, yet I see the alignment data ([here](https://git.door43.org/ult-pre-alignment/en_tit/src/branch/master/en_tit.usfm#L139) to [here](https://git.door43.org/ult-pre-alignment/en_tit/src/branch/master/en_tit.usfm#L152))
1. These should be represented with ... as described in `OrigQuote` on https://git.door43.org/unfoldingWord/en_tn#tn-tsv-column-description .
1. This should be considered a match, the word order will be different in many cases.

Also, I see several places where your output is not preserving the quote marks, particularly in the `OccurrenceNote` field (example Acts 1:4).  These need to be preserved.

**Comment by da1nerd** [comment]
1. For example [Rev 22:21](https://git.door43.org/ult-pre-alignment/en_rev/src/branch/master/.apps/translationCore/alignmentData/rev/22.json#L9524) is not fully aligned (see "everyone" still in wordbank).
2. Ok I see what you mean. I'm parsing the [raw alignment data](https://git.door43.org/ult-pre-alignment/en_tit/src/branch/master/.apps/translationCore/alignmentData/tit/1.json#L727) which is sorted by the source language, but the usfm is sorted by the target language. Reading from the aligned usfm instead of the json should resolve most of these.
3. related to 2.

**Comment by da1nerd** [comment]
@jag3773 made some improvements and have the latest updates in that [same pr](https://git.door43.org/unfoldingWord/en_tn/pulls/1071).

Current totals are:

* 17,712 quote lookups
* 4,144 lookup misses

The inclusion of quotation is a little better, but I haven't taken the time to refine it yet.

**Comment by da1nerd** [comment]
Ok I've improved the punctuation support. It's doing an initial pass with strict punctuation checking and then a second pass as needed without punctuation checking to catch those phrases where the punctuation was inconsistent. In the latter case the surrounding punctuation will be blindly included so that editors can easily adjust as needed.

Same hit/miss ratio as above.

**Comment by da1nerd** [comment]
@jag3773 I've fixed the bugs we discussed and it's ready for review.
The diff is actually readable now!

**Comment by jag3773** [comment]
This is complete now, I've merged https://git.door43.org/unfoldingWord/en_tn/pulls/1071 after Larry's green light.

Next step is the manual review process which the blue team will take.

**Comment by jag3773** [comment]
@neutrinog I'm reopening this to address two more issues that have come up:

- [x] The https://git.door43.org/unfoldingWord/en_tn/src/branch/master/en_tn_56-2TI.tsv does not have any Greek snippets at all. Can we rerun the script on it?
- [x] The Greek snippets have been inserted into the TSV files in the English language order.  This needs corrected so that the Greek snippets are in the Greek word order.  For example, in [PHM 1:1](https://git.door43.org/unfoldingWord/en_tn/src/branch/master/en_tn_58-PHM.tsv#L4) there is a snippet that should have "καὶ Τιμόθεος" based on the [UGNT](https://git.door43.org/unfoldingWord/UGNT/src/branch/master/58-PHM.usfm#L19).  However, it uses the English order instead and has "καὶ ὁ ἀδελφὸς Τιμόθεος".

**Comment by da1nerd** [comment]
@jag3773  2Tim was empty because the chapter and verses in the tsv were zero padded (none of the other tsv files are). Would you like me to normalize the chapter and verse numbers while processing it?

**Comment by da1nerd** [comment]
@jag3773 I can sort the words, but since the punctuation is not included in the alignment json I have no way to accurately place the punctuation. I can keep the punctuation "mostly" in the same location, but it will have to be verified by a human.

**Comment by da1nerd** [comment]
@jag3773 here's a PR with the fixes! https://git.door43.org/unfoldingWord/en_tn/pulls/1075

**Comment by lrsallee** [comment]
See doubled Greek words in https://git.door43.org/unfoldingWord/en_tn/src/branch/master/en_tn_57-TIT.tsv at 

- line 9: ἐπιστεύθην ἐπιστεύθην
- line 25: Θεοῦ' Θεοῦ
- line 62: τοῦ τοῦ' Θεοῦ Θεοῦ βλασφημῆται βλασφημῆται
- line 72: τὴν τὴν τοῦ τοῦ Σωτῆρος Σωτῆρος
- line 84: λαὸν λαὸν
- line 104: τοῦ τοῦ Σωτῆρος Σωτῆρος
- line 107: ἐξέχεεν ἐξέχεεν
- line 110: ζωῆς ζωῆς

**Comment by lrsallee** [comment]
We need to use the Greek punctuation from the UGNT instead of the English punctuation. If there was a way to have a script do that, it would save us a lot of manual checking time.

**Comment by lrsallee** [comment]
Greek phrases that are non-contiguous require an ellipsis at the break. If there was a way to have a script do that, it would save us a lot of time.

**Comment by da1nerd** [comment]
@jag3773 where can I get the latest greek source?

**Comment by jag3773** [comment]
@neutrinog https://git.door43.org/Door43-Catalog/el-x-koine_ugnt .

**Comment by da1nerd** [comment]
I've fixed the duplicate words https://git.door43.org/unfoldingWord/en_tn/pulls/1077.

I should have the punctuation fixed soon as well.

**Comment by da1nerd** [comment]
@jag3773 while looking up punctuation for the original quote there are some instances where some greek words within the phrase are not used. e.g. Act 1:2

GlQuote: `until the day that he was taken up`
Aligned Greek: `ἄχρι ἧς ἡμέρας ἀνελήμφθη`
Greek Text: `ἄχρι ἧς ἡμέρας ἐντειλάμενος τοῖς ἀποστόλοις διὰ Πνεύματος Ἁγίου, οὓς ἐξελέξατο, ἀνελήμφθη`

You can see how this whole chunk `ἐντειλάμενος τοῖς ἀποστόλοις διὰ Πνεύματος Ἁγίου, οὓς ἐξελέξατο,` is not part of the alignment but is still in the middle of the phrase.

How do you want me to represent that? Maybe `ἄχρι ἧς ἡμέρας...ἀνελήμφθη`?

**Comment by jag3773** [comment]
@neutrinog Yes, following https://git.door43.org/unfoldingWord/en_tn#tn-tsv-column-description.

**Comment by da1nerd** [comment]
@jag3773 @lrsallee Here are a bunch of improvements https://git.door43.org/unfoldingWord/en_tn/pulls/1083.

* more accurate punctuation
* more accurate word sorting
* support for discontinuous Greek words
* down to 3,511 misses
