### ISSUE TITLE
Problems importing OT books in developer mode

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4951]
1.0.0 (71a9a28)
In non-developer mode the user is correctly prevented from importing OT projects.

In developer mode the user is allowed to import OT projects
On the Door43 selections screen and on project details screen the Book dropdown list does not include the OT books
The Continue button is enabled even though the Book field is empty
The OT book import does complete and gets a name that does include the book name
When loaded in wA the following is displayed and the app crashes
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4b434bb8-2cd8-450b-a4b3-6a40b24a42df)

 ===
- [ ] Disable the Launch button for wA & tW tools for OT projects.

**Comment by PhotoNomad0** [comment]
This is not needed for release 1.0.0

**Comment by mannycolon** [comment]
@PhotoNomad0 Hey this issue was addressed and merged in to develop branch. However, this issue is supposed to be part of 1.0.2, so we still need to add this changes to `release-v1.0.2` without adding code changes that should not be part of `release-v1.0.2`

**Comment by PhotoNomad0** [comment]
@mannycolon - I spot checked the 1.0.2 branch and these changes are already in there.  So apparently was merged into develop before 1.0.2 branch was created.

**Comment by PhotoNomad0** [comment]
Verified in build https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-5be314d.setup.exe

- in developer mode should be able to do USFM import OT book and project details page should show OT books in the bible drop down. Hit cancel
- now switch off developer mode and do USFM import OT book and project details page should show empty for book name. Also should not show any OT books in the bible drop down. Also make sure that continue is disabled.
- on tools card both WA and TW should have launch button disabled for OT books (since we do not have aligned Hebrew in resources) in both developer and non-developer mode. Full Hebrew support is another issue for future.

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02)
