### ISSUE TITLE
Bundle Git with Installation Package

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4960]
### User Story

As a non-power user, I want Git to automatically be installed with the tC installation package so that I don't get overwhelmed and confused by all the options and decisions that come with a clean install of tC.

### Features / Specifications

- [ ] Recognize if Git has already been installed (and don't reinstall it)
- [ ] Bundle the installation of Git with the tC installation files so that (as much as possible), the user doesn't even notice that Git is being installed. 
- [ ] All the necessary configurations are pre-selected in Git so the user doesn't have to make any decisions on how to install or set up Git

**Comment by da1nerd** [comment]
@benjore which platforms do you want to support this on?

* Linux
* Windows
  * x32
  * x36
* macOS

Or rather, what's the priority of platform support?

**Comment by benjore** [comment]
MacOS, Win64, Win32, Linux

**Comment by da1nerd** [comment]
ok started playing with this.

## For linux
I don't think it's feasible to bundle git with the linux installer since there are so many distributions out there. 
We'd have to compile git for half a dozen distros (to support the popular ones), then bundle those into half a dozen additional installers, then manually install the git binaries (dangerous). 

Alternatively, we could bundle the source for git and compile it during the installation. However, this requires the host computer to have some basic developer packages already installed.

Another route would be to install git via the system package manager (requires internet) since that will download/compile git appropriately for the platform.

Most of these seem like a waste of time and resources since Linux is **not** our most popular platform. For the moment, I've figured out how to generate a nice executable that will install tC on the system complete with a launch icon. I'm not sure what the best solution for installing git is yet.

- [x] generate `.deb` package for installing tC.
- [ ] install git dependency if missing. Punting on this for after windows and macos.

Do we have the user base to justify further git integration with the linux installer?

## For the rest
I don't see any problems with bundling git other than the technical details of doing so.
We'll still only need to generate 2 installers for windows and 1 for macOS and both platforms have pre-built git binaries.

**Comment by klappy** [comment]
At what point do we update the git npm package to one that does not require the installation of git? 
There are new and improved libraries for git that should do what we want and not require us to even install git.

One limitation that might be present is the requirement of https for git communication to DCS which @jag3773 has already offered to enable on the git server.

I feel that by updating the git library to one that does not require git will not only solve this problem but will ease our maintainability short and long term.

**Comment by da1nerd** [comment]
Linux builds are now available as `.deb` packages. You can find an example at http://tc-builds.door43.org/build/develop/

**Comment by jag3773** [comment]
> One limitation that might be present is the requirement of https for git communication to DCS which @jag3773 has already offered to enable on the git server.

Just to clarify in writing, the DCS server *does* support git over HTTPS.

**Comment by da1nerd** [comment]
Just an update. It looks like nodegit will work well. I'm currently in the process of refactoring how different components in our ecosystem are transpiled to es5.
Simplifying transpilation will allow me to more easily configure webpack for tC, which will allow me to greatly reduce the size of builds. Adding support for nodegit forced me to hack together runtime transpiling, which increased our build sizes exponentially.

**Comment by da1nerd** [comment]
This is mostly finished. Waiting until work officially begins on 1.1 before continuing to refactor wA and tW.
Those tools will need to be transpiled at compile time instead of runtime.

**Comment by cckozie** [comment]
@benjore Why does this have the 'Retest' label?

**Comment by da1nerd** [comment]
yeah I haven't merged anything in yet.

**Comment by da1nerd** [comment]
actually this issue is technically outdated since we'll be migrating to nodegit hopefully in 1.1

**Comment by da1nerd** [comment]
Found a new git library https://github.com/isomorphic-git/isomorphic-git. This could be lighter than nodegit and be easier to compile (as in not at all). This would speed things up and potentially decrease the size of the builds. Might be worth investigating.

**Comment by cckozie** [comment]
1.1.0 (8b1ff72)
Tested fine (at least for basic operations) on Windows 64.
I'm going to wait until after a decision on 1.0.3 before deleting git on my Mac. Putting the QA Hold label on until then.

**Comment by cckozie** [comment]
Test on Yosemite with 1.1.0 (2ba28f8) and it looks good on Mac too.
