### ISSUE TITLE
Problems with spaces appearing next to quote marks (usfm3?)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5063]
1.0.0 (e375ee0)
1. The space should appear before rather than after the single quote after the word "Psalms" (Fixed in 1.0.2 (5ebb84f))
2. The space should appear before rather than after the single quote after the word "there':"(Fixed in 1.0.2 (5ebb84f))
(Actually, in 2. the word "And" should be outside of the single quotes and not capitalized. The following "let" should be capitalized. I assume this is a content problem)
![image](https://user-images.githubusercontent.com/8171759/45655425-d0305a00-baa5-11e8-8f5f-02a959e3deaf.png)
3. There are variations in the way we are handling the spacing between the target, Greek, and ult. The target in this screenshot is the usfm3 downloaded from the catalog which should be identical to the ult resource.
![image](https://user-images.githubusercontent.com/8171759/45833104-6d1f0d00-bcc9-11e8-87aa-596602d523c5.png)
This is the appearance in 1.0.2 (5ebb84f)
![image](https://user-images.githubusercontent.com/8171759/47728503-7a1a0f00-dc2c-11e8-9a90-b509dfa392c5.png)

4. Another example with double quotes. No space between the double quote and the start of the next sentence in both the target and ULT.
![image](https://user-images.githubusercontent.com/8171759/45834770-a2c5f500-bccd-11e8-8a68-d7cc3b3b33f7.png)
This is the appearance in 1.0.2 (5ebb84f)
![image](https://user-images.githubusercontent.com/8171759/47748392-afd4ed00-dc58-11e8-8e40-408974fea176.png)

**Comment by PhotoNomad0** [comment]
#### Notes:
1. looks like is in Acts 1:20.  in en_ult USFM `\zaln-e\*,\q'`, there is no space, but a `\q`.  Should be a space after `\q` according to USFM spec.  Need to fix in usfm export. 
2. related to above, but issue with import since word is started on new line so should not be treated as significant.
3. mat 4:6 - in greek added support that right and left double quotes now recognized as punctuation in ScripturePane.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [8] - fix spacing on usfm3 export
- [ ] [8] - fix spacing on usfm3 import
- [ ] [2] - PR review [5063]

**Comment by PhotoNomad0** [comment]
@cckozie -
Tested in: 
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-b2239db.setup.exe

Need to delete resources first before testing.

Check testing steps in https://github.com/unfoldingWord-dev/translationCore/pull/5307 to see what issues fixed and content issues not fixed by this PR.

**Comment by cckozie** [comment]
1.0.2 (5ebb84f)
Tested per #5307. Mat 4:6 and 8:32 are now good.
