### ISSUE TITLE
Update UGNT

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5079]
One of the know issues that should be fixed by this story:
2 Cor 13:14 (13:12 actually contains the content for 12-13, 13:13 contains the content for 14 and 13:14 has nothing).

**Comment by cckozie** [comment]
1.0.0 (4bd6856)
![image](https://user-images.githubusercontent.com/8171759/46313534-b7d43b00-c58d-11e8-8ce5-a9e8c415b012.png)
![image](https://user-images.githubusercontent.com/8171759/46313608-de927180-c58d-11e8-8956-efccfe262d88.png)

**Comment by cckozie** [comment]
No different than in the 1.0 release. No grc available in source content update.
I'm pretty sure the problem in 2CO is in the UGNT, not tC.
1.0.0 (ea3713f) clean install
![image](https://user-images.githubusercontent.com/8171759/46313866-9d4e9180-c58e-11e8-9969-f8a3284d10e2.png)
![image](https://user-images.githubusercontent.com/8171759/46313917-c2db9b00-c58e-11e8-8d3e-41bbf94c8d5f.png)

**Comment by jag3773** [comment]
The content team decided not to make the change that @benjore pointed out in the issue here (see PR at https://git.door43.org/unfoldingWord/UGNT/pulls/100 ).

@cckozie You could check to see that Acts 19:40/41 exist, based on this PR https://git.door43.org/unfoldingWord/UGNT/pulls/97 (19:41 should exist).

**Comment by cckozie** [comment]
1.0.0 (4bd6856)
Acts 19:41 does now exist in the UGNT.
