### ISSUE TITLE
Optimize Tool Loading

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5093]

**Comment by RoyalSix** [comment]
Tasks
- [ ] Optimize `loadAllGroupsData` function
- [ ] Optimize `ToolCard` function

**Comment by RoyalSix** [comment]
Please ask me about these tasks if you need help

**Comment by cckozie** [comment]
Base resources only. Closing and reopening tC before each test.
Load unaligned Acts in wA: 
- 1.0.0 (4bd6856) = 16 seconds
- 1.0.2 (6ab77c0)  = 11 seconds

Load fully aligned Acts in wA: 
- 1.0.0 (4bd6856) = 17 seconds
- 1.0.2 (6ab77c0) = 11 seconds

Load unaligned Acts in tW: 
- 1.0.0 (4bd6856) = 36 seconds
- 1.0.2 (6ab77c0) = 11 seconds

Load fully aligned Acts in tW: 
- 1.0.0 (4bd6856) = 37 seconds
- 1.0.2 (6ab77c0) = 11 seconds

All available resources downloaded. Only target and Greek in scripture pane.
Closing and reopening tC before each test.
Load unaligned Acts in wA:
1.0.0 (4bd6856) =  30 seconds
1.0.2 (6ab77c0) =  17 seconds

Load fully aligned Acts in wA:
1.0.0 (4bd6856) =  31 seconds
1.0.2 (6ab77c0) =  17 seconds

Load unaligned Acts in tW:
1.0.0 (4bd6856) =  82 seconds
1.0.2 (6ab77c0) =  17 seconds

Load fully aligned Acts in tW:
1.0.0 (4bd6856) =  82 seconds
1.0.2 (6ab77c0) =  17 seconds

Overall a 30 - 80% reduction in tool loading time. Very good!
At this point it still takes about 50% longer to load a tool when all of the resources have been downloaded. I don't think the time to load the tool should be dependent on the number of resources available since most will not be used in the tool. Hopefully this will be fixed in #4954 or elsewhere.

**Comment by mannycolon** [comment]
Verified on macOS build 1.0.2 (b64af99)

**Comment by da1nerd** [comment]
FYI. This introduced a regression. I've reverted some changes in https://github.com/unfoldingWord-dev/translationCore/issues/5277

**Comment by cckozie** [comment]
1.0.2 (f005f02) 
The tool loading is much better now, as on my Mac it is consistently ~7 seconds regardless of how many resources are loaded on the machine.
However, the 3+ seconds with a blank screen during the loading of the app is not acceptable. The Loading... message should not be dismissed until the Get started screen is displayed.
