### ISSUE TITLE
Implementation of Tools Optimization

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5160]
This is a follow-up on #5093.

**Comment by RoyalSix** [comment]
The fix I found that I was able to verify was loading the tool views, and their api's (requiring them) before the tool load saves a lot of time.
Since node requires are synchronous (blocking) its a major CPU overhead to do this while doing other things
Actions to dispatch early
`loadSupportingToolApis`
`saveToolViews`
`registerToolApi`(In save tool views)

The node `requires` happening in these actinos need to happen at a time the user will not notice. 
We have all the information we need in order to load them as soon as the app starts. All we theorecitcally need is the path which is static.
`~/tC_apps...` Once the information is loaded (you can use the same logic that we already have.) Just send it to the store (you can use the same logic as well) 

Note:The tools views might be cleared in certain places before it gets loadeed so watch the actions for that. 

Check out the changes I made here https://github.com/unfoldingWord-dev/translationCore/pull/5182/files

**Comment by da1nerd** [comment]
@RoyalSix those changes you mentioned above have negatively impacted the initial start up of tC e.g. the app is noticeably frozen for a few seconds after the welcome screen is displayed.

**Comment by RoyalSix** [comment]
@neutrinog  You are right. But it takes less time to do those operations at the start and it is also not something that can happen multiple times in one session. So I think it is still a performance enhancement.
The long-term solution would be to have the tools precompiled.

I would also be willing to try and find a better place for loading so that the user does not have to think the app is lagging. i.e. before showing any UI

**Comment by da1nerd** [comment]
@RoyalSix we'll be changing when/how tools are loaded in https://github.com/unfoldingWord-dev/translationCore/issues/4672

**Comment by cckozie** [comment]
1.0.2 (f005f02)
The tool loading is much better now, as on my Mac it is consistently ~7 seconds regardless of how many resources are loaded on the machine.
However, the 3+ seconds with a blank screen during the loading of the app is not acceptable. The Loading... message should not be dismissed until the Get started screen is displayed.
Also, the Get started button needs to be operational as soon as it is displayed.

**Comment by RoyalSix** [comment]
In build https://tc-builds.door43.org/build/release-v1.0.2/translationCore-macos-x64-1.0.2-b84794c.dmg

**Comment by cckozie** [comment]
1.0.2 (8c6f266) App loads in 26 seconds. No blank screen displayed.
