### ISSUE TITLE
SPIKE: Find out how to tell if a project is up to date so we can properly allow/disallow the sync button

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#521]

**Comment by ihoegen** [comment]
So unless I'm missing something here @klappy, this isn't exactly needed, because we run `git pull` before we push. However, if there is another reason to this, we could do the following: 

`git log origin/master..HEAD`

This compares local commits to the ones on remote, and can do it the other way around as well..
