### ISSUE TITLE
[0] SPIKE: Figure out a solution for our dependency on dependencies

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5285]
## Specs 

- [ ] Figure out if there is a way that would assist in keeping track of dependencies and making sure they are all updated and consistent. 
- [ ] Consider #3398

**Comment by PhotoNomad0** [comment]
@benjore - trying to remember the context of this.  Was this related to having multiple release branches and making sure we don't pull in updated dependencies that are for a newer release?

Also we have the challenge that often we get multiple versions of a dependency in tCore.  For example tCore may have multiple versions of usfm-js module in tCore - since tCore, tc-ui-toolkit, word-aligner, tc-source-content-updater, etc. may specify different versions in their dependencies.

**Comment by PhotoNomad0** [comment]
One option for searching for duplicate packages:
- install tool using: `sudo npm install -g find-duplicate-dependencies`
- do `rm -rf node_modules` and `npm ci`
- run tool: `find-duplicate-dependencies`
- run `npm dedupe` (can be very slow)
- again run tool: `find-duplicate-dependencies`

Putting this in script
