### ISSUE TITLE
wA Edit/Comment/Bookmark: Add VerseEditor UI and backend

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5407]

**Comment by PhotoNomad0** [comment]
@cckozie - here is a test build to kick the tires.  Reset button is still missing text when you open verse editor from Enhanced Scripture Pane in tN and tW.  But otherwise it should be fully functional in all tools. wA icons should now be actionable and reflect state.

[Linux build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-25adf7a.deb) is ready for download.
[macOS build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-25adf7a.dmg) is ready for download.
[Windows x64 build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-25adf7a.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-25adf7a.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 
1. The text on the edit modal should not be bolded.
2. The Save button on the comment modal should not be active until some text is entered.

@birchamp - For discusion:
A. The comment box is quite a bit larger than in the mockups. Is that desirable?
B. Suggested text for the icon hover overs:
- Edit this verse / This verse has been edited
- Add a comment on this alignment / Comments have been entered for this alignments
- Bookmark this alignment / The bookmark has been set for this alignment

**Comment by PhotoNomad0** [comment]
@cckozie - thanks for feedback.  Will continue to tweak.

**Comment by PhotoNomad0** [comment]
@cckozie - have another test build for you to eval:

[Linux build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-a1cd196.deb) is ready for download.
[macOS build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-a1cd196.dmg) is ready for download.
[Windows x64 build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-a1cd196.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-a1cd196.setup.exe) is ready for download.

**Comment by birchamp** [comment]
@PhotoNomad0 I like the smaller dialog.  I know the dialog is modal, but can it be draggable?   The user is going to want to see what's in the alignment pane as they make the comment.  In the other tools, because the comment is beside the check, so it doesn't cover anything that the user is doing.

**Comment by cckozie** [comment]
@PhotoNomad0 - It's looking good. I agree that it would be good to make the comment dialog draggable even tho it technically is scope creep. (I think the mockups were done prior to the changes to make the edit dialog draggable)

**Comment by PhotoNomad0** [comment]
build process for tools is currently broken, so waiting for that to resolve.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (35226ce)

**Comment by cckozie** [comment]
2.2.0 (a121e92) 
The edit works as expected, but there is a problem with the edit icons showing in the other tools. I added that to the QA Fail on #6675.

**Comment by elsylambert** [comment]
2.2.0 (a121e92).
Edit window looks good and is draggable.
