### ISSUE TITLE
Expand the width of the word card for extra long words

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5440]
![image](https://user-images.githubusercontent.com/8171759/48582175-64be0980-e8e9-11e8-9b0d-f75cc761fdfa.png)

- [ ] For extra long words, the word card should expand to encompass it all. 
  -  [ ] Note: in 1.1.3, wA correctly adds a horizontal scroll bar. 

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/dcc28de3-5343-47ba-934a-6adf6f7ba8b2)

## Notes: 
- [ ] This works improperly in the word bank. When the word is dropped into the drop zone, the card expands to correctly encompass the word. See below.

![image](https://user-images.githubusercontent.com/13352518/60366280-b31fa480-99b0-11e9-872b-1df4c2fdf373.png)

**Comment by PhotoNomad0** [comment]
Question: do we want to put a sanity limit on the size of the unaligned word box and constrain the word to the box with ellipsis?

**Comment by PhotoNomad0** [comment]
Note: discovered that wordbank width is hard coded to 160 pixels - this makes size of word cards within a fixed width.

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie - have Test build for review and feedback with these changes to WA:
- changed wordbank width to be variable from 100 to 400px (previously was fixed at 160px).
- changed word cards so text will show ellipsis instead of overflowing card

[Linux build 2.1.0 (a95d810)](https://tc-builds.door43.org/build/feature-mcleanb-5440/translationCore-linux-x64-2.1.0-a95d810.deb) is ready for download.
[macOS build 2.1.0 (a95d810)](https://tc-builds.door43.org/build/feature-mcleanb-5440/translationCore-macos-x64-2.1.0-a95d810.dmg) is ready for download.
[Windows x64 build 2.1.0 (a95d810)](https://tc-builds.door43.org/build/feature-mcleanb-5440/translationCore-win-x64-2.1.0-a95d810.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (a95d810)](https://tc-builds.door43.org/build/feature-mcleanb-5440/translationCore-win-x32-2.1.0-a95d810.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Verified in develop build translationCore 2.1.0 (ed1c32c)

**Comment by cckozie** [comment]
2.1.0 (ed1c32c) 
@PhotoNomad0 Is 400 pixels the correct limit?
Do we want to supply a hover over to show the entire word? OR
Should we provide the scroll bar if there is overflow?
![image](https://user-images.githubusercontent.com/8171759/71483210-5caee980-27cc-11ea-97b3-d7e9f9451f00.png)

It is acceptable as is for now. Moved these questions to #6627
