### ISSUE TITLE
WordMAP suggestions break WordAlignment tool rendering

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#5519]
### Prerequisites

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

After importing a Hindi project that is already aligned, WordMAP appears to be generating suggestions that break the Rendering of the Greek words in the main alignment workspace of the wA tool.

### Steps to Reproduce

1. Import any Hindi => Greek aligned book, Jude will be attached to this issue.
2. Open Word Alignment Tool.
3. Navigate to Jude 1:7.
4. Note that a single Greek word has a really long suggestion to many Hindi words. 
5. Note that the Greek is truncated and looks like the verse is really short but comparing to the Scripture Pane it appears truncated.
6. Clicking `(x) Reject All` appears to fix the rendering bug.
7. Notice that even the word that was causing issues was human aligned, which suggestions should never take precedence. 

**Screenshots**
Load verse or Refreshed suggestions:
<img width="1440" alt="screen shot 2018-12-03 at 2 22 53 pm" src="https://user-images.githubusercontent.com/118073/49396402-05dcfa80-f707-11e8-9130-00193b04fddd.png">

Looks better after clicking `(x) Reject All`.
<img width="1440" alt="screen shot 2018-12-03 at 2 22 59 pm" src="https://user-images.githubusercontent.com/118073/49396400-05446400-f707-11e8-981c-ed01e83ec7fb.png">

**Expected behavior:** 
WordMAP suggestions shouldn't override human alignments, let alone break the rendering.

**Actual behavior:**
Broken rendering and suggestions overriding human alignment on render.

### Context
Caused much confusion for the Hindi aligners.

**Environment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      |    Release     |
| OS           |     Mac and Windows    |

### Additional Information

Project used to recreate the issue, happens in many places, this is just the smallest project to recreate with:
[HIN_GRK_UGNT4_JUD.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2640962/HIN_GRK_UGNT4_JUD.usfm.zip)

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/61078988-86738000-a3e7-11e9-8c83-7da38aa2c890.png)

This ^^^ is now how it opens in tC 1.2. All three merged sets of Original Languages words are discontiguous. I'm guessing this is why tC choked previously, but does better now. Though tC still has a problem with the duplicating the first dropbox twice. I dove into the alignment data to see if I could find the problem. 

![image](https://user-images.githubusercontent.com/13352518/61080578-018a6580-a3eb-11e9-8162-b6018fec02f6.png)

You can see the data of the attached (above) Hindi project on the left. On the right, I recreated the same alignment structure in the Greek using an English project and random English words. 

You can see that there are a number of differences between the two: 
- Each Hindi only has two Greek words aligned, but only one of those words is shared (I'm guessing this is why tC is able to correctly get the three Greek words, but incorrectly duplicates that dropbox and its content). 
- The Lexical data is all stripped out of the Hindi project. 
- The `\zaln-s` markers are not closed out with a `\*` in the Hindi
- The Hindi project adds a `x-verified=` attribute

[This is probably another issue for another time, but I am also concerned as to why these words were merged. "ai" is nominative feminine plural while "tropon" is accusative masculine singular and "heteros" is genetive feminine singular (so "ai" can't modify either of those words, instead it is modifying "poleis").]

I am not sure how to proceed with this. I think the Hindi content needs to be fixed before we attempt any fixes in tC, though I'd be happy to be shown otherwise. Thoughts?

**Comment by cckozie** [comment]
I loaded up tC 1.0.2 and imported the project
I exported the project without alignments
I imported the exported project
I aligned the words as in the first image above, except for the suggestions
I exported the project including alignments.
I compared the exported USFM with the original (verse 1:7 of the export is attached below)
Observations:
1. The project USFM file has apparently been manipulated outside of tC because of the issues Ben noted above (discontiguous merged Greek words, missing Lexical data and added x-verified markers)
2. Without a very detailed examination of the entire USFM file it cannot be ultimately determined if, other than the problems noted in 1. above, the USFM in the project file is valid, and if workMAP was actually overriding manual alignments.
[JUD 1-7 Aligned in 1.0.2.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/3384003/JUD.1-7.Aligned.in.1.0.2.txt.zip)

**Comment by pjoakes** [comment]
I don't believe anything is wrong with tC. BCS has made tC do things that would be impossible for a user to make it do unless the inputs were manipulated outside of tC, such as discontiguous merging of Greek words, deletion and addition of Greek words and rearranging of the Greek word order.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.

**Comment by cckozie** [comment]
We need to decide what/if we want to do about the "problems" noted above.

**Comment by cckozie** [comment]
Because we have had no other reported incidents of similar behavior, I'm closing this issue.
