### ISSUE TITLE
Renaming project does not work.

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5532]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
Renaming a project will not successfully rename the remote repository.

### Steps to Reproduce

1. Import a project from online
2. Once imported, edit the project details to change it's name
3. When asked if you would like to rename the remote repo click yes
4. An error dialog is displayed and the console produces a `401 Unauthorized` error.

**Screenshots**

![image](https://user-images.githubusercontent.com/166412/49564158-6e7ad180-f8d7-11e8-8069-af477d2be728.png)

**Expected behavior:** The remote repo should be renamed

**Actual behavior:** The app is rejected with a 401 error.

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      |  any  |
| OS           |  linux   |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing the error while renaming Repo,

**Comment by cckozie** [comment]
This is partially fixed in 2.0.0 (15e3755). The project does now get renamed as requested, but if the renamed project (repo) is imported again, the project details screen shows that the translation id is the old one and does not reflect the project's name.
Original project imported from Door43 was en_ulb_tit_book
After import the translation id was changed to ulbx, so the project was renamed to en_ulbx_tit_book
When importing en_ulbx_tit_book from Door43, the translation id shows as ulb

**Comment by cckozie** [comment]
Issue noted in last comment is now on #6508
