### ISSUE TITLE
No translationCore default tools found error

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5543]
1.1.0 (c6414a7)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/03f1da8d-3979-424c-a673-7a99879a954a)
https://git.door43.org/qa99/en_test_gen_book

Actually receiving this error on any book.

**Comment by da1nerd** [comment]
I discovered the root cause of the issue is that `fs.access` does not work on directories within an asar file. See this related issue https://github.com/electron/electron/issues/6555. Strangely this was supposed to have been fixed several years ago, but perhaps just not for directories?

At any rate I've updated the tool loading code to not use `fs.access` either directly or indirectly.
