### ISSUE TITLE
Add progress and invalid check count APIs to tW tool

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5599]

**Comment by cckozie** [comment]
1.1.1 (f6a4c6b) 
Since this is the last child issue of #3562, I am writing up problems here that may not relate specifically to this issue. 

ISSUE A:
~~When edits are made in wA that affect tW selections, the alert indicating that the selection being reset is not being displayed. (The broken link indicator is updated correctly on the tW card)~~ Moved to #5687

ISSUE B:
When the user then loads the project in tW, the checkmark and previously made selection are still being displayed on the menu tile. Both the broken link and checkmark are displayed in the popover.
<img width="202" alt="check-link" src="https://user-images.githubusercontent.com/8171759/52425519-c85b6b80-2ac1-11e9-9d3a-53a4ef4426bf.png">
To replicate A and B:
1. Load a project in tW
2. Make a selection for a check where there are multiple checks in the group.
3. Save the selection
4. Click the Save & Continue button
5. Open the project in wA
6. Edit the verse in which the selection was made in such a way that the selection will be reset.
Note that the alert for reset selections is not displayed.
7. Load the project in tW
Note that the checkmark and previous selection are displayed on the menu tile until you navigate to that check.

ISSUE C:
~~When a verse is edited in wA, the edit icon is not displayed on the verse in tW.~~ Moved to #5832

ISSUE D: (This is dealt with in #5686)
~~1. When a verse is edited external to tC that will reset selections, when it is reimported the alert notifying of reset selections is not displayed during the reimport.
2. When a verse is edited external to tC that will reset selections, when it is reimported the broken link count on the tW card is not updated.
3. When a verse is edited in external to tC and then reimported, the edit icon is not displayed on the verse in tW.~~

**Comment by da1nerd** [comment]
The above issues are related to https://github.com/unfoldingWord-dev/translationCore/issues/5686.
There were a few minor bugs that weren't caught in the PR, but looks like they should be quick fixes.

**Comment by cckozie** [comment]
@neutrinog #5686 only deals with edits made external to tC. (ISSUE D above)

**Comment by da1nerd** [comment]
@cckozie issue A was supposed to be in 1.2. I realize it looks different from the user's perspective but it's actually the same code in https://github.com/unfoldingWord-dev/translationCore/issues/5686.
> NOTE: I found a bug in the implementation of https://github.com/unfoldingWord-dev/translationCore/issues/5686 that will need to be addressed for this to work consistently.

**Comment by PhotoNomad0** [comment]
@cckozie - do you expect to see an edit mark in tw on every check instance for a verse edited in WA?

**Comment by cckozie** [comment]
@PhotoNomad0 - Yes, I would expect to see that. Although I do see that currently the edit mark is only displayed in either tool when the edit is made in that same tool. 
@benjore - What say you? Should the edit icon be displayed on the verse in both tools regardless of where the edit was performed?

**Comment by benjore** [comment]
@cckozie Yes. That is correct. Eventually, the pencil will be an indicator that there is an edit history that they can go and view. Since we don't have that feature yet, it is merely a notification. But an edit in 1:3, for instance, should result in the pencil icon showing up for all checks occurring in 1:3 and in the wA for 1:3.

**Comment by da1nerd** [comment]
I thought it was going to be an easy hack to get the verse edits to be viewable globally, but now I'm not so certain.

**Comment by da1nerd** [comment]
@cckozie can I suggest opening a new issue as a feature addition for item "C" above?
This may take some planning and potentially some internal architecture changes.

**Comment by cckozie** [comment]
@neutrinog That's a @benjore call.

**Comment by PhotoNomad0** [comment]
@cckozie - @benjore has split out item C into a new issue.  Are items A & B still broken?

**Comment by cckozie** [comment]
@neutrinog - Should this be In QA?

**Comment by da1nerd** [comment]
Issue A will be  handled in #5687. @RoyalSix has been working on this. Though I don't think tC has been updated to properly trigger his new `validateVerse` API yet when a verse is edited. @RoyalSix if you're verse validation is ready I can update tC's verse edit to trigger the appropriate api methods.

Issue B has been fixed.

**Comment by da1nerd** [comment]
Fyi the update in tC I referenced above begins on this line https://github.com/unfoldingWord-dev/translationCore/blob/develop/src/js/actions/VerseEditActions.js#L75

Basically we'll need to simplify those lines a lot and just blindly loop through all the tool APIs triggering `validateVerse`.

In which case the comment in the code about this being a "hack" would not longer apply since we wouldn't need to hard code the tool names like it is currently.

**Comment by cckozie** [comment]
1.1.3 (982b0d9) 
Issue B has been fixed. Now only the broken link icon is displayed on the menu tile.

**Comment by cckozie** [comment]
@benjore - Per Joel, Issue A above is being worked on as part of #5687 which was set up to handle Issue C above. Are you willing to wait for that, or should I fail this one again?

**Comment by cckozie** [comment]
All fixed or moved.
