### ISSUE TITLE
Connect new GroupedMenu to tW

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5710]
Original issue at https://github.com/unfoldingWord-dev/translationCore/issues/4443.

Route all of the tW specific logic into the new menu.

**Comment by cckozie** [comment]
1.1.0 (26fdc79) 
@benjore - Please weigh in on any of these problems if you are OK with leaving them as is.

There are a number of issues with the new menu (both in tW and wA), most of them are related to element sizing and spacing. This makes the new menu less user friendly since it will limit the user's view of menu items and also cause additional scrolling. (In the example shown with the filter open, the old menu displays twice as many checks as are displayed in the new menu without scrolling.)

ISSUE 1:
A. The spacing associated with the filtering options is much larger in the new menu. [Fixed in 1.1.3 (4f85a74)]
~B. The filter icons and check boxes are significantly larger in the new menu.~ Note: this is true only if we can consume about the same amount of real estate as the previous version.
C. The circle indicating how many filters have been selected should show only when the filter is closed. [Fixed in 1.1.3 (4f85a74)]
D. The filter icon is not reverse imaged against a white circle background when the filter is open in the new menu. [Fixed in 1.1.3 (4f85a74)]
E. The badges displayed when filters are selected and the filter menu is closed are significantly larger and are ordered differently in the new menu. [In 1.1.3 (4f85a74) the vertical size of the badges is much better, but still larger than in the old menu. I think that is OK. However, the ordering of the badges is still incorrect. And the two columns of badges should be left aligned. See failing comment below.]
F. The circle indicating how many filters are selected is smaller and harder to read in the new menu. [Fixed in 1.1.3 (4f85a74)]
Old menu:
<img width="253" alt="open1 1 0" src="https://user-images.githubusercontent.com/8171759/52417625-e9b45b80-2ab1-11e9-9fc0-e5aa7ae52851.png">

<img width="251" alt="badges1 1 0" src="https://user-images.githubusercontent.com/8171759/52417230-07cd8c00-2ab1-11e9-8df7-a23c9df08230.png">

New menu:
<img width="253" alt="open1 1 1" src="https://user-images.githubusercontent.com/8171759/52417669-03ee3980-2ab2-11e9-9df2-9c6c81b7a26e.png">

<img width="246" alt="badges1 1 1" src="https://user-images.githubusercontent.com/8171759/52417264-1c118900-2ab1-11e9-927b-e5b08217c2ae.png">


ISSUE 2:
A. The tile for each tW group is much larger vertically in the new menu. This is also true of the Chapter card in the wA menu. [Fixed in 1.1.3 (4f85a74)]
~B. The completion % circle is larger and thicker in the new menu.~ [Fixed in 1.1.3 (4f85a74)]
C. The spacing between the completion % circle and the group text is much greater in the new menu. [Fixed in 1.1.3 (4f85a74)]
D. The scroll bar goes all the way to the top of the 'Menu' tile in the new menu. [NOT FIXED in 1.1.3 (4f85a74)]
~E. The icons on the menu tiles are different size and shape (and sometimes color) on the new menu. The thin new checkmark is harder to detect when the tile is blue.~ Note: Keep the colors as they are in the new menu (all white except the checkmark), make the green checkmark more "bold". [Fixed in 1.1.3 (4f85a74)]
F. The active (blue) tile card expands vertically slightly when an icon is added to it. [Fixed in 1.1.3 (4f85a74)]
Old tW menu:
<img width="252" alt="tw1 1 0" src="https://user-images.githubusercontent.com/8171759/52373243-cc36b180-2a1f-11e9-97d5-9ffc5ddf4a73.png">


New tW menu:
<img width="250" alt="tw1 1 1" src="https://user-images.githubusercontent.com/8171759/52374120-1751c400-2a22-11e9-8db4-fc55108419e2.png">

ISSUE 3 [Fixed in 1.1.3 (4f85a74)]
The order of precedence for the icons on the menu tile has changed. It should be
1. Invalidated
2. Bookmark
3. Selected/Alignment Complete
4. Verse Edit
5. Comments

ISSUE 4:
1. The hover popup over the text on the menu tile should only display the selected text, not the verse reference and selected text. [Fixed in 1.1.3 (4f85a74)]
2. The hover popup is displayed in some cases even when the selection text is not truncated. [Fixed in 1.1.3 (4f85a74)]

ISSUE 5:
The user used to be able to move through the menu items by using the cursor up and down keys. That feature no longer works. [Fixed in 1.1.3 (4f85a74)]

ISSUE 6: [Fixed in 1.1.3 (e1fae24)]
When a verse is edited in the expanded scripture pane in tW that resets a selection, the alert indicating that is displayed, but the checkmark is not cleared, and the broken link and edit icons are not displayed on it unless it was the one active in the menu.
If the edit did not reset the selection, the edit icon is not added.

ISSUE 7:
When an edit is done in tW, the edit icon does not appear on the verse in wA. [The fix for this is now in #5832]

**Comment by da1nerd** [comment]
issues 6 is likely related to https://github.com/unfoldingWord-dev/translationCore/issues/5599#issuecomment-461495653

**Comment by cckozie** [comment]
1.1.3 (4f85a74)
From ISSUE 1: E above;
The badges need to be ordered the same as they were in the old menu as shown in the screenshot above.
The badges need to be left aligned in two columns as they were in the old menu. 

ISSUE 2: D above has not been fixed.

ISSUE 6 above: None of this has been fixed

**Comment by PhotoNomad0** [comment]
@cckozie - Checking https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-982b0d9.dmg

**on Issue 1: E:**

I am seeing badge alignment as below.  Is this good for column alignment:

![screen shot 2019-02-28 at 2 54 54 pm](https://user-images.githubusercontent.com/14238574/53594675-609cbb80-3b69-11e9-8d45-f818d8a856a9.png)

But when I change the toggles, it looks like new badge is added to bottom changing the order.  So I understand that you always want them sorted in the same order?

Any other changes to the badges that need to be made?

**Comment by cckozie** [comment]
@PhotoNomad0 
Concerning badge alignment; no it is not good. Only the left column is left aligned, both should be as they were in the previous version of the menu. (See images above)
Concerning their ordering; they should always be ordered left to right, top to bottom, in the same order as the checkboxes (Invalidated, Bookmarks, Selected, Verse Edit, Comments) regardless of which ones are checked.

**Comment by PhotoNomad0** [comment]
@cckozie - Oh, you want the badges aligned with badge above.

**Comment by PhotoNomad0** [comment]
Note: have badge ordering fixed.  Looking at fixing column ordering.

**Comment by PhotoNomad0** [comment]
@cckozie - how does this look?

![screen shot 2019-03-04 at 8 15 28 am](https://user-images.githubusercontent.com/14238574/53735719-b61ce500-3e55-11e9-912b-0043231309e0.png)

**Comment by PhotoNomad0** [comment]
@cckozie - how does this look for alignment of badges?

![screen shot 2019-03-04 at 8 16 37 am](https://user-images.githubusercontent.com/14238574/53735776-e19fcf80-3e55-11e9-8344-8529ba4d9e40.png)

@PhotoNomad0 Alignment looks good.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie Status
- ISSUE 1: E - have fixes for this

- ISSUE 2: D - limitation of material UI menu, do we want to refactor the group menu again to make the filter a separate component.  If we want to make this change, maybe move this to release 1.2

- ISSUE 6 - seems to be working now, fixed in other issue?  Maybe Jay's fix for verse edits fixed this.

**Comment by cckozie** [comment]
I think 2:D is fine as is. I think the proper fix would be to have the top Menu tile a separate component rather than part of the actual menu list. The problem existed in the previous version of the menu as well.

**Comment by cckozie** [comment]
@benjore would like to see this fixed for 1.1.3, but has time-boxed it to 1 day. If it will take longer than that, we'll move it to 1.2.
I found another issue:
ISSUE 8: [Fixed in 1.1.3 (e1fae24)]
When the checks in the active menu group are not all in view, as the user makes selections and clicks the Save the Save & Continue buttons, the active check eventually goes below the viewable area and the menu is not scrolled to keep it in view.

**Comment by PhotoNomad0** [comment]
> @benjore would like to see this fixed for 1.1.3, but has time-boxed it to 1 day. If it will take longer than that, we'll move it to 1.2.
> I found another issue:

@benjore @cckozie - is the one day time boxing for making the filter a separate component?  Or is it for fixing the auto-scroll below?

> ISSUE 8:
> When the checks in the active menu group are not all in view, as the user makes selections and clicks the Save the Save & Continue buttons, the active check eventually goes below the viewable area and the menu is not scrolled to keep it in view.

**Comment by cckozie** [comment]
@PhotoNomad0 - It is for the auto-scroll issue. Making the filter a separate component will be for something way down the line.

**Comment by PhotoNomad0** [comment]
Tested in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-win-x64-1.1.3-836a5d9.setup.exe

**Comment by cckozie** [comment]
Issues 1:E and 8 are fixed in 1.1.3 (836a5d9)

**Comment by cckozie** [comment]
Issue #6 was not fixed in #5599 as Joel suggested. This seems to be somewhat dependent on the sequence of events. Here is one way to reproduce with this file:
[46-ROM.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2933488/46-ROM.usfm.zip)
1. Import the file and load in tW
2. Open the 'disobey' group
3. Click on verse 11:30
4. Select 'disobediance'
5. Click Save
6. Click Save & Continue
7. Select 'have been disobedient' 
8. Click Save
9. Click Save & Continue
10. Select 'disobedience'
11. Click Save
12. Open the expanded scripture pane
13. Open verse 11:30 for editing
14. Change the word 'disobedience' to 'unobedience'
15. Click Next
16. Choose a reason code
17. Click Save
18. Click Close
Notice that the menu seems to indicate that the edit was made to verse 11:32 and that verse 11:30 still shows the checkmark and not the edit or broken link icons. Also note that the tW tool card on the tools page does not indicate the reset selection. The problem is not corrected by reloading the project in tW.
![image](https://user-images.githubusercontent.com/8171759/53843793-397b2b00-3f69-11e9-8603-15b0140deaef.png)

![image](https://user-images.githubusercontent.com/8171759/53843830-557ecc80-3f69-11e9-98d8-08f89c39fc22.png)

**Comment by PhotoNomad0** [comment]
@cckozie - was able to reproduce, looks like it is doing the reset and edit on the active verse, not the edited verse and not showing the invalidation on the edited verse until I select it.

**Comment by PhotoNomad0** [comment]
@cckozie - I realized I was running 1.1.2 when I reproduced the problem, so this looks like it's been around a while.

**Comment by PhotoNomad0** [comment]
Also is an issue where there are multiple checks with the same group id in a verse.

**Comment by PhotoNomad0** [comment]
@cckozie - Fix for issue 6.

checked in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-e1fae24.dmg

**Comment by cckozie** [comment]
1.1.3 (e1fae24)
The specific test referenced for Issue 6 has been fixed. There are still some issues remaining having to do with alerting of reset alignments and selections, but I'm adding those to #3562.
