### ISSUE TITLE
Update the Smurf Bar to display data from new location (alignment data)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5760]

**Comment by RoyalSix** [comment]
#5831

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-45fa8a2.dmg

**Comment by cckozie** [comment]
1.2.0 (b7e490a) 
@RoyalSix - Please check to see if this is a problem with the content or the code.

In the Personification group of Titus, verse 2:12, the smurf bar text is really related to verse 2:11, and it also has some strange text
<img alt="212" width="571" src="https://user-images.githubusercontent.com/8171759/53664315-c8b4d580-3c2d-11e9-8405-3e60a5f0c559.png">

**Comment by benjore** [comment]
The link in the screenshot above is bad. If it is a good link to a Scripture reference, there should be a hover-over that displays the reference in view.

**Comment by benjore** [comment]
https://resource-container.readthedocs.io/en/latest/linking.html

**Comment by PhotoNomad0** [comment]
@benjore - Got confirmation from @jag3773 that the link is bad (i.e. a content problem).  How do you want to proceed?

**Comment by benjore** [comment]
Ignore the bad data. If it is a good link, can you add the Scripture as a pop-over in the selected GL language, with English as a fallback if the GL doesn't exist.

**Comment by mannycolon** [comment]
@cckozie 

#### Detailed Test instructions:
-  Download [this file](https://github.com/translationCoreApps/translationNotes/files/3022120/tit.zip)
- Unzip the file and put it in the following location `Users⁩ ▸ {you} ▸ ⁨translationCore⁩ ▸ ⁨resources⁩ ▸ ⁨en⁩ ▸ ⁨translationHelps⁩ ▸ ⁨translationNotes⁩ ▸ ⁨v14⁩ ▸ ⁨figures⁩ ▸ ⁨groups⁩` (This file hasn't been fixed in the door43 catalog)

- Open the following [Titus project ](https://github.com/unfoldingWord-dev/translationCore/files/3040808/en_ulb_tit_book.zip)
- Select all tN categories and hit launch
- Open `Personification check` in `Titus 2:12`
- if you hover over the Titus 2:11 reference a tooltip should pop up with the scripture reference 

**This test instructions will only work with the project included in here or new projects until we get #5951**

**Comment by cckozie** [comment]
Correct data (from occurrence note) is being displayed in the smurf bar.
The noted problem in 2:12 now works as described by Joel above in 1.2.0 (b485978)
