### ISSUE TITLE
Load GroupData/GroupIndex base on GL selected for tN

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5797]
### User Story

As a tC user, I want tools to be built such that the checks and group menu are built directly off the GL TSVs so that all my tW & tN checks show up in tC.

### Features / Specifications

- [ ] Filesystem structure of groupData & groupIndex will have to change and be moved out of the Greek resource folder and put into the respective GL folders. 
- [ ] Loading of the groupData and groupIndex will have to change to accommodate change
- [ ] Make necessary changes in the source content updater module to follow the new filesystem structure 

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
This is the filesystem structure I'm proposing:

<img width="892" alt="screen shot 2019-02-11 at 4 13 37 pm" src="https://user-images.githubusercontent.com/17072300/52594273-156c7400-2e19-11e9-8d2f-c6602dbee360.png">

**Comment by richmahn** [comment]
tW is different, where it is the same for every language. Yet tN, since different parts of speech/grammar/etc. are different for every language. I still don't think I based tW off the English, but off the ids which had their Resource Container URIs  in the UGNT, and from that could link to the English title/article, Hindi title/article, etc.

**Comment by RoyalSix** [comment]
#5831

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/feature-jay-5753/translationCore-macos-x64-1.2.0-4f42f46.dmg

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-45fa8a2.dmg

**Comment by cckozie** [comment]
1.2.0 (b7e490a) 
Seems to be working

**Comment by cckozie** [comment]
I'm guessing that this issue is where this problem should be noted.
3. Attempting to load Titus with only 'lexical' checked, I get the generic ERROR screen. I suspect that there may not be any tN lexical checks in Titus. If that is the case, lexical should not show as an option on the tool card.
<img width="1440" alt="error" src="https://user-images.githubusercontent.com/8171759/53666472-cce3f180-3c33-11e9-97b4-e32a5b714cf5.png">
