### ISSUE TITLE
Zip translationHelps & lexicon files in tC static resources 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5846]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] This will reduce the build size 
- [ ] Will significantly Improve startup time on fresh install (user without translationCore folder in users path)
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@mannycolon 
It appears to me that all of the lexicon files are not included in the latest build. (Or is it possible that some have been deleted between 3/7 and today?)

Latest build - 1.2.0 (3fa53ee)
Clean startup time - 1:11
.dmg size = 392.3MB
.app size - 391.8MB
resources folder info: 321,062,911 bytes (407.1 MB on disk) for **29,873 items**

Previous build - 1.2.0 (368d706)
Clean startup - 1:30
.dmg size - 429.6MB
.app size - 429MB
resources folder info: 322,021,439 bytes (420.7 MB on disk) for **33,131 items**

**Comment by mannycolon** [comment]
@cckozie I'll move this issue back to in progress to double check if it is the case that lexicon files are missing

**Comment by mannycolon** [comment]
@cckozie You were right there were files missing in the UHL. I have a PR with a fixed.

**Comment by mannycolon** [comment]
Tested on ad0e098 (v1.2.0)

**Comment by cckozie** [comment]
1.2.0 (ad0e098)
resources/hi - Current build has these additional files:
/Users/cckozie/translationCore/resources/hi/bibles/udb/v5.1/books.zip
/Users/cckozie/translationCore/resources/hi/bibles/udb/v5.1/index.json
/Users/cckozie/translationCore/resources/hi/bibles/udb/v5.1/manifest.json

resources/hbo - all files match

resources/grc - all files match

resources/en - all files match

Since the current build has all of the files from the previous, plus a few more, I think it's safe to say that it works.
