### ISSUE TITLE
Make expanded scripture pane draggable

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5868]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
See #5737

**Comment by mannycolon** [comment]
See: https://material-ui.com/demos/dialogs/#draggable-dialog

**Comment by cckozie** [comment]
@benjore - In the current implementation, the expanded scripture pane is draggable and works mostly as expected until the edit modal is opened. When the edit modal is opened by clicking on a pencil icon, the expanded scripture pane returns to its original position before the edit modal is opened. Now only the edit modal is draggable. Is that acceptable behavior? (I would expect the expanded scripture pane to remain in its last position when the edit modal is opened)

**Comment by cckozie** [comment]
ISSUE A:
The expanded scripture panel is draggable, but the user should not be able to drag it out of the main tC window. Currently I am able to drag it off the top of the screen where it cannot be grabbed, and also completely out the side of the window where it cannot be seen and there is no obvious way to get it back. Same problem exists in #5737.

ISSUE B:
When the expanded scripture pane is dragged to a new position and then the edit modal is opened, that expanded scripture pane should remain in its last position instead of moving back to its original position.

**Comment by benjore** [comment]
Expected behavior would be that the expanded scripture pane remain in its last position.

**Comment by elsylambert** [comment]
Verified in 1.2.0 (3ae9fb5). Working fine.
Expected Behaviour: - Expanded Scripture pane is draggable and stays within the tC window.
- when verse edits are made, the window stays at the last position.
- when clicked away from the edit window, it gives a warning that the changes are not saved.

**Comment by cckozie** [comment]
1.2.0 (3ae9fb5)
ISSUE A still has problems. I am able to drag the expanded scripture pane completely off the bottom of the screen where it cannot be seen or dragged back once the mouse button has been released.
Issue B has been fixed.

**Comment by mannycolon** [comment]
@cckozie per conversation with @benjore we dicided that as long as the user could click away to close the dialog it was ok that the user could drag the dialog out of the window. Reasoning: users may want to be able to see what's behind the dialog and if we make it so that they cant drag it outside of the window they will not be able to do that.
