### ISSUE TITLE
Errors uploading to Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5890]
1.1.2 (134656f)
I have not seen this before, but believe that some user's have. 

Downloaded the usfm3 Acts file from https://git.door43.org/Door43-Catalog/en_ult/raw/branch/master/45-ACT.usfm and imported it. Loaded it in wA but did not make any changes to alignments, then uploaded. I received the same error twice. The third time it worked.

[en_ult_act_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2944376/en_ult_act_book.zip)

![image](https://user-images.githubusercontent.com/8171759/54007403-21510a80-4127-11e9-97e4-890edf573586.png)

**Comment by PhotoNomad0** [comment]
@cckozie @benjore  - this error is actually a server error returned by Door43.  Unfortunately when we changed to Isomorphic-git, it now throws exceptions instead of returning an error code.  That's why we are now suddenly getting these strange error messages on upload failure.  So I made fix to handle this and show the normal upload error message.

I've also changed so we will show the project loading dialog while alignment data is being checked (creating the USFM3 file) and local file changes committed to git which is a major amount of the time consumed.  This way the user sees something is happening before upload begins.

**Comment by PhotoNomad0** [comment]
@cckozie - this is a great "worst case" upload test.  It imports a large book with alignments.  When you open WA it initializes the data structures on disk.  But since you don't change verses, none of the file changes are committed to git yet.  Then when you do upload:
- the usfm3 file is created (which doesn't actually take long)
- the changed files are committed to git (which takes most of the time in this case since there are a lot - several for each verse - and there is now a huge new usfm3 file to compress and add to commit)
- then the git repo is pushed up (which typically is the fastest part of the process)

**Comment by PhotoNomad0** [comment]
@cckozie - still can't reproduce fail, but should go faster with fix for https://github.com/unfoldingword-dev/translationcore/issues/5798

**Comment by PhotoNomad0** [comment]
@cckozie - looks like this may have been due to git running so slow.  Tested in Windows with fix for https://github.com/unfoldingword-dev/translationcore/issues/5798 and don't see a problem.  should work in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-win-x64-1.1.3-64d8fb7.setup.exe

**Comment by cckozie** [comment]
I'm moving this to the QA Watch lane.

**Comment by cckozie** [comment]
Haven't seen this for some time now. Closing.
