### ISSUE TITLE
[5] SPIKE: #5662 Whole language alignment memory

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5909]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by RoyalSix** [comment]
- [ ] Add alignment memory based on book/chapter/verse in intialization (`Container.js - generateMAP`)
- [ ] Add book to word alignment reducer state 
  - This should not be too difficult because the state is in slices, just need to add one more top layer for the book
- [ ] Update all references in tC using alignment data json
  - We will either have to change the json output structure or create multiple jsons for each book
  - SET_ALIGNMENT_SUGGESTIONS will need book reference as well
  - All references will need to first access the book property
- [ ] Performance issues??
  - There will be a performance hit on initialization, and predictions, and alignment additions. They msy or may not be negligible
  - Web workers

**Comment by da1nerd** [comment]
@RoyalSix  I'm not sure why there are two issues open for this but here's something that I wrote up.
https://github.com/unfoldingWord-dev/translationCore/issues/5662#issuecomment-477332542

I don't think we'll need to many too many changes (if any) to redux. And just a few changes to the tool apis.
