### ISSUE TITLE
Need indicator of processing during imports after the project details screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5937]
1.1.3 (126c679)
Import this project: https://git.door43.org/lrsallee/en_ult_act_book
On the Project Details page change the translation ID to something other than ULT and click Continue
After clicking Continue on the Project Details page it takes about 10 seconds until the screen changes and the Project page is displayed. During that time there is no indication of processing. 
Even though the Project page is now displayed, the import is continuing for another 10 seconds after which the Project has been named alert is displayed. Again there is no indication of processing during that time.

**Comment by mannycolon** [comment]
Added indicator of processing & Improved performance on saving changes from `2mins 10sec` to `15sec` on my computer

**Comment by mannycolon** [comment]
@cckozie @elsylambert 

This issue was addressed/fixed long time ago and I thought it was actually referring to the delay when only opening the project's project details screen. 

Therefore I used the following steps:

-  Import this project: https://git.door43.org/lrsallee/en_ult_act_book using the online import dialog.
- After being taken to the tools page go to the home page and click the three dots and click edit project details
- Change the translation ID to something different and click `Save Changes`
- A dialog saying `Saving Changes` should be displayed

### Changes:

- Added `Saving Changes` dialog to indicate something is happening when after clicking `Save Changes`
- Improved performance on saving changes from 2mins 10sec to 15sec on my computer

**Comment by mannycolon** [comment]
@cckozie @elsylambert  So I would suggest testing both functionalities

**Comment by mannycolon** [comment]
Verified on 9972d1a

**Comment by cckozie** [comment]
2.0.0 (3727b58)
The problem described in the first comment in the issue has been fixed. I was hoping this would also fix the problem of selecting a project that has missing verses, but unfortunately it didn't. I wrote that up as issue #6420.
The problem Manny described has also been fixed.

**Comment by elsylambert** [comment]
2.0.0 (aa663e3) .
While importing the Project from Door43, it asked for rename of Translation ID (I had the same project on my system). After I renamed, it saved the changes and displayed the below shown Alert message:
![image](https://user-images.githubusercontent.com/51806180/64264427-46201200-ceff-11e9-876a-cae285d1d41b.png)

Similarly, editing the project from the Projects page(three dots), it gives the same alert message with the Characters
Note: Not seeing the performance improvement in my system though. After the "Edit Project details" , Saving Changes spinner wheel spun for nearly 2 minutes before it saved the changes.

**Comment by elsylambert** [comment]
The issue with the alert message has been written up in #6423 
Seems that Alert message is not just related to this issue.
I am passing this issue.

**Comment by mannycolon** [comment]
https://git.door43.org/lrsallee/en_ust_tit_book
