### ISSUE TITLE
Search "Anglicized" language names in language lookup

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6005]
### User Story

As a speaker of a language with a non-western script, I want to be able to lookup my language using my regular keyboard so that I don't have to memorize the language code in order to find my language.

### Features / Specifications

- [ ]
- [ ]
- [ ]

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/92ed0f65-9404-4ba5-8b64-648221cefdec)

### Definition of Done

- [ ] If I search for `nepali`, I should get 
![image](https://user-images.githubusercontent.com/13352518/56745025-33225780-673f-11e9-9804-4e5ab53170ad.png) as a result

- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@benjore - when I search for `Nepali` I get `Nepali [npi]` and `Kurux, Nepali [npi]` as the only matches. It looks like there is a bug in tC that doesn't handle well if there are two language entries with the same anglicized name (both 'npi` and `ne` are called Nepali)

**Comment by PhotoNomad0** [comment]
Fixing to show three matches for `Nepali`
![Screen Shot 2019-05-01 at 11 25 17 AM](https://user-images.githubusercontent.com/14238574/57030044-7c781880-6c11-11e9-8051-e1b6fb213b62.png)

**Comment by cckozie** [comment]
@benjore -  Wondering how literally I should interpret your definition of done. I can only search for "nepali" in the Language Name field. When I do, this is the result. Note that all text is in English. This is the case regardless of whether I use English or Hindi as the locale.
<img width="168" alt="lang" src="https://user-images.githubusercontent.com/8171759/57155318-c3484880-6da0-11e9-9233-8d1ffa4c78cd.png">

When I search for "ne" in the Language Code field, then I do see the result you are looking for.
<img width="228" alt="code" src="https://user-images.githubusercontent.com/8171759/57155407-ff7ba900-6da0-11e9-9587-716b83a29467.png">

Is this result acceptable?

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - interesting, ~it's looking like language code is being case sensitive.  Will take a look.~

**Comment by benjore** [comment]
Expected behavior: if I type in `nepali` and I get an entry that for `[ne]` , if I type in `hindi` I get an entry with `[hi]`. Both of those are met (I think), so I'm good.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - for language codes searching, it looks like had to make a compromise due to limitations of AutoComplete to just match language codes.  If we didn't, then auto complete would come up with a long list of everything that would also have the language code in the localized name and anglicized name which would often result in the real code dropping off the end of a very long list.  For example just doing case insensitive matching in whole string would cause matches for `en` to be:

![Screen Shot 2019-05-03 at 3 08 13 PM](https://user-images.githubusercontent.com/14238574/57159995-8d618f00-6db5-11e9-9b5d-8ec5cb6442fd.png)

And actual English language is not in the long list which stops at the language codes that start with `c`.  In this case we really need a two stage search - one for language codes and then for language names, but priority given to codes.  Alas, that is two much for the humble autocomplete.

**Comment by cckozie** [comment]
Works per Ben's comment in 1.1.4 (23a7fbd)
