### ISSUE TITLE
Spike: Why are there two languages for `[hi]`?

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6006]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]
![image](https://user-images.githubusercontent.com/13352518/56695952-0115e480-66b0-11e9-9706-f6ebf4b2ebd5.png)

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@benjore - this is a just a search **_feature_** - since for each language code there can be either an anglicized name, localized name, or both; I have included whichever names are found.  I don't see this as a major problem since whichever the user selects will set the correct language code (hi) which is what the app uses.  It seems that it is preferred to be able to search by either anglicized or localized name.

**Comment by PhotoNomad0** [comment]
It does seem strange they are searching by language code in the name field by putting brackets around it.  If they already knew the language code, just put it into the language code field and they are done.

**Comment by benjore** [comment]
The corollary to this one is https://github.com/unfoldingWord-dev/translationCore/issues/6005 . In this one, the only way to find the correct `Nepali` language code is by searching `[ne]`. In #6005, searching for the anglicized version doesn't work. In this one, it appears there are two entries for `[hi]`. 

Ultimately, what we need to happen between these two issues: 
- [ ] A user should be able to search for a language in the language's script (as it appears in `langnames.json`) or in the Anglicized version and be able to find it. 
- [x] Verify that there is no problem with having two entries for `[hi]` (or any other language)

**Comment by PhotoNomad0** [comment]
>  A user should be able to search for a language in the language's script (as it appears in langnames.json) or in the Anglicized version and be able to find it.

@benjore - This is being fixed in  #6005. So I think this spike is done.
