### ISSUE TITLE
Spinning tC logo/icon sometimes starts as a blank white box during tool loading

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6017]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Change the big spinner for the small spinner in all locations.
- [ ] Fix the issue that is causing the spinning logo to not show up. 
  - [ ] This is for Tool loading. 

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Related to #3522

**Comment by mannycolon** [comment]
Verified on b46b7c6

**Comment by elsylambert** [comment]
@benjore The alert message while loading the project says"Loading your project data." and loading the tool says"Loading tool data". Are these the desired messages?
Suggestion: "Loading Notes tool data" for tN, "Loading Word tool data " for tW and "Loading Alignment tool data" for wA, If this is a generic alert for all the three tools then, "Loading your tool data" or "Loading the tool data" are fine, which ever makes more sense. 

Also, there is no need of the OK button since there is no user input.

**Comment by benjore** [comment]
- [ ] Update "Loading your project data" to "Loading project data"

**Comment by elsylambert** [comment]
Not seeing issue with Spinning tC logo in 2.0.0 (00bca0b). The Alert messages are fine.
On Hold for a change in Alert message while importing a project locally.

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (855642f).

**Comment by cckozie** [comment]
Looks good in 2.0.0 (15ce3cd)
