### ISSUE TITLE
Alignment complete improperly set by tC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6112]
1.1.4 (a89d16f)
1. Open a project in wA
2. Align a verse completely
3. Note that the Alignment complete switch is set ON and the checkmark is set in the menu
4. Click on the Alignment complete switch
5. Note that the Alignment complete switch is set OFF and the checkmark is removed in the menu
6. Click on the next verse in the menu
7. Note that the checkmark is again set in the previous verse, the one you aligned
8. Click on that previous verse in the menu
9. Note that the Alignment complete switch is set to ON
10. Repeat step 4 and 5
11. Click on the Tool icon in the menu bar to return to the tools page
12. Relaunch the project in wA
13. Note that the checkmark is again set and the Alignment complete switch is again set to ON

**Comment by PhotoNomad0** [comment]
**Notes:**
- this looks like a tricky one to fix.  This like it has been a problem for a while since we haven't made any WA changes in 1.1.4.
- The chain of events goes like this:
  - changing verses changes contextId to change, which causes Api.toolWillReceiveProps() to be called in WA, which calls
  - this._validateBook(), which calls this._validateChapter(), which calls 
  - this._validateVerse() that determines that the verse is completely aligned and calls this.setVerseFinished(chapter, verse, true) (see line https://github.com/translationCoreApps/wordAlignment/blob/release-v1.1.3/src/Api.js#L294).  Think that line should be removed since they no longer want verse complete to be auto-toggled.

**Comment by cckozie** [comment]
Looks good in 1.1.4 (4b90ae7)
