### ISSUE TITLE
Projects that are overwritten with a USFM2 file cannot be uploaded to Door43

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6149]
### User Story

As an aligner, I want to update my text in USFM2, reimport it into tC, and upload it to DCS so that I can use other tools besides tC to edit my text.

### Features / Specifications

- [ ] `en_ult_ezr_book cannot be uploaded because there have been changes to the translation of that project on your Door43 account.`
- [ ] Renaming the project seems to be the only way to get around this. 
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
2.0.0 (aff6765)
This is still a problem. Now in some cases the user receives the "[project] cannot be uploaded because there have been changes to the translation of that project on your Door43 account." message.
Moving the issue back to the Bugs lane.
1. Import this project https://git.door43.org/shojojohn/hi_irv_act_book 
2. Upload it to Door43
3. Open the project details page and add a couple contributors and checkers
4. Upload it to Door43
5. Export it to USFM without alignments
6. Reimport the exported file choosing the Overwrite option
7. Upload it to Door43
Note that the upload fails

**Comment by cckozie** [comment]
Still a problem in 2.0.0 (15e3755)

**Comment by PhotoNomad0** [comment]
Note: suspecting the original git history is not copied into final merged project.

**Comment by PhotoNomad0** [comment]
Note: 
Found that USFM import creates a new git history, so made fix to make sure this is overwritten by existing project so we preserve the git history of the project.

**Comment by PhotoNomad0** [comment]
@cckozie - have a test build for this if you want to check it:

From the `release-vx2.1.0-test` branch:
[Linux build 2.1.0 (8221c56)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-linux-x64-2.1.0-8221c56.deb) is ready for download.
[macOS build 2.1.0 (8221c56)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-macos-x64-2.1.0-8221c56.dmg) is ready for download.
[Windows x64 build 2.1.0 (8221c56)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-win-x64-2.1.0-8221c56.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (8221c56)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-win-x32-2.1.0-8221c56.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 Looks good in the test build.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (2216ef6)

**Comment by cckozie** [comment]
Works in 2.1.0 (8b531e4)

**Comment by elsylambert** [comment]
Works in  2.1.0 (7adcd44).
