### ISSUE TITLE
Error while importing an old testament project 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6158]
#1.2.0 (b1cd66e)

https://git.door43.org/lrsallee/en_ult_rut_book

The project is working fine in 1.1.3 and 1.1.4. 
It breaks the same way if the project exists when upgrading from 1.1.4.
Steps to re-create:
1. Searched for an old testament project.
2. selected the project and Continued.
3. Error showed up as in the snapshot, while the project was loading.

![Error while loading the project.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/018b2be8-4e4d-498d-a1b3-92d0b51ef16c)

Tried downloading latest Hebrew Content, but it did not help.

**Comment by cckozie** [comment]
1.2.0 (7caed9f) 
[en_ult_rut_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3312189/en_ult_rut_book.2.zip)
SCENARIO 1: **Fixed in 1.2.0 (cf6fd22) after downloading latest UHB**
This was an existing project in 1.1.4, and it woked as expected there. It was using the resources that were bundled with the 1.1.4 release.
After upgrading to 1.2, the tW card has all category checkboxes cleared and the Launch button is disabled.
![image](https://user-images.githubusercontent.com/8171759/59880103-db385380-9371-11e9-993a-c12bbb152c77.png)

SCENARIO 2 (this is a problem that currently exists in 1.1.4, but is related in that it set the stage for upgrading in scenario 3 below):  **Fixed in 1.2.0 (cf6fd22)**
[en_new_rut_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3312190/en_new_rut_book.zip)
While running 1.1.4, the latest hbo in 1.1.4 was downloaded, then a new Ruth project was imported. tC 
 now hangs with the loading dialog displayed and a console error message of "logger.js? [sm]:32 openTool() Error: ENOENT: no such file or directory, lstat'/Users/cckozie/translationCore/resources/en/translationHelps/translationWords/v9/name/index.json'"
![image](https://user-images.githubusercontent.com/8171759/59880632-1b4c0600-9373-11e9-991a-ff8fe23848ff.png)

SCENARIO 3:  **Fixed in 1.2.0 (cf6fd22)**
After upgrading to 1.2, when attempting to select the project in SCENARIO 2, the first two time an alert with the message "undefined is not iterable" was displayed. (See #6164)
After selecting it the third time, the tools page was displayed with Names and Other Terms unchecked and Key Terms showing an indeterminate state on the tW tool card:
![image](https://user-images.githubusercontent.com/8171759/59881317-e9d43a00-9374-11e9-9eee-2b36bbe92372.png)

When this project was loaded in tW, only the "name, named" group is displayed:
![image](https://user-images.githubusercontent.com/8171759/59881591-931b3000-9375-11e9-9e9f-28c73cd0caa6.png)

The first attempt to download the latest hbo resource failed, but the hbo no longer was showing as available on the resource download selection screen. I deleted the hbo on my machine and tried again. The download failed, but again the hbo no longer shows in the update resource selection screen. Deleted it on my machine again and restarted tC. This time it succeeded, but the results of selecting the project in SCENARIO 2 rendered the same results as before downloading the latest hbo.

Here is the log file.
[Thu Jun 20 2019.log 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3312182/Thu.Jun.20.2019.log.2.zip)

**Comment by mannycolon** [comment]
@cckozie If you don't mind could you please clean up the items above? maybe list them up so they're easier to read.

**Comment by cckozie** [comment]
@mannycolon - I tried :) If you still have questions we can chat online.

**Comment by mannycolon** [comment]
Could also fix 6073

**Comment by mannycolon** [comment]
Verified on f9728ae

**Comment by elsylambert** [comment]
needs regression
