### ISSUE TITLE
Critical Error Handling

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6256]
### User Story

As a user who receives a critical error, I want tC to fail gracefully so that I have a good UX & so I don't have to restart tC.

### Features / Specifications

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/2ff479d7-e591-45e3-839d-498fc5f538c8)
- [ ] If the user clicks "Send Feedback", the modal opens up on top of this screen. When closed, they would still be at this screen
- [ ] If the user clicks "Return to Home", they will be brought back to the Home Screen (of the stepper)
- [ ] This screen should always be shown instead of the current Critical Error screen.

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
Verified on 71e7de6

**Comment by cckozie** [comment]
2.0.0 (71e7de6)
The button text is Return Home, but when clicked, the user is returned to the Projects page, not the Home page.

Is this to be expected at this point?
![image](https://user-images.githubusercontent.com/8171759/62483781-1c4bc200-b77e-11e9-993f-5f78696fab2b.png)

(Button text is Return Home vs. Return to Home as in the included mockup. This was approved by @benjore in a slack thread, so it is OK.)

**Comment by benjore** [comment]
Go back to Projects instead of Home screen. Change verbiage to "Go to Projects"

**Comment by PhotoNomad0** [comment]
~verified in translationCore 2.0.0 (03081b5)~

**Comment by PhotoNomad0** [comment]
Oops, moved this to QA too soon.  Merged new locale strings and waiting for new dev build.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (61fec46) with hi locale

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (92b46cf).

**Comment by elsylambert** [comment]
Steps to bring up the Critical Error screen:
- Log in as a user that has some projects on Door43.
- Import one of those projects, but change the translation id when you get to the project details screen.
- When the alert comes up asking whether you want to rename the repo or create a new one, click the X on the alert instead of one of the buttons.
- If the new project does not appear on the Projects page, click Go to User, then Go to Projects.
- The new project should show as the active one. Click on the Tool icon in the menu bar. That should bring up the critical error message.
