### ISSUE TITLE
Alignment memory not shown for an existing project

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6380]
2.0.0 (8a6a8c5) .
Here is the project:
[en_new_heb_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3503373/en_new_heb_book.zip)

Import this project with same Translation ID as one of your aligned projects. This project does not show word suggestions from the aligned project.
Steps to Replicate: 
Just dropped the project into the projects folder, then imported an aligned Matthew with the same translation id. None of the alignments in Matthew  showed as suggestions in Hebrews.
Then made some manual alignments in Hebrews that also did not show as suggestions in Hebrews.

**Comment by PhotoNomad0** [comment]
@benjore @elsylambert @RoyalSix - The problem is due to the selections made in tN in this Hebrews project.

To recreate this in another project, just make a selection in tN for a check that has multiple words in the original language (probably would have same problem in tW).  

**Developer Troubleshooting Notes:**
In WA initMAP() during startup, there is an exception being thrown that is breaking wordmap.  Unfortunately it is in a promise and it is not caught so there is no log entry.

I put a try catch in that function and found this exception when loading alignment memory from tN tool:
```
TypeError: source.split is not a function at WordMap.appendAlignmentMemoryString (/Users/blm/Development/Electron/translationCore/node_modules/wordmap/dist/WordMap.js:94:36) at /Users/blm/Development/Electron/translationCore/tC_apps/wordAlignment/src/components/Container.js:472:25 at run (/Users/blm/Development/Electron/translationCore/node_modules/core-js/library/modules/es6.promise.js:75:22) at /Users/blm/Development/Electron/translationCore/node_modules/core-js/library/modules/es6.promise.js:92:30 at flush (/Users/blm/Development/Electron/translationCore/node_modules/core-js/library/modules/_microtask.js:18:9) at process._tickCallback (internal/process/next_tick.js:61:11) 
```

tN is returning item 2 of alignment array that has sourceText as an array and not the expected string, so it chokes on split.  Here is the data grab of the tN alignment memory for this project:

![Screen Shot 2019-08-15 at 8 34 06 AM](https://user-images.githubusercontent.com/14238574/63094874-9a0a8d00-bf37-11e9-914d-8173b638ec80.png)

**Fixes Needed**
It looks like we should fix two things: 
- better catching/logging/recovery of errors in initMAP() in WA (probably also needs fixing in checking-tool-wrapper)
- map.appendAlignmentMemoryString() needs to work with source text that is already an array of words. Or fix getAlignmentMemory in checking-tool-wrapper to not return an array for source quote.

**Comment by PhotoNomad0** [comment]
Here is a check in Hebrews that would cause wordmap error if selection is made:

{
  "contextId": {
    "occurrenceNote": "“40 years” (See: [Numbers](rc://en/ta/man/translate/translate-numbers))",
    "reference": {
      "bookId": "heb",
      "chapter": 3,
      "verse": 10
    },
    "tool": "translationNotes",
    "groupId": "translate-numbers",
    "quote": [
      {
        "word": "τεσσεράκοντα",
        "occurrence": 1
      },
      {
        "word": "ἔτη",
        "occurrence": 1
      }
    ],
    "quoteString": "τεσσεράκοντα ἔτη",
    "glQuote": "forty years",
    "occurrence": 1
  },
  "selections": [
    {
      "text": "for forty years",
      "occurrence": 1,
      "occurrences": 1
    }
  ],
  "nothingToSelect": false,
  "userName": "ElsyLambert",
  "modifiedTimestamp": "2019-08-14T14:45:41.359Z",
  "gatewayLanguageCode": "en",
  "gatewayLanguageQuote": "for forty years"
}

**Comment by PhotoNomad0** [comment]
To "fix" this project - in tN for this project, removed selections for numbers, pronouns 5:11, pronouns 9:5.  And in tW remove selection for zion.  WordMap will start working.

**Summary:** Either tN or tW selections where there are multiple words in the Original Language can break word suggestions in the project.

**Comment by PhotoNomad0** [comment]
[41-MAT-aligned.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3506072/41-MAT-aligned.usfm.zip)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (af07d31)

**Comment by elsylambert** [comment]
Not seeing the issue in 2.0.0 (ade72a0). Word map suggestions are showing up in wA when there are two or more Original language selections in tN and tW.

Needs regression.

**Comment by cckozie** [comment]
Looks good in 2.0.0 (3727b58)
