### ISSUE TITLE
tC hangs for two minutes after navigating to a verse in wA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6554]
2.1.0 (b775824) 
[projects.zip](https://github.com/unfoldingWord/translationCore/files/3843727/projects.zip)
 (I'm not sure if steps 1-6 are necessary or not)
1. Download the latest English, Greek, and Hebrew resources
2. Import the John project giving it translation identifier ult
3. Load it in wA
4. I added the t4t to the scripture pan
5. Open the expanded scripture pane
6. Return the the Projects page
7. Import the Matthew project giving it the same translation identifier ult
8. Load it in wA
9. Navigated to 8:32
10. Attempt to open the expanded scripture pane or other activity (other than scrolling the menu), and note that the app is hung. On my fastest Mac, it hangs for about 2 minutes. There are hundreds of alignment memory messages in the log.

**Comment by da1nerd** [comment]
Only steps 7-10 are necessary. I ran the code at commit b77582416.

With this particular verse wordMAP is having a difficult time generating suggestions that contain the proper order of occurrence. To get the proper occurrence order it will throw away suggestions until it finds the right one (or runs out of permutations). Normally wordMAP will need to throw away just a few suggestions, but in this verse it's throwing away around 600 suggestions.

Getting wordMAP to produce suggestions with the proper occurrence has been difficult and additional improvements will require a lot of research and potentially some fundamental changes to wordMAP.
As a temporary solution I would propose taking the following actions:

- [x] verify there's no bug in the occurrence validation. Maybe it's needlessly discarding suggestions.
- [x] provide a configurable limit to the number of retries (default to 10). If it runs out of retries it will just return the best numerically scored suggestion and log a warning.

**Comment by da1nerd** [comment]
while investigating this I discovered a bug that is likely causing the second problem in https://github.com/unfoldingWord/translationCore/issues/6237#issuecomment-552589121

**Comment by da1nerd** [comment]
ok I've isolated this particular corner case. The problem arises when alignment memory associates source and target n-grams that occur on opposite sides of the verse. Or more specifically, the alignment memory pulls a target n-gram out of it's occurrence order. An illustration will make this easier to understand.

Take for instance, the following translations.
```
Ich liebe das Aussehen von Schnee im Winter
I love the look of snow in the winter
```

If wordMAP receives an alignment memory like `das=the winter` (mistakes happen some times right?) the last "the" is forced into the position of the first "the". This happens because currently all alignment memory gets a HUGE boost in the prediction score.
Because we recently added some filtering to enforce the correct order of occurrence, wordMAP has to sequentially toss out the higher scoring suggestions until it finds one that works. If the alignment memory only produces one such error it may not be a big deal, but in sentences with lots of repeated words this exponentially increases the time required to find a valid suggestion.

I think this could be resolved if we allow alignment memory to be influenced by the `AlignmentPosition` algorithm.

**Comment by PhotoNomad0** [comment]
In translationCore 2.1.0 (2216ef6)

**Comment by cckozie** [comment]
2.1.0 (8b531e4) 
[projects2.zip](https://github.com/unfoldingWord/translationCore/files/3865053/projects2.zip)

Import the John project in the zip file
Import the Matthew project in the zip file giving it the same translation ID as the John project
Load the Matthew project in wA
Navigate to 8:32
On my fastest Mac it now takes about 10 seconds to show the suggestions. In 2.0 it took less than 3 seconds on the same machine. I think more work needs to be done on this so the user does not experience this sort of performance degradation after upgrading to 2.1.

**Comment by PhotoNomad0** [comment]
Should be in https://tc-builds.door43.org/build/release-v2.1.0/translationCore-macos-x64-2.1.0-5980326.dmg

**Comment by cckozie** [comment]
Added #6572 to revert wordMAP back to the 2.0 code for the 2.1 release.

**Comment by da1nerd** [comment]
I've opened a PR (#6647) which should resolve the performance issues described above. I'm also investigating wrapping wordMAP inside of a web worker which could further improve UI performance.

**Comment by PhotoNomad0** [comment]
Verified in build at https://github.com/unfoldingWord/translationCore/actions/runs/32631095

**Comment by cckozie** [comment]
2.1.0 (228ed0f) 
I'm again seeing ~3 seconds to display the suggestions in 8:32.
