### ISSUE TITLE
[48] SPIKE: Electronite planning

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6657]

**Comment by PhotoNomad0** [comment]
**Notes:**
Items learned in getting to build/run:
- File system:
    - imports and require()'s still use relative paths based on source folder.  Restrictions on importing from files below src/.  There seems to be an exception for package.json, but that may be because the start script copies package.json to build directory. 
    - You can only use string constants as parameter to require().  If you use a string variable it will fail to load.  Probably due to webpack needing to modify paths at compile time.   - File access using fs are relative the base tCore folder.  This is true also in tools.  So for example locale files would be at `./src/locale`
    - `__dirname` usage in app always points to / when webpack is used - regardless of the source file location.   So not very useful.
- in React, now need to first do import of image and then can use as src  (e.g. `src={Image}`).  Loading from path does not work anymore.
- in React, now need to do import of css files instead of loading with html.
- Loading each locale seems very slow.  And each locale is calculated twice (e.g. once for `en` and then again for `en_US`
- path.datadir() is deprecated (and no longer works), use ospath.dir() instead.
- tools:
  - Loading tools cannot use generated path for require. For now have a switch statement selecting string constant for each tool's path, and that works for now.
  - tc_tool - uses a require() of generated path for non-translatable which fails at runtime.  Can easily change to be a json file.

Still TODO:
1. Fix startup splash screen.
2. Fix build scripts for github actions, etc.
3. Get unit tests running
5. Some images need to be loaded into tC: Tool card, and ?
6. How to get css to load in tools?  Seems to be working in tC, but not seeing CSS in tools?  The styling seems to be off for all tools.
7. Need to find fix for `redux-logger` crashing app when enabled.  Thought it may be a deep-diff bug, but seems to crash even with diff disabled.
8. Resolve warning: `DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
1. Resolve warnings that react life cycle methods are deprecated.

**Comment by PhotoNomad0** [comment]
**Note:** 
moving current work into sandbox-electronite branch
