### ISSUE TITLE
Reported by Larry: Alignments in wA invalidated after tN invalidation fixes

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6684]
2.1.0 (7adcd44)
Here is the Project: 
[en_ult_rut_book.zip](https://github.com/unfoldingWord/translationCore/files/4215138/en_ult_rut_book.zip)

Copy the Ruth ULT project in Projects Folder. It shows one invalidated alignment in the WA tool, and a bunch in the tN and tW tools. I opened the WA tool and checked the one broken alignment. Everything was OK. I did my 'normal fix' of dragging a word back to the EN list and then aligning it again, and everything was OK. I then opened the tN and tW tools to look around at the errors. I fixed a few, and then went back to the project screen and noticed that the WA tool dropped to Zero percent, and every verse had broken alignments. I have the latest resources installed. UHB V2.1.10.
<img width="610" alt="Screen Shot 2020-02-17 at 11 38 03 AM" src="https://user-images.githubusercontent.com/51806180/74672801-05017e80-517c-11ea-86b4-91fc8b3604fa.png">

**Comment by elsylambert** [comment]
To Replicate this issue:
1. Install the Release Version 2.1.0 (7adcd44).
2. Check the Resources, if they are latest (I checked with UHB 2.1.10)
3. Copy the project in Projects folder.
4.  Open the Project and note that the wA shows 100% and 1 Invalidation link on the tool card. There are a few invalidation on tW and tN as well.
5.  Open wA, Fix the invalidation by dragging a word back to the EN list and then aligning it again.
6. Open tN and fix some of the invalidation by completing the checks.
7. Go back to the Tools Page and see now wA shows 85 broken links and tool card percentage as 0%.

**Comment by elsylambert** [comment]
Able to Replicate in Windows-64 build as well. Need to restart tC after the Resources are updated to the latest to replicate this issue.

**Comment by cckozie** [comment]
After several attempts I am unable to replicate the problem on 2.1 either on my Mac or Windows machines. However, I can replicate it on my Mac in 2.2.0 (f898237). On 2.2 when the project is first opened it shows all of the alignment resets, but the wA card continues to show 100% even after opening the project in the other tools and making changes there.
Based on that I'm guessing that it may be a race condition issue.

**Comment by PhotoNomad0** [comment]
Updating of the en tn helps causes the project to update to using the latest Orig Language version in the tn checks (this only happens when the tn tool is opened). This causes the grief since the wa and tw are just using the last version in the directory list returned by the file system. Since these were not sorted by semantic version rules, v2.1.8 could be used as the most recent and not v2.1.10(of course it's OS dependent).

**Comment by PhotoNomad0** [comment]
It is a very quick fix to use the latest version of the Orig language for wa and tw. And then we would not see this issue as long as the GL helps are in sync with latest original language.

But this doesn't fix the issue for other GLs such as Hindi that often are based on older Orig lang versions.

It seems to be a ticking time bomb - hopefully we don't see as dramatic changes to the Orig Language again.

The real solution (in addition to fixing the sorting) seems to be to keep two versions of the original language in memory if the tN is using an older version than the most recent on the system, but this would be a large change for a .1 release.

**Comment by PhotoNomad0** [comment]
Suggested items to fix in 2.1.1 release:

- [x] fix sorting of versions so WA and TW will be using the latest original languages
- [x] add versions of resources being used in tools to log file
- [x] add resource versions used for tool checks/alignments to project manifest
- [x] warning dialog on launch of tN when using older version of original language than the other tools are using.

**Comment by PhotoNomad0** [comment]
**Current Problems dealing with catalog changes:**
- tN checks are specific to a GL and tied to specific original language version, but may not be updated at same time as the original language updates (e.g. hi tN checks may lag).
- the checkers and aligners have no visual indication of what versions of the original language they are currently using.
- we hope that future original language changes will be small without many breaking changes. But since all tools are loaded at same time these changes may result in:
  - checkers making edits in tN that uses older original language version may cause invalidations in WA and tW that are based on changes to original language (in that case tC currently **_unaligns the whole verse_**).

**Future possible fixes:**
1. not do anything and hope for the best from catalog changes.

2. change wa tool to not invalidate alignments for whole verse on source changes, but just alignments based on original language word that is no longer found.
  - pros: will minimize spurious alignment invalidations from original language changes.  Certainly a less nuclear option and makes less work for aligners.
  - cons: complex change to WA - may take quite a while to set up test cases and debug

3. when loading and editing in tN in an older original language version, disable immediate validation of WA alignments and tW checks (validations can be run at a later time).
  - pros: will prevent spurious invalidations from original language changes
  - cons: user will not get immediate feedback on WA and tW invalidations

4. when loading and editing in tN in an older original language version, any immediate validation of WA alignments and tW checks will be done against newer original language version.
  - pros: will prevent spurious invalidations from original language changes
  - cons: adds complexity in tCore to do checking against original language versions specific to tool.

5. in tC make all tools use the same original language version that the tN tool currently uses
  - pros: edits in tN would not cause WA alignments and tW checks to be revalidated against a different original language version.
  - cons: if user loads project aligned with newer original language version, will get invalidation

6. in tC make tN tool use the latest original language version loaded on system
  - pros: edits in tN would not cause WA alignments and tW checks to be revalidated against a different original language version.
  - cons: when user updates original language, tN checks may be invalidated or disappear from left menu if linkage cannot be made to original language through the GL.

**Comment by birchamp** [comment]
@PhotoNomad0 @cckozie 
**Alert text for launching tN:**  
Opening this tool could reset/undo/break some of your work. Are you sure that you want to continue? 

The Gateway Language that you have chosen for translationNotes uses a previous version of the original  (Hebrew or Greek) language text.   Launching this tool may reset some of the checks that have been completed in the other tools.  The checks that are reset they will be marked as incomplete each time you launch this tool. If you have not updated recently, you may check for new Gateway language content below.

**Comment by cckozie** [comment]
@birchamp @elsylambert @PhotoNomad0 
My thoughts/edits: (Some changes made because we should not assume that the current user is the one who did the existing work, some to add clarity in my view, and I did not think the last sentence about updating was pertinent)

Opening a project in translationNotes could invalidate some work previously completed on it. Are you sure you want to continue?

The Gateway Language you have chosen to use for translationNotes uses a previous version of the original (Hebrew or Greek) language text. Launching it now may reset some of the checks previously completed in translationWords and/or invalidate some alignments. The checks and alignments that are reset will be marked as incomplete after launching this tool.

(The alert should show Cancel and Continue buttons. Cancel should be the primary button)

**Comment by elsylambert** [comment]
> @birchamp @elsylambert @PhotoNomad0
> My thoughts/edits: (Some changes made because we should not assume that the current user is the one who did the existing work, some to add clarity in my view, and I did not think the last sentence about updating was pertinent)
> 
> Opening a project in translationNotes could invalidate some work previously completed on it. Are you sure you want to continue?
> 
> The Gateway Language you have chosen to use for translationNotes uses a previous version of the original (Hebrew or Greek) language text. Launching it now may reset some of the checks previously completed in translationWords and/or invalidate some alignments. The checks and alignments that are reset will be marked as incomplete after launching this tool.
> 
> (The alert should show Cancel and Continue buttons. Cancel should be the primary button)

Sounds good.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.1 (f4b4b6c)

**Comment by elsylambert** [comment]
I opened the Ruth Project in  2.1.1 (f4b4b6c) and got critical error warning message after the tools page was loaded.
<img width="1792" alt="Screen Shot 2020-02-24 at 11 00 39 AM" src="https://user-images.githubusercontent.com/51806180/75168624-34bd0300-56f5-11ea-941f-6c6b22938e21.png">
(From Koz) I believe this was a process error and not a problem in tC.

**Comment by elsylambert** [comment]
[Mon Feb 24 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4245706/Mon.Feb.24.2020.log.zip)

[en_ult_rut_book (1).zip](https://github.com/unfoldingWord/translationCore/files/4245533/en_ult_rut_book.1.zip)
- Got 3 Invalidations in wA. I corrected the invalidations in wA and made alignments complete.
- Then Opened the tool tN and got the warning message as intended. I clicked on Continue and made some selections in tN.
- I returned to the tools page and saw 3 invalidations in wA. So the corrections I completed in wA were not saved.
(From Koz - I believe this is working as expected and is the reason for the warning)

**Comment by cckozie** [comment]
The 2.1.1 (f4b4b6c) build includes both hbo v2.1.8 and v2.1.11.
The 2.1.1 (f4b4b6c) build includes both ugnt v0.9 and v0.12.
The manifest on the Ruth project attached to this issue shows the tsv relation is to hbo 2.1.10.
The user is not prompted to download v2.1.10 as I would expect.

**Comment by cckozie** [comment]
User is warned about the potential of invalidations even if the project has never been previously opened in tN.
1. Import this project and resolve the merge conflicts [en-x-demo1_php_text_ulb.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4246102/en-x-demo1_php_text_ulb.tstudio.zip)
2. Open it in wA but don't make any alignments
3. Open it in tN and note the warning.
This does not happen on usfm projects I have tested.
I wrote this up on #6703

**Comment by PhotoNomad0** [comment]
@cckozie  - up to now we only put up the warning in tN if you are opening it with original language version that is older than the latest on the system.  Do you want to add conditions?  And what would they be?

**Comment by PhotoNomad0** [comment]
I could see adding a check for existing alignments and tW checks as a precondition for the warning.

**Comment by birchamp** [comment]
I'm assuming that checking for broken alignments will take too much processing time, and that checking if there are existing alignments and tW checks won't take very much.  Is that correct?

**Comment by cckozie** [comment]
@birchamp @PhotoNomad0 
Since I'm viewing this as a stop-gap measure and not the long-term solution, I don't think it's worth the effort to test for those things. If there are no alignments, there is nothing to do in tW.
The only condition I think we should test for is that if tN has not been used on the project with an older version of the gl (a project not previously checked intN) then we shouldn't display the warning.

**Comment by PhotoNomad0** [comment]
@cckozie - unfortunately that is not straight forward.  We are just now starting to record last gl and original language version used for checks in manifest.  The tsv_relations in the project manifest is also not updated after project import.

Just checking for the presence of alignments or selections would be very fast since we already have tool progress displayed.

**Comment by birchamp** [comment]
@PhotoNomad0 Can we check if the version of the biblical languages that's being used by the GL TN is different from what's selected for the WA or TW?

**Comment by PhotoNomad0** [comment]
@birchamp we already do that.  That is the only condition we currently have to show the warning.

**Comment by cckozie** [comment]
@PhotoNomad0 - In 1.2.0 (issue #6184) we started tracking the gl and original used in tN, so can't we easily determine if that's not older than the latest? Aren't we already doing that to see if we need to prompt the user to download an older source?

**Comment by PhotoNomad0** [comment]
@cckozie - I don't think that will make any difference with your tStudio project above.  On import, tCore is initializing the tsv_relation to the manifest to ugnt v0.9 even before the project is opened, which is older than my most recent ugnt on my system.  So I would still get the warning.

**Comment by PhotoNomad0** [comment]
@cckozie - I don't see the tsv_relation initialized for USFM imports however...

**Comment by PhotoNomad0** [comment]
@cckozie - ~still seems to be problem that tsv_relation is not being updated in project manifest.  I will check into that.~

I does get updated, but just not if resource is updated when project is open.  In that case it gets updated the next time you open project.

**Comment by cckozie** [comment]
Tests run and results on previous older original language needed alert and new invalidations warning. All results were as expected.

Clean install of   1.1.4
Single version of ugnt and uhb installed
Import OT and NT books and open in tN
tsv relation not stored in manifest
Save projects
Clean install of 2.0.0
Single version of ugnt and uhb installed
Load projects in tN
tsv relation not added to Titus, but was   added to Ruth
Import OT and NT books and open in tN
No version warnings displayed
tsv relation added to all projects
Save projects
Clean install of 2.1.0
Single version of ugnt and uhb installed
Hindi Titus projects from 1.1.4 and 2.0   display version update warnings
Import OT and NT books and open in tN
Newly imported Hindi Titus projects   displays version update warning
Save projects
Clean install of 2.1.1
Multiple versions of ugnt and uhb are   installed with 2.1.1
All existing Hindi Titus projects from   display new invalidation warning, then the version warning
All existsing English projects display   new invalidations warning
Newly imported English projects do not   display any warnings
Newly imported Hindi Titus project   displays new invalidations warning and then the version update warning.

**Comment by elsylambert** [comment]
2.1.1 (f4b4b6c). Getting warning Alert when tN is opened and alignments are reset in wA , as implemented for this release.

**Comment by elsylambert** [comment]
Looks good in 2.1.1 (17b9e26).
