### ISSUE TITLE
[6] SPIKE: Ruth tN "problem with content" errors

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6721]
Possibly normalizing the string to NFC prior to the text comparison could resolve the issue. 
The UNICODE report may be of some value: https://unicode.org/reports/tr15/#Canonical_Equivalence

Reported by Jobby: https://unfoldingword.zulipchat.com/#narrow/stream/207545-wg-gl/topic/Hindi.20BPF.20process/near/188980789

tNotes →Assumed Knowledge and Implicit Information
Ruth 1:16
Ruth 2:18
Ruth 3:13
Ruth 4:22

tNotes → How to Translate Names
Ruth 4:19

tNotes → Symbolic action
Ruth3:4 

The content may be wrong, but it has been checked to be valid in Robert's script: https://unfoldingword.zulipchat.com/#narrow/stream/207527-wg-tc/topic/Completed.20Book.20Package.20Issues/near/189634757

**Comment by PhotoNomad0** [comment]
@cckozie @birchamp - there is not much to go on here.  What version of tCore?  What version of resources?  If he was using 2.1.1 a log file or or zipped project give tell us some details.

**Comment by cckozie** [comment]
@PhotoNomad0 
Here is a log from 2.1.1 using the latest resources and accessing the checks in question. 
tC indicated a problem with each of the checks except for 4:19 in How to translate names.
[Thu Apr 02 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4422505/Thu.Apr.02.2020.log.zip)
I imported and used this project: 
[08-RUT.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4422514/08-RUT.usfm.zip)

**Comment by PhotoNomad0** [comment]
@cckozie @birchamp - it looks like tsv-groupdata-parser is calling the string-punctuation-tokenizer, and it is splitting words at a Word Joiner (U+2060).  It looks like we haven't added support for the Word Joiner since we switched the uhb from using ZERO WIDTH JOINER.

This would also impact exports with alignments.

The fix is trivial in string-punctuation-tokenizer, then a little work adding some unit tests to tsv-groupdata-parser and string-punctuation-tokenizer, and then updating dependencies in other modules.

**Comment by PhotoNomad0** [comment]
@cckozie @birchamp - an update here:  @klappy already had a fix for string-punctuation-tokenizer, but it had not made it all the way through publishing as an official npm package.  We worked together to publish this as version 2.0.0.  Now it looks like all that is needed is to integrate it into tC - 4 or more PRs.

This sprint is completed now.  Just need decision on when to pull this in.
