### ISSUE TITLE
Selection Invalidation Link icon is missing on the invalidated verse

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6785]
2.2.0 (2375ae5).
when the selection is invalidated, there is no Invalidation Icon on the invalidated verse.

- Open the tW tool, make a selection for a check and save.
- Open tN tool, edit the same verse , changing the text which was selected in step 1.
- Open tW, we get the selection invalidation alert, but cannot find the invalidated icon on the verse. As a result of the icon not displayed, the filter does not bring up the invalidated verse.

**Comment by cckozie** [comment]
Adding this to the edit and broken link icons epic.

**Comment by BincyJ** [comment]
Setting medium priority since Functionality working but UI broken. Needs fixing.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (4496c12)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (4496c12). Broken link is displayed on the Invalidated verse;-
- when edits are done in tW, icon is displayed in tN and wA for invalidation.
- When edits are done in tN, icon is displayed in tW and wA.
- when edits are done in wA, icon is displayed on tN and tW.

**Comment by cckozie** [comment]
2.2.0 (d786804) It is better, but still broken
1. Import https://git.door43.org/TC_SAVE/en_edit_phm_book
2. Load it in tN
3. Verify that 'you' is selected on verse 1:3 in the Inclusive and Exclusive We group
4. Verify that 'Christ' is part of the selection on verse 1:25 in the Forms of You group
5. Verify that 'soldier' is part of the selection on verse 1:2 in the Exclusive and Inclusive We group 
5. Return to the Tools page
6. Load the project in tW
7. Navigate to verse 1:3 under Christ
8. Note that 'you' is selected 
9. Click on 1:25 in the same group
10. Note that 'Christ' is selected
11. Open the expanded scripture pane
12. Edit verse 1:3 to change 'you' to 'us'
13. Choose a reason and click Save, and click OK on the resets alert
14. Still in the expanded scripture pane, edit verse 1:25 to delete the word 'Christ'
15. Choose a reason and click Save, and click OK on the resets alert
16. Click Close
17. ERROR: Note that on verse 1:3 the edit icon is displayed on the check, but the checkmark is still displayed instead of the broken link icon
18. Note that the icons on verse 1:25 are correct
19. Navigate to verse 1:2 under church
20. Note that 'soldier' is selected
21. Click Edit Verse
22. In the verse editor change the word 'soldier' to 'warrior'
23. Choose a reason code
24. Click Save, and click OK on the resets alert
25. Return to the Tools page
26. Open the project in tN
27. Navigate to 1:25 under Forms of You
28. ERROR: Note that the text has been changed and the selection has been cleared, but the check mark icon is displayed instead of the broken link icon
29. Navigate to 1:2 under Exclusive and Inclusive We
28. ERROR: Note that the text has been changed, but only the part of the selection that contained 'soldier' has been cleared.

Also, no invalidation link or edit icons are displayed in either tN or tW on checks where an import with overwrite invalidated the check.
The project in step 3 below includes the same edits performed in the steps outline above.
1. Delete the project used above
2. Reimport the project
3. Import this project choosing the Overwrite options [58-PHM-edits.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4647433/58-PHM-edits.usfm.zip)
4. Load the project in tN and tW and note that all of the the checks that were modified in the steps above now still show the checkmark and do not show the broken link icon or edit icon.

**Comment by PhotoNomad0** [comment]
@cckozie - excellent write up here of various failure modes.  Very clear here.

**Comment by cckozie** [comment]
Thanks, @PhotoNomad0 - I had to do it that detailed in order to replicate it myself:)

**Comment by PhotoNomad0** [comment]
Note: it looks like there is a problem when other tools are being invalidated that they are unaware of the new verse text.

**Comment by PhotoNomad0** [comment]
verified changes in Version 2.2.0 (4920def)

**Comment by elsylambert** [comment]
Not fixed- 
29. ERROR: Note that the text has been changed and the selection has been cleared, but the check mark icon is displayed instead of the broken link icon
Navigate to 1:2 under Exclusive and Inclusive We
ERROR: Note that the text has been changed, but only the part of the selection that contained 'soldier' has been cleared.

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (a444d5f). Seeing Invalidation link icon on the invalidated verses including the cases mentioned above.

**Comment by cckozie** [comment]
Invalidation links show as expected in 2.2.0 (4920def)
