### ISSUE TITLE
2.2.0 loses existing tN selections on projects imported from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6791]
2.2.0 (2375ae5)
https://git.door43.org/TC_SAVE/en_ult_3jn_book
When the above project is imported into tC 2.1.0 the tN card shows 100% complete(which is accurate. All checks are completed)
When that 2.1.0 environment is upgraded to 2.2.0, the tN card shows 61% (which is accurate, some completions do not show, but there are no invalidations)
When the project is imported into 2.2.0, the tN card shows 0% and there are no selections in the project.

**Comment by PhotoNomad0** [comment]
@cckozie - interesting test project in that it is a bit broken: has the selection entries in the check data, but the group data index does not have the selections.  Suspect that the older tCs were doing some automated project cleanup.  Suspect this is not being done anymore.  This could be due to performance improvements or moving reducers into tools.

**Comment by birchamp** [comment]
DoD: tN selections on imported projects are not lost.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (6a53472)

**Comment by PhotoNomad0** [comment]
This should also fix issue that progress doesn't update when gateway language changes.  And this should fix issue that adding comments to tN and tW would not show up in CSV exports.

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (6a53472). tN checks are not lost when imported to 2.2.0. Progress works fine when GL is changed and also the comments in tN and tW are showing fine in CSV exports.

**Comment by cckozie** [comment]
2.2.0 (690092a) 
tN's are not lost when upgrading the project. 
The change in % complete between 2.1 and 2.2 is due in every case to the addition of tN checks between 2.1 and 2.2.
The % complete on the tN card is correct upon import and after changing GL
The correct user name is not being written to the csv files. It is now showing as Anonymous. See #6906

**Comment by PhotoNomad0** [comment]
Note:
In reviewing develop build Version 2.2.0 (9ea8fdb), see hang opening rev ult.
[en_ult_rev_book.zip](https://github.com/unfoldingWord/translationCore/files/4628014/en_ult_rev_book.zip)

It is hanging while processing 405 edited verses.  Looks like it never returns from:
`dispatch(batchActions(actionBatch));` in ensureCheckVerseEditsInGroupData()

After further review, it looks like tW has 2334 changes (and tN has a bunch), but batch operations are running very slow since there is a file save for each change.

**Comment by PhotoNomad0** [comment]
Verified that ult rev book above will open without a long hang in translationCore 2.2.0 (4496c12)

**Comment by elsylambert** [comment]
Not seeing the issue in 2.2.0 (4496c12). The Rev_ult project with large edits opens fine in all the tools.

**Comment by cckozie** [comment]
2.2.0 (d786804)
The original problem related to losing tN selections remains fixed.
The Revelation project does now open, although the first time it is selected there is a 7 second delay on the tools page before tC will accept user input. This is written up in #6796.
