### ISSUE TITLE
Export to CSV failing for some projects

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6822]
Export to CSV failing for some projects, here :
[en_newl_rev_book.zip](https://github.com/unfoldingWord/translationCore/files/4439085/en_newl_rev_book.zip)
[en_prct_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4439087/en_prct_tit_book.zip)
<img width="1904" alt="Screen Shot 2020-04-06 at 10 48 33 AM" src="https://user-images.githubusercontent.com/51806180/78571732-8aa4c080-77f4-11ea-897c-eee343142cf7.png">

**Comment by cckozie** [comment]
Not seeing this on my Mac using the Revelation project, but I do see it with the Titus one.

**Comment by birchamp** [comment]
DoD: all books export to CSV with alignments.

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie  - there is a broken selection entry in the titus project.  It looks like the project was one I used for testing (since it has my username in it).  Making the CSV export more robust and improving the logging.  It would surprise me if exporting this would work on older tC versions.

So far not having any problems exporting the rev project.  Will do a little more checking.

**Comment by PhotoNomad0** [comment]
verified in translationCore 2.2.0 (a352530)

**Comment by cckozie** [comment]
Exports succeed in 2.2.0 (02533e8) for attached projects and others at random.

**Comment by cckozie** [comment]
Exports succeed in 2.2.0 (02533e8) for attached projects and others at random.

**Comment by elsylambert** [comment]
Verified in 2.2.0 (02533e8). Export to CSV is working fine for the attached projects and few other existing projects.
