### ISSUE TITLE
Ruth tN "problem with content" error

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6831]
This is the issue that was produced from the Spike #6721

**Comment by PhotoNomad0** [comment]
**Steps to be done:**

string-punctuation-tokenizer v2.0.0 has some API changes.

Modules that will have to be updated with string-punctuation-tokenizer v2.0.0:

1. word-aligner v0.2.15 - update dependencies: 
    - [x] string-punctuation-tokenizer

2. wordmap-lexer v0.3.5 - update dependencies: 
    - [x] string-punctuation-tokenizer

3. tsv-groupdata-parser v0.9.15 - update dependencies:
    - [x] string-punctuation-tokenizer
    - [x] fix generateGroupDataItem() - getting word count based on spaces - fails on Hebrew punctuation that does not have spaces (for example quote string `אֶת־דָּוִֽד` which has `Hebrew Punctuation Maqaf U+05BE`)

4. tc-ui-toolkit v0.15.8 - update dependencies:
    - [x] string-punctuation-tokenizer
    - [x] word-aligner

5. tc-source-content-updater v0.6.17 - update dependencies:
    - [x] tsv-groupdata-parser

6. checking-tool-wrapper 1.0.11 - update dependencies:
    - [x] tc-ui-toolkit

7. translationCore v2.1.1 - update dependencies:
    - [x] checking-tool-wrapper, 
    - [x] string-punctuation-tokenizer, 
    - [x] tc-source-content-updater, 
    - [x] tc-ui-toolkit, 
    - [x] tsv-groupdata-parser, 
    - [x] word-aligner, 
    - [x] wordmap-lexer

Will then need to update/reparse the bundled resources for hbo and en.

**Comment by birchamp** [comment]
DoD: All tN checks will open without error for the book of Ruth unless there are actual content problems.

**Comment by PhotoNomad0** [comment]
Found more items that are breakages not due to word joiner:

- it looks like we are not splitting words on `Hebrew Punctuation Maqaf U+05BE`
![Screen Shot 2020-04-08 at 4 11 51 PM](https://user-images.githubusercontent.com/14238574/78829644-b8d0fe80-79b4-11ea-807d-253b3015d3fa.png)

- the quote string is `אֶת־דָּוִֽד` - it looks like we are not splitting words on `Hebrew Punctuation Maqaf U+05BE`
![Screen Shot 2020-04-08 at 4 12 10 PM](https://user-images.githubusercontent.com/14238574/78829655-bcfd1c00-79b4-11ea-849a-078754ceeae2.png)

- this is a difference bug - looks like duplicate entry?
![Screen Shot 2020-04-08 at 4 13 03 PM](https://user-images.githubusercontent.com/14238574/78829660-bff80c80-79b4-11ea-8d4e-88c982a9d0cb.png)

- for all the below, it looks like we are not splitting words on `Hebrew Punctuation Maqaf U+05BE`
![Screen Shot 2020-04-08 at 4 15 18 PM](https://user-images.githubusercontent.com/14238574/78829667-c2f2fd00-79b4-11ea-8fc9-3495f706fb4c.png)
![Screen Shot 2020-04-08 at 4 15 18 PM](https://user-images.githubusercontent.com/14238574/78829674-c71f1a80-79b4-11ea-85b6-0b9642f67cdd.png)
![Screen Shot 2020-04-08 at 4 15 48 PM](https://user-images.githubusercontent.com/14238574/78829686-cb4b3800-79b4-11ea-9fe4-2f968f89920e.png)
![Screen Shot 2020-04-08 at 4 16 17 PM](https://user-images.githubusercontent.com/14238574/78829690-cedebf00-79b4-11ea-9e18-d7d0427a7344.png)
![Screen Shot 2020-04-08 at 4 17 02 PM](https://user-images.githubusercontent.com/14238574/78829701-d2724600-79b4-11ea-94e0-9483638742f2.png)
![Screen Shot 2020-04-08 at 4 17 25 PM](https://user-images.githubusercontent.com/14238574/78829708-d605cd00-79b4-11ea-97f2-690f4cf00248.png)
![Screen Shot 2020-04-08 at 4 17 33 PM](https://user-images.githubusercontent.com/14238574/78829716-d900bd80-79b4-11ea-9699-01779d868b09.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.2 (44c92e9)  - can open all ruth checks in tN.

**Comment by elsylambert** [comment]
2.1.2 (44c92e9). Not seeing content error message in the tN Checks for Ruth.

**Comment by cckozie** [comment]
2.1.2 (44c92e9) 
No content errors reported in tN for Ruth.

**Comment by elsylambert** [comment]
2.1.2 (44c92e9).
Seeing one content error in Windows and Mac build under the tN category of grammer-connect-time-simultaneous  in Ruth 3:8.
<img width="1792" alt="Screen Shot 2020-04-15 at 9 12 55 AM" src="https://user-images.githubusercontent.com/51806180/79341356-a8aba880-7ef9-11ea-9f4f-f0bb15538bfc.png">
For Review @cckozie
