### ISSUE TITLE
Add Graphite to Electron v 7 for a new version of Electronite

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6840]
The steps for building with a new version of Electron should be well documented.

**Comment by da1nerd** [comment]
Once the patch is ready, here are the build instructions for windows https://github.com/unfoldingWord/translationCore/issues/6660#issuecomment-581279916.

**Comment by da1nerd** [comment]
It should be noted somewhere that using a VPN may cause fetching the sources to fail. After a few failed attempts, I remembered to turn off my VPN and things started working again.

**Comment by da1nerd** [comment]
If you encounter errors while downloading the source, check the errors in the console. You may need to remove a lock file from the git cache. Sometimes I'll delete the last cached repo it was working on as well just to be safe.
You'll also need to delete the electron-gn folder.

**Comment by da1nerd** [comment]
Putting together a release. https://github.com/unfoldingWord-dev/electronite/releases/tag/v7.2.1-graphite

Just waiting on the macOS build to finish.

**Comment by da1nerd** [comment]
waiting to hear back from npm. I accidently published `electronite` without updating the types. Now it won't let me republish that same version.

**Comment by da1nerd** [comment]
I have heard nothing from npm on republishing over a release. So I'm going to create a new tag on electronite and republish the package as `7.2.1-graphite` on npm. Because of how the packages `electronite-packager` and `electronite` are configured, the github tag will need to be named `v7.2.1-graphite-graphite`.

After these changes electronite can be used as usual. The only difference will be the odd version name.

**Comment by da1nerd** [comment]
the release is complete.

**Comment by da1nerd** [comment]
I opened #6863 for writing up some nice documentation.

**Comment by cckozie** [comment]
The devs will need to approve this one

**Comment by mannycolon** [comment]
Verified that 7.2.1-graphite is in the latest build
