### ISSUE TITLE
Critical error screen in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6858]
**IGNORE THIS TOP COMMENT. THIS ONE ERROR CASE WAS MOVED TO #6790**

2.2.0 (02533e8) .

Got critical error screen when traversing through the checks in tN. This project was opened and looked fine in 2.1.1 and 2.1.2.
<img width="1904" alt="Screen Shot 2020-04-06 at 9 36 28 AM" src="https://user-images.githubusercontent.com/51806180/79778171-55c15f00-8306-11ea-8284-54d8d518b6c3.png">

Here is the project:
[hi_test_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4504908/hi_test_tit_book.zip)

After I got the critical error screen, I am not able to open tN at all even after restarting tC. When tN is launched, it throws the Critical error screen.

Resources: tN-v13.8
IRV- v7
Here is the log file: 
[Mon Apr 20 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4504970/Mon.Apr.20.2020.log.zip)

**Comment by elsylambert** [comment]
Got a Critical error screen in tN for a Rev project. After the error appeared, not able to open tN again.
<img width="1904" alt="Screen Shot 2020-04-22 at 4 18 16 PM" src="https://user-images.githubusercontent.com/51806180/80029935-85fb3000-84b5-11ea-9bff-084170a79d2e.png">

**Comment by cckozie** [comment]
2.2.0 (d8fd543) 
[41-MAT.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4519319/41-MAT.usfm.zip)
[6866.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4519320/6866.mp4.zip)
1. Import the attached project
2. Load it in tW with English GL
3. Navigate to a different check
4. Return to the Tools page
5. Load it in wA
6. Navigate to a different verse
7. Return to the Tools page
8. Load it in tN with English GL
9. Navigate to a different check
Note the critical errors screen

![image](https://user-images.githubusercontent.com/8171759/80041004-ea6fbc80-84c0-11ea-950b-07c3e9fa2ab4.png)

**Comment by PhotoNomad0** [comment]
Notes:
- duplicated in this and another project, and it looks like there is a problem with this check: `translationNotes figs-abstractnouns mat 9:35`
- imported Mat usfm without alignments - crashed as soon as I clicked on this check.  Other checks in tN were fine.
- nothing obvious in the check itself that would indicate a problem.
- due to conversion to hooks?
- found component in tc-ui-toolkit: PhraseWithToolTip.  Added some sanity checking.
- looks like there is a problem processing the occurrence note: `Here “kingdom” refers to God’s rule as king. See how you translated this in [Matthew 4:23](rc://en/ult/book/mat/04/23). Alternate translation: “preaching the good news that God will show himself as king” (See: [Abstract Nouns](rc://en/ta/man/translate/figs-abstractnouns))`
- seems related to work done for https://github.com/unfoldingword/translationcore/issues/6351

**Comment by da1nerd** [comment]
@PhotoNomad0 I think we found that use case with the tooltip as well. Remember the TODO that I left in the code? figs-abstractnouns mat 9:35 is the example we needed. :smile: 

I messaged you in zulip as well. Updating the line in the effect to `const anchors = phraseEl.current ? phraseEl.current.getElementsByTagName(a) : [];` fixes the crash. But we'll need to handle the tooltip case now that we have an example.

**Comment by PhotoNomad0** [comment]
@neutrinog - thanks, can you take this issue then?

**Comment by da1nerd** [comment]
Ok I've fixed the bug and added support for rendering the link when there's also a tooltip.
https://github.com/unfoldingWord/tc-ui-toolkit/pull/260

**Comment by PhotoNomad0** [comment]
@neutrinog - waiting on PR to tC.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (236380d)

**Comment by cckozie** [comment]
2.2.0 (d2e40ce) 
Following the steps in my error case above did not produce the critical error screen.
Stepping through all of the tN checks in Matthew and Revelation did not cause the critical error screen.

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (d2e40ce). Verse links and tool tips in smurf bar are working fine and no longer crashing. Tested Mathew and Revelation projects which earlier crashed at mat 9:35 and Rev 9:18. 
Not seeing the critical error screen.

**Comment by BincyJ** [comment]
@birchamp , please confirm if I can go ahead and close this issue.
