### ISSUE TITLE
Blank screen when opening a project in wA after edit in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6877]
2.2.0 (f1fb0cd) 
Problem was found when testing #6675 
[6675 projects.zip](https://github.com/unfoldingWord/translationCore/files/4546782/6675.projects.zip)
[Tue Apr 28 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4545752/Tue.Apr.28.2020.log.zip)

![image](https://user-images.githubusercontent.com/8171759/80488198-954e0380-8923-11ea-9b4b-de67c580ecdb.png)

These usfm projects were copied from the catalog about a year ago and have been used for testing ever since. I'm thinking this may have to do with wordMAP since it seems to be project interdependent.
To replicate the failure:
1. Import the Matthew project and load it in each of the tools.
2. Import the Luke project giving it the same translation id as the Matthew project and load it in each of the tools.
3. Import the Titus project giving it the same translation id as the other two projects.
4. Load the Titus project in tW selecting English as the GL
5. In the check pane, edit verse 1:6 in the accuse group and save the edit.
6. Return to the tools page
7. Load the project in wA and note the error.

**Comment by PhotoNomad0** [comment]
Notes:
- testing in translationCore 2.2.0 (236380d) 

**Net Heap usage:**

Version 2.1.2 (44c92e9)
- Import Matt project - 74 to 444MB
- open each tool - 130 to 776MB
- import Luke and open each tool - 183 to 888 MB
- import Tit and open TN and edit - 223 to 983 MB

Version 2.2.0 (236380d)
- Import Matt project - 219 to 240MB
- open each tool - 74 to 224MB
- import Luke and open each tool - 118 to 841 MB
- import Tit and open TN and edit -100 to 130 MB

Observations:
- did not see obvious signs of memory leaks or memory pressure
- ~did not~ see the crash now and every time now I open wA tool on titus project.

- ~tried running on Mojave VM with 4GB of ram - did not see crash~
- Kos is testing on Mojave Mac with 8GB of ram

**Comment by birchamp** [comment]
DoD: wA screen shows instead of blank screen

**Comment by cckozie** [comment]
@PhotoNomad0 - I am seeing the same problem with my older MacBook. Once I see the failure and after restarting tC, it always crashes when attempting to load the project in wA. I see in the log file an entry stating that contextId.json does not exist. It actually does exist but is empty.
Will now test on my Windows machine.

**Comment by cckozie** [comment]
@PhotoNomad0 - It fails on my Windows machine too.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 - I am seeing the same problem with my older MacBook. Once I see the failure and after restarting tC, it always crashes when attempting to load the project in wA. I see in the log file an entry stating that contextId.json does not exist. It actually does exist but is empty.
> Will now test on my Windows machine.

@cckozie - the empty contextId is concerning, but at least I have a starting point.

**Comment by PhotoNomad0** [comment]
Notes:
- do not see the problem in the last electron 3 release: translationCore 2.2.0 (5214923)
- it does seem to be related to wordmap, because if I change the translation ID, the project will open.  So don't think it is a data corruption issue.
- tried reverting wordmap to previous versions, but still see crash. So don't think it is a wordmap bug.  Tried many combos back all the way to:
```
    "wordmap": "0.7.9",
    "wordmap-lexer": "0.3.5",
```
- is this a memory issue?  ~or infinite recursion in wordmap?~ Added logging of sessionStorage usage to getGlobalAlignmentMemory().  After adding alignments of luke it shows sessionStorage usage to be nearly 6MB (5973595).  Then while adding alignments of mat the window crashes.  Looks like we are running out of session memory (looks like Chrome allows up to 10MB), but not sure how this worked in electron 3.
- But then when I renamed the luke project we crashed during the loading of mat alignments - corruption of mat alignment data?
- it looked like the latest electronite 7.2.1 would fix the problem, but when the final build came out started seeing blank screen again.  Back to the drawing board - see the same error in electron 6.x & 7.x, but not 3.x.
- when I open the tit project in WA, stepping through getGlobalAlignmentMemory(), I see tC go to blank screen after cache.set of the mat project. But it does not throw an exception if I add a try catch.  projectMemory memory size for Luke is 5,124,277. projectMemory memory size for Mat is 4,755,021. There is no error in tC console, but I do see this error in terminal:

```
[1] Window main was killed. {
[1]   preventDefault: [Function: preventDefault],
[1]   sender: WebContents {
[1]     webContents: [Circular],
[1]     history: [ 'http://localhost:3000/' ],
[1]     currentIndex: 0,
[1]     pendingIndex: -1,
[1]     inPageIndex: -1,
[1]     _events: [Object: null prototype] {
[1]       'navigation-entry-commited': [Function],
[1]       '-ipc-message': [Function],
[1]       '-ipc-invoke': [Function],
[1]       '-ipc-message-sync': [Function],
[1]       'pepper-context-menu': [Function],
[1]       crashed: [Array],
[1]       'devtools-reload-page': [Function],
[1]       '-new-window': [Function],
[1]       '-add-new-contents': [Function],
[1]       login: [Function],
[1]       'will-navigate': [Function],
[1]       'did-navigate': [Function],
[1]       destroyed: [Function],
[1]       'devtools-opened': [Array],
[1]       move: [Function],
[1]       activate: [Function],
[1]       'page-title-updated': [Function],
[1]       'render-view-deleted': [Array]
[1]     },
[1]     _eventsCount: 18,
[1]     _maxListeners: 0,
[1]     browserWindowOptions: {
[1]       icon: './TC_Icon.png',
[1]       title: 'translationCore',
[1]       autoHideMenuBar: true,
[1]       minWidth: 1200,
[1]       minHeight: 689,
[1]       show: false,
[1]       center: true,
[1]       webPreferences: [Object]
[1]     }
[1]   }
[1] }
```

**Comment by PhotoNomad0** [comment]
Note:
- to easily test, here is the projects folder:

[projects.zip](https://github.com/unfoldingWord/translationCore/files/4567580/projects.2.zip)

- tC log of the crash:
[temp-electron-7.log.zip](https://github.com/unfoldingWord/translationCore/files/4567578/temp-electron-7.log.zip)

- in electron 3, I was able to go over 31MB without problem.
- session storage is saved here: ~/Library/Application Support/translationCore/Session Storage/

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (78a80ee)

**Comment by cckozie** [comment]
Not seeing the problem in 2.2.0 (64bf0a5). I was able to load the entire new testament and open each book in each of the tools. (The translationCore helper (Renderer) was showing 734.8 MB after all NT books had been loaded.)
Also was able to load the entire OT and open each book in all tools available for it.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (dd79140) with the attached projects.
