### ISSUE TITLE
Github Actions problem that artifact upload failures are flagged as success

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6892]
### User Story

Looking at this build the mac and linux builds are empty: https://github.com/unfoldingWord/translationCore/actions/runs/95247125. Artifact upload failures should not be considered a successful build. 

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
@PhotoNomad0 when you triggered the build again did it work? What am I trying to fix here? Just catching erroneous artifact uploads, or broken builds?

**Comment by da1nerd** [comment]
I don't see any way to catch the error, but I was able to update the upload artifact action we are using. The docs said they fixed some upload problems. Hopefully that works. Unfortunately there's no good way to test this because the failed uploads is not a regular occurrence.

PR ready https://github.com/unfoldingWord/translationCore/pull/6896
