### ISSUE TITLE
Project files with a timestamp in the filename cause a critical error

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6902]
During the archive process (#975) the project filename is appended with a timestamp and an incremental number. If a user moves or copies the project back to the projects folder and then selects it without removing the timestamp from the project name, the critical error screen is displayed after the 'Your project has been named" alert.

**Comment by PhotoNomad0** [comment]
The PR should also fix https://github.com/unfoldingword/translationcore/issues/6435

**Comment by PhotoNomad0** [comment]
Fixed in translationCore 2.2.0 (690092a)

**Comment by cckozie** [comment]
2.2.0 (690092a)
The crash has been fixed, but there is a few unexpected/undesired behaviors. 
1. After selecting a project with the timestamp in the name and clicking OK on the project named alert, the user is returned to the Projects page rather than the Tools page. 
2. If the user attempts an upload of a project whose name contains the timestamp, the upload fails with this alert:
![image](https://user-images.githubusercontent.com/8171759/81701005-0a92fb80-942f-11ea-90b2-12ea2959b224.png)
3. After selecting a project with the timestamp in the name, if the user clicks Cancel on the Project Details page, the user is sent to the Tools page rather than back to the Projects page. The project can now be opened in any of the tools with the project name still containing the timestamp. 
I'm writing these problems up on a new issue (#6908) and passing this one since the specified problem in this issue has been fixed.

**Comment by elsylambert** [comment]
2.2.0 (690092a). Not seeing the error screen on importing back the Archived project. #6908 will be refining the restore process of the project.
