### ISSUE TITLE
Quotation Marks for 'translated as' text after selection.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6983]
### User Story

Quotes are on wrong sides of RTL text:
![Screen Shot 2020-06-09 at 9 47 35 AM copy](https://user-images.githubusercontent.com/14238574/84180026-d540f400-aa54-11ea-8af2-9d6b91f40626.png)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert @cckozie - This one is turning out to be more complicated since the standard quotes are actually inherently LTR, and only apply to a set of western languages.  Other languages use different characters for quotes (e.g. Persian uses "«»", see https://phabricator.wikimedia.org/T221952 for more background data).

It might be simpler just to remove the quotes if the target language is set to RTL.  The text will still stand out because it is a different color, and this would probably be less annoying to the native reader.

There are some RTL quotes in unicode (one example is Hebrew), but then we would have to build and maintain a lookup table.

**Comment by PhotoNomad0** [comment]
Also here is a list of quotes for various languages: https://en.wikipedia.org/wiki/Quotation_mark#Summary_table

**Comment by PhotoNomad0** [comment]
Note: Decided to remove quotes entirely regardless of LTR or RTL.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (318d196)

**Comment by cckozie** [comment]
Not seeing quote marks in 3.0.0 (318d196)

**Comment by elsylambert** [comment]
Verified in 3.0.0 (318d196). Quotation Mark from "Please select translation for" pane are removed.
