### ISSUE TITLE
Disable electron's internet connection

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#701]
Apply Jay's research in #648 .

**Comment by RoyalSix** [comment]
So I've been going at this issue for some time now and I've learned a lot of new things that I was not previously aware of, and thought I'd document it if someone can help me out with this issue or just help me think through it.
1. There is no native javascript/html way to block a hyperlink or connection to the internet (This would be bad for obvious reasons)
2. Electron has methods to receive XMLHttpRequest before they are sent. `focusedWindow.webContents.session.webRequest.onBeforeRequest(filters, callback)`  Because they are performed through the Chrome environment. 
    - This is a bit hacky because there are requests through this method that are not pertaining to XHR at all, but they are Chrome related or image require related. And for some reason the callbacks associated with them are not released on a reload, therefore causing a memory leak on a refresh (crashing the app). This would be the preferred method (After finding a way to clear the callbacks) if it weren't for the fact that libraries do not always have to use the native XHR to access the internet, therefore if a tool maker uses a library directly or indirectly that accesses the internet in some other way we will not be able to intercept it.
This is all that I have so far. I am going to venture a bit in the direction of getting a bit lower level, instead of using such high-level apis/listeners. Moving more towards what is actually happening on the client side before any type of request is sent to access the internet. If we can get or request access to that and make the modifications we need in-order to filter it, then we will be set.
***EDITED***
3. I think I may have found our way
Sandboxing the environment with no network seems to work like a charm although it will require a few additional details.
on mac `sandbox-exec -n no-network npm start` on windows is a bit of a different approach, we may be able to instead block the application from accessing the internet through the windows firewall
- `netsh advfirewall firewall add rule name="block tc in" dir=in program="~\translationCore\node_modules\electron\dist\electron.exe" action=block && netsh advfirewall firewall add rule name="block tc out" dir=out program="~\translationCore\node_modules\electron\dist\electron.exe" action=block`
- `netsh advfirewall firewall delete rule name="block tc in" && netsh advfirewall firewall delete rule name="block tc out"`
