### ISSUE TITLE
User can change the font of resources and projects in the scripture pane. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7037]
### User Story

As a checker, I want to change the font in the scripture pane so that the text renders to my preferences.

### Features / Specifications

- [ ] 3 dot menu item offers the list of fonts in a submenu (current font name highlighted)
- [ ] The user's font choice is retained for that resource.

### Definition of Done

- [ ] User can change the font of any scripture pane resource or project.

### Mockups
![Screenshot-20200707085522-906x420](https://user-images.githubusercontent.com/10272744/86785702-064f1d00-c031-11ea-8407-91323a8a975e.png)

**Comment by mannycolon** [comment]
@birchamp Should the icon be the same used in the project details page?
![Screen Shot 2020-07-07 at 3 19 47 PM](https://user-images.githubusercontent.com/17072300/86831850-6bbd0100-c065-11ea-8559-7a8985604b42.png)

**Comment by mannycolon** [comment]
Verified on  ab7dcb1

**Comment by cckozie** [comment]
3.0.0 (ed14fea) 
The font dropdown lists in the scripture pane are not sorted alphabetically. **Fixed in 3.0.0 (4892ffe)**
![image](https://user-images.githubusercontent.com/8171759/87368816-615aa580-c544-11ea-9f66-5da4871c9e7f.png)

The font selector sometimes appears off of the screen **Fixed in 3.0.0 (4892ffe)**
![Screen Shot 2020-07-13 at 8 18 36 PM](https://user-images.githubusercontent.com/8171759/87369428-16da2880-c546-11ea-9154-318db55be16a.jpg)

Is the default font for Hebrew actually Noto Sans?
![image](https://user-images.githubusercontent.com/8171759/87368982-f493db00-c544-11ea-8260-0e731d8b2f86.png)

**Comment by mannycolon** [comment]
verified on 3ab4a94 and faea329

**Comment by cckozie** [comment]
Looks good in 3.0.0 (4892ffe)
