### ISSUE TITLE
TN Col 1:28 under "When Masculine words include women" produces an error

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7291]
I can reproduce this in tC.  
The discussion on this issue is taking place [here](https://unfoldingword.zulipchat.com/#narrow/stream/309205-Helpdesk---ST/topic/Colossians.201.3A28.20tC.20Alert.20GroupId.3A.20.E2.80.9Cfigs-gendernotations.E2.80.9D/near/279188631).
The helpdesk post is [here](https://forum.door43.org/t/tc-content-and-resources-feedback/1423).

```
There is a problem with the content of this check:

Tool: “translationNotes”
GroupId: “figs-gendernotations”
Reference: “col 1:28”
Gateway Language: “en”
Quote: “ἄνθρωπον”
Occurrence: “-1”

Showing this error. Please check and resolve it. Thank you
```
Running a validation on the English Col TN file doesn't produce any obvious errors.

**Comment by PhotoNomad0** [comment]
@birchamp Looked at the repo (https://git.door43.org/Door43-Catalog/en_tn/src/branch/master/en_tn_52-COL.tsv), and there are two items with -1 for occurrence:

152 | COL | 1 | 28 | lyz1 | figs-explicit | πάντα ἄνθρωπον | **_-1_** | so that we may present every man | Here, every man refers to every person whom Paul has told about Jesus. If every man would be misunderstood in your language, you can include this information. Alternate translation: “every man whom we talk to … each of them … each of them” (See: [[rc://en/ta/man/translate/figs-explicit]])

153 | COL | 1 | 28 | pwff | figs-gendernotations | ἄνθρωπον | **_-1_** |   | Here, the word man does not refer to only male people but to any human being. If man would be misunderstood in your language, you could use a term that refers to humans in general. Alternate translation: “human” (See: [[rc://en/ta/man/translate/figs-gendernotations]])

**Comment by PhotoNomad0** [comment]
Notes:
Fixes required:
- tc-ui-toolkit
  - highlightHelpers.getOccurrenceOfWord()
  - checkAreaHelpers.getQuoteAsArray()

Current work is in branch `feature-mcleanb-7291`

**Comment by PhotoNomad0** [comment]
@birchamp How does this look?
![Screen Shot 2022-05-09 at 1 45 34 PM](https://user-images.githubusercontent.com/14238574/167467515-98776ad0-0790-42a1-be07-3b6c2652d043.png)

**Comment by PhotoNomad0** [comment]
@elsylambert fix is in translationCore 3.2.0 (12353d0) 

Testing the Col 1:28, you should see:
![Screen Shot 2022-05-10 at 1 17 09 PM](https://user-images.githubusercontent.com/14238574/167686106-5f87d581-a895-46f0-a821-34c49467fb53.png)

**Comment by elsylambert** [comment]
@PhotoNomad0 I am not able to see the category "When Masculine words include woman". I downloaded en resources with latest tN. What am I missing?

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (12353d0).

**Comment by elsylambert** [comment]
@PhotoNomad0 while doing regression on translationCore 3.3.0 (fb96f72), I found that the highlight is shown correctly for the three occurrences of the word, but the selections shows two occurrences instead of three as shown in the screenshot:

<img width="1437" alt="Screen Shot 2022-08-18 at 9 29 53 AM" src="https://user-images.githubusercontent.com/51806180/185407738-6ac27e1f-d97f-4160-98d2-9fa855bcdbd0.png">

Project:
[en_ulb_php_book.zip](https://github.com/unfoldingWord/translationCore/files/9374239/en_ulb_php_book.zip)

Tool: tN , Category: Forms of 'You', verse: 3:2

**Comment by PhotoNomad0** [comment]
Note:
- the UI is in InstructionsArea and mode === 'select'

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 while doing regression on translationCore 3.3.0 ([fb96f72](https://github.com/unfoldingWord/translationCore/commit/fb96f725f13bae5c1c9559746e3fb438cd6f3e84)), I found that the highlight is shown correctly for the three occurrences of the word, but the selections shows two occurrences instead of three as shown in the screenshot:
> 
> <img alt="Screen Shot 2022-08-18 at 9 29 53 AM" width="1437" src="https://user-images.githubusercontent.com/51806180/185407738-6ac27e1f-d97f-4160-98d2-9fa855bcdbd0.png">
> 
> Project: [en_ulb_php_book.zip](https://github.com/unfoldingWord/translationCore/files/9374239/en_ulb_php_book.zip)
> 
> Tool: tN , Category: Forms of 'You', verse: 3:2

@elsylambert - It looks like this is behaving as it always has.  There is a subtitle difference between your screenshot and the two screenshots above that one.

**Comment by PhotoNomad0** [comment]
The confusing thing is that the order of the text changes after you make the selections.  The selections have always been displayed simply by putting ellipsis between the first group of selected text and the last group.

**Comment by PhotoNomad0** [comment]
@birchamp This is showing the selections the same way as it always has for the last 4 years.  I think if we want to show all the selections we should make a new issue.

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp Maybe a better way to put it is that this is an issue to fix the display of multiple words in the GL text.  And that is the text shown above the `Has been translated as:`.  It is being displayed correctly as `Beware of ... beware of ... beware of`.

**Comment by elsylambert** [comment]
@PhotoNomad0 You are correct about- the text shown above the Has been translated as:. It is being displayed correctly as Beware of ... beware of ... beware of. I was asking about the GL Text display after you make selections for those words. I wrote it separately in https://github.com/unfoldingWord/translationCore/issues/7409
