### ISSUE TITLE
Handle " & " for discontiguous original language highlights

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7294]
According to [the new spec](https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870) ellipsis is changed from ... to " & " and this breaks the highlighting in the scripture pane. Both of them should work at least for now. 

DoD:
---
" & " in the original quote should highlight the discontinuous words

Details:
---
Any use of the " & " or the ellipsis in the original quote field should highlight discontiguous words. There can be multiple & per original quote.

**Comment by PhotoNomad0** [comment]
@birchamp - it does seem that you are expanding the spec in the description.  Note that the spec referenced only mentions the use case of `A three-character sequence & (ampersand with surrounding spaces) `.  That is probably safer use case than just a single ampersand.

**Comment by birchamp** [comment]
Yes we do want to allow for both ... and " & ".  You're right, we do want to include spaces

**Comment by PhotoNomad0** [comment]
@birchamp - Currently I am converting the & to ellipsis when resources are downloaded so that tC can easily handle either without a lot of code changes.  But the side effect is that they are displayed in the checking tools as ellipsis.  Is this acceptable for this issue or do you want more changes?  Here is an example where the & was converted to ellipsis on download.

![Screen Shot 2022-07-07 at 3 24 18 PM](https://user-images.githubusercontent.com/14238574/177868798-e8fc83cc-dd0d-4b68-a34e-d39756c2b8c7.png)

**Comment by PhotoNomad0** [comment]
I suppose another option would be to convert ellipsis to & on download and display & in the checking tool.  But I think it might get too complicated trying to show either ellipsis or & in tool based on the source tsv format.

**Comment by birchamp** [comment]
We're moving to the ampersand, so let's display it as an ampersand even if it is an ellipsis

**Comment by PhotoNomad0** [comment]
**Note:**
- source content updater:
  - fix generateGroupDataItem()
  - getWordOccurrencesForQuote()
  - cleanQuoteString()
  - replace hasEllipsis() and much of ELLIPSIS

- tCore:
  - will need to do migration of projects that have ellipsis
    - example project path: ~/translationCore/projects/en_ult_tit_book/.apps/translationCore/checkData/selections/tit/1/1/2018-08-20T19_29_49.794Z.json
    - Will need to add migration v8 to src/js/helpers/ProjectMigration/index.js?
    - use migrateToVersion7 as an example switching verseEdits folder for selections

- tc-ui-toolkit:
  - find usages of ellipsis, change to break_char

- checking-tool-wrapper
  - don't see anything

**Comment by PhotoNomad0** [comment]
@elsylambert the issue is fixed in the latest develop build [e917d7b].  Most of the latest changes are under the covers.  But here is an example of what you should see in checking tools:
<img width="1298" alt="Screen Shot 2022-09-13 at 8 33 18 AM" src="https://user-images.githubusercontent.com/14238574/189902549-64575ded-a276-4438-9555-acec20331e93.png">

**Comment by elsylambert** [comment]
Looks good in translationCore 3.4.0 (984c28c).
<img width="1501" alt="Screen Shot 2022-09-16 at 9 16 27 AM" src="https://user-images.githubusercontent.com/51806180/190647775-45455688-866d-409d-b968-ac3b1498ee7f.png">
