### ISSUE TITLE
SPIKE: What does tC do with multiple discontiguous snippets (...)

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7303]
What happens in tC when "εἴ τις…εἴ τι…εἴ τις…εἴ τις" is the snippet in Phil 2:1?  

See: ID "b1q7" in https://git.door43.org/unfoldingWord/en_tn/src/branch/master/en_tn_51-PHP.tsv

More info: 
https://github.com/unfoldingWord/tc-create-app/issues/1183
ROM 5:12 as well https://unfoldingword.zulipchat.com/#narrow/stream/214041-CONTENT---UR/topic/Romans.20BP/near/281708673

**Comment by PhotoNomad0** [comment]
> What happens in tC when "εἴ τις…εἴ τι…εἴ τις…εἴ τις" is the snippet in Phil 2:1?
> 
> See: ID "b1q7" in https://git.door43.org/unfoldingWord/en_tn/src/branch/master/en_tn_51-PHP.tsv
> 

@birchamp That example does not currently have multiple ellipsis, but only one.  Maybe this is a data problem, or the tool they are using to make the selection?

PHP | 2 | 1 | b1q7 | figs-explicit | **_εἴ τις…παράκλησις ἐν Χριστῷ, εἴ τι παραμύθιον ἀγάπης, εἴ τις κοινωνία Πνεύματος, εἴ τις σπλάγχνα καὶ οἰκτιρμοί_** | 1 | If there is any encouragement in Christ | The phrase if there is any, which occurs one time in this verse, and the phrase if any, which occurs three times in this verse, appear to be hypothetical statements. However, they are not hypothetical, because they each express things which are true. If it would be clearer in your language, you could express the meaning of these phrases explicitly. Alternate translation: “because of the encouragement which comes from Christ, because there is comfort from his love, because of the fellowship of the Spirit, because you have affections and compassions” or “since Christ has encouraged you, since there is comfort from his love, since there is fellowship in the Spirit, since you have affections and compassions” (See: [[rc://en/ta/man/translate/figs-explicit]])

**Comment by birchamp** [comment]
@PhotoNomad0 Yes, Larry had to change it so it would highlight in tC Create.  We're just trying to discover what would happen in tC if he hadn't changed it.  We want tC Create to reflect what tC will do.

**Comment by PhotoNomad0** [comment]
Created a unit test in tsv-groupdata-parser, which is used by the tC source code downloader.  Looks like it fills everything in giving the final quote string as `εἴ τις οὖν παράκλησις ἐν Χριστῷ, εἴ τι εἴ τις ὖν παράκλησις ἐν Χριστῷ, εἴ τι παραμύθιον ἀγάπης, εἴ τις κοινωνία Πνεύματος, εἴ τις`  which is what tC will highlight.  It looks like it works as it should.

**Comment by birchamp** [comment]
@PhotoNomad0  So the ... ellipsis is actually for highlighting discontiguous words but not the whole phrase. In the [forum post on the old TSV9 format](https://forum.door43.org/t/translationnotes-tsv-format/57), it says: "A Unicode ellipsis character (…) indicates that the quote is discontinuous; software should interpret this in a non-greedy manner"

**Comment by birchamp** [comment]
I'm curious how it works with just 1 ellipsis. Does it just highlight each of the words and not what's in between. We don't have a definition for multiple ellipses as far as I can tell.  @PhotoNomad0

**Comment by PhotoNomad0** [comment]
Multiple ellipsis (﻿﻿hacking the note in Phil 2:1 to be  `εἴ τις…εἴ τις…εἴ τις`):
<img width="1273" alt="Screen Shot 2022-05-12 at 4 42 50 PM copy" src="https://user-images.githubusercontent.com/14238574/168277688-c0acd637-4aa9-4f3f-bfd4-97127244f1bc.png">

Single Ellipsis:
![Screen Shot 2022-05-12 at 11 23 09 AM copy](https://user-images.githubusercontent.com/14238574/168277736-3fc97328-d7db-408a-a9fc-1d6960135884.png)

**Comment by birchamp** [comment]
@birchamp make issues in tCC and gE for fixing multiple ellipsis logic.

**Comment by PhotoNomad0** [comment]
@birchamp It looks like there is nothing to be done on this issue for tC?  It looks to me that it is functioning correctly.
