### ISSUE TITLE
 Fix the display of multiple words in the GL text.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7409]
#7291- Multiple occurrences of a word, does not display after the selection is made in the Selection area.
the highlight is shown correctly for the three occurrences of the word, but the selections shows two occurrences instead of three as shown in the screenshot:

<img width="1437" alt="Screen Shot 2022-08-18 at 9 29 53 AM" src="https://user-images.githubusercontent.com/51806180/185407738-6ac27e1f-d97f-4160-98d2-9fa855bcdbd0.png">

Project:
[en_ulb_php_book.zip](https://github.com/unfoldingWord/translationCore/files/9374239/en_ulb_php_book.zip)

Tool: tN , Category: Forms of 'You', verse: 3:2

**Comment by PhotoNomad0** [comment]
@elsylambert What you have highlighted is not GL text, it is the selection(s) made to target text. The selections have always been displayed simply by putting ellipsis between the first group of selected text and the last group when there are multiple selections.  This is looking like a new feature request rather than a bug.

**Comment by elsylambert** [comment]
@PhotoNomad0  I got it now. I think the ellipsis confused me. Thanks for refreshing my memory.

**Comment by PhotoNomad0** [comment]
@elsylambert - Go ahead and leave this issue.  But just change the title to `target selections` in instead of `GL text`.  

Also I think this is another place where we need to switch from using ellipsis to the ampersand.
