### ISSUE TITLE
Print Preview displays the formats the chapter numbers as right aligned.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7523]
### Description

When you open a book of the Bible in the print preview it shows chapter numbers in the wrong side of the column

**Screenshots**
![CleanShot 2023-08-12 at 18.34.10@2x.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/466f3bc4-07a6-4448-be7f-460d47aa5c43)

**Expected behavior:** [What you expect to happen]
Chapter numbers should be left aligned in ltr languages.

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v3.5.0  |
| build #      |         |
| OS           |  MacOS       |

**Comment by PhotoNomad0** [comment]
Sure enough it is.  It looks like we are passing the correct text direction to proskomma-react-hooks. So will have to investigate if there is an update that would fix it.  Since we implemented this last fall, I believe that there have been lots of rewrites to the proskomma libraries.

On closer investigation, It looks like the css is hard coded to float the chapter right, so I think I can quickly fix in the css.  Probably also want some additional padding on right or left depending on position.

Are you looking to create a 3.5.1 patch release? Or halt the 3.5.0 release and fix that?

**Comment by birchamp** [comment]
I've already announced 3.5.0 so it's possible that people have downloaded it. So we need to do a hot fix release 3.5.1.

**Comment by PhotoNomad0** [comment]
> I've already announced 3.5.0 so it's possible that people have downloaded it. So we need to do a hot fix release 3.5.1.

I'm glad you chose that option - as I thought through the steps required to back out a release.  Since it is fully released on github, and though it is possible on github to delete and recreate the release, it is strongly discouraged.

**Comment by PhotoNomad0** [comment]
@elsylambert - this fix is in tCore Version 3.5.1 (6e1cd7b)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.5.1 (6e1cd7b). Chapter numbers are left aligned for LTR Languages and right aligned for RTL Languages.
