### ISSUE TITLE
Highlights not working for a loaded Aligned Bible resource

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7576]
Highlighting not showing for an aligned scripture resource, when we add a it using URL in projects >Load bible resource (USFM).
- Open tC and on Projects page, click on the the three-dot menu for Projects, you can see the option to Load Bible resources.

<img width="1490" alt="Screenshot 2024-06-18 at 2 18 28 PM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/36c971f6-a0a4-4c15-8dc0-c819c98360ec">

- Paste the link: https://git.door43.org/Worldview/en_bsb in there and open TN for this project, you would be able to see the Resources in scripture pane.
![image](https://github.com/unfoldingWord/translationCore/assets/51806180/f992d6ed-460d-4dcf-aee9-23c6679eabf0)

- Note that the highlights are not shown for the Aligned resource.

**Comment by elsylambert** [comment]
@PhotoNomad0

**Comment by PhotoNomad0** [comment]
@elsylambert It's now fixed in latest develop branch translationCore 3.6.5 (4dc6b21)

Just remember to input the url again for the BSB again to force it to reload and reprocess the bible.

This is how it looks now - should work in both tN and tW:

<img width="1214" alt="Screenshot 2024-06-19 at 2 35 37 PM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/30c1c1ed-2897-486d-8f39-4e77c348954d">

**Comment by elsylambert** [comment]
Works fine in translationCore 3.6.5 (4dc6b21). Seeing highlights working for an aligned bible resource.
<img width="1636" alt="Screenshot 2024-06-21 at 10 31 29 AM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/b48dba6f-9630-4751-b601-83de7a09f595">
