### ISSUE TITLE
SPIKE: Research Separating Apps/Modules to Repos

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#92]
As a developer I want an educated estimate to tasks to be completed so that we can plan.

**Comment by benjore** [comment]
#27

**Comment by ihoegen** [comment]
I guess for now, I'll talk to myself in here as I sort through how to do this.

So to start this off, I think we should create a repo dedicated to holding a manifest file, that includes a list of packages, and the repo that they are located at. This manifest file will be referenced by the application when a module is installed. It should include a version number too, so we can update packages.

# What we need

## From Modules
- Versioning Number - This is needed so we know if the local module is up to date. Needs to be on manifest.
- Module developers can submit pull requests to the centralized repo, and all they should be able to do is update a manifest.json file, adding their package name, version number, and their repo location. In the repo, they should tag the release so that we pull the correct code in.

## From translationCore
- Workflow - So we need to have a package manager. In the the system app data folder, we will have a translationCore folder, which will have 2 folders: packages, and packages-compiled. When a module is downloaded, it is downloaded to the packages folder, then compiled into packages-compiled. When an update is available, the same thing is done. Uninstall just deletes the folder inside of packages and packages-compiled. When a package is required, it is pulled from packages-compiled.
- Package Manager - Needs to give a way to view the list of projects in the manifest.json, and the option to install, uninstall, and to check for updates.

**Comment by ihoegen** [comment]
I'd say my research is about done, new spikes will be created as I run into issues.
