### ISSUE TITLE
2. Project: Edit Project Details

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#972]
- [ ] Editable fields:
  - [ ] Book name - Choose from a pre-populated list of all 66 books of the Bible
  - [ ] Language name - Choose from a list of languages from the API
  - [ ] Language direction - Right-to-Left (RTL) or Left-to-Right (LTR)

**Comment by Thajny** [comment]
![edit detail 2](https://cloud.githubusercontent.com/assets/21183377/24427383/5f7cda40-13d0-11e7-9fe1-8978c743a6e0.png)
![edit details 1](https://cloud.githubusercontent.com/assets/21183377/24427384/5f7e802a-13d0-11e7-8bcd-bd3df816c83f.png)

**Comment by Thajny** [comment]
Some notes: 
clicking on "edit project details" will expand the card vertically and reposition the info. 
Everything is a text field - if it is disabled, it shows up as grayed out, if it is editable it turns blue with black text. 

Also: 
A few things unrelated to the edit details card may be outdated/inconsistent. Use this screenshot ONLY for the edit details.
Typing in a field will bring up a list of words matching what the user has typed. If they stop typing mid-sentence and click somewhere else, it will revert back to how it was. 
The user has to hit "confirm" in order to save changes. Click anywhere or canceling this process will not save any changes made.

**Comment by Thajny** [comment]
![edit details 1](https://cloud.githubusercontent.com/assets/21183377/24563423/d3da36e0-1613-11e7-9fd1-3940eee6433e.png)
![project context menu](https://cloud.githubusercontent.com/assets/21183377/24563432/dbbd9622-1613-11e7-98f8-8da412851e8c.png)

**Comment by benjore** [comment]
dup of #2416
